import mock
import pytest
from pyspark.sql.types import (
    StructType,
    StructField,
    StringType,
    LongType,
    TimestampType,
    BooleanType,
    ArrayType,
    DoubleType,
)
import odw.test.util.mock_util.import_mock_notebook_utils  # noqa: F401
from odw.core.etl.transformation.curated.appeal_s78_curation_process import (
    AppealS78CurationProcess,
)
from odw.test.integration_test.etl.etl_test_case import ETLTestCase
from odw.test.util.assertion import (
    assert_dataframes_equal,
    assert_etl_result_successful,
)
from odw.test.util.session_util import PytestSparkSessionUtil
from datetime import datetime


pytestmark = pytest.mark.skip(reason="Curated logic not implemented yet")


def _harmonised_row(**overrides):
    base = {
        "caseReference": "12345",
        "AppealS78ID": 1,
        "caseId": 123,
        "submissionId": "fkgf3gl3lgiufd3ukg3dgdlgj",
        "caseStatus": "assign_case_officer",
        "caseType": "W",
        "caseProcedure": "written",
        "lpaCode": "someCodeA",
        "caseOfficerId": None,
        "inspectorId": None,
        "allocationLevel": None,
        "allocationBand": None,
        "caseSpecialisms": None,
        "caseSubmittedDate": "2025-01-01T00:00:00.000Z",
        "caseCreatedDate": "2026-01-01T00:00:00.000Z",
        "caseUpdatedDate": "2027-01-01T00:00:00.000Z",
        "caseValidDate": None,
        "caseValidationDate": None,
        "caseValidationOutcome": None,
        "caseValidationInvalidDetails": None,
        "caseValidationIncompleteDetails": None,
        "caseExtensionDate": None,
        "caseStartedDate": None,
        "casePublishedDate": None,
        "linkedCaseStatus": None,
        "leadCaseReference": None,
        "lpaQuestionnaireDueDate": None,
        "lpaQuestionnaireSubmittedDate": None,
        "lpaQuestionnaireCreatedDate": None,
        "lpaQuestionnairePublishedDate": None,
        "lpaQuestionnaireValidationOutcome": None,
        "lpaQuestionnaireValidationOutcomeDate": None,
        "lpaQuestionnaireValidationDetails": None,
        "lpaStatement": None,
        "caseWithdrawnDate": None,
        "caseTransferredDate": None,
        "transferredCaseClosedDate": None,
        "caseDecisionOutcomeDate": None,
        "caseDecisionPublishedDate": None,
        "caseDecisionOutcome": None,
        "caseCompletedDate": None,
        "enforcementNotice": None,
        "applicationReference": "123",
        "applicationDate": "2028-01-01T00:00:00.000Z",
        "applicationDecision": "refused",
        "applicationDecisionDate": "2029-01-01T00:00:00.000Z",
        "applicationDecisionDueDate": None,
        "caseSubmissionDueDate": "2030-01-01T00:00:00.000Z",
        "siteAddressLine1": "e2e Test Address",
        "siteAddressLine2": "Somewhere St",
        "siteAddressTown": "Somewhereville",
        "siteAddressCounty": "Somewhere",
        "siteAddressPostcode": "BS21 6LE",
        "siteAccessDetails": ["Come and see", ""],
        "siteSafetyDetails": ["It's dangerous", ""],
        "siteAreaSquareMetres": 22.0,
        "floorSpaceSquareMetres": 22.0,
        "isCorrectAppealType": None,
        "isGreenBelt": False,
        "inConservationArea": None,
        "ownsAllLand": True,
        "ownsSomeLand": True,
        "knowsOtherOwners": "Some",
        "knowsAllOwners": "Some",
        "advertisedAppeal": True,
        "notificationMethod": None,
        "ownersInformed": True,
        "originalDevelopmentDescription": "A test description",
        "changedDevelopmentDescription": False,
        "newConditionDetails": None,
        "extraConditionsDetails": None,
        "nearbyCaseReferences": [],
        "neighbouringSiteAddresses": None,
        "reasonForNeighbourVisits": None,
        "affectedListedBuildingNumbers": None,
        "changedListedBuildingNumbers": None,
        "preserveGrantLoan": None,
        "consultHistoricEngland": None,
        "appellantCostsAppliedFor": False,
        "lpaCostsAppliedFor": None,
        "agriculturalHolding": True,
        "tenantAgriculturalHolding": True,
        "otherTenantsAgriculturalHolding": None,
        "informedTenantsAgriculturalHolding": None,
        "appellantProcedurePreference": None,
        "appellantProcedurePreferenceDetails": "eiusmod ex exercitation",
        "appellantProcedurePreferenceDuration": 1.0,
        "appellantProcedurePreferenceWitnessCount": 5.0,
        "statusPlanningObligation": "proident aute",
        "affectsScheduledMonument": None,
        "hasProtectedSpecies": None,
        "isAonbNationalLandscape": None,
        "designatedSitesNames": [],
        "isGypsyOrTravellerSite": None,
        "isPublicRightOfWay": None,
        "eiaEnvironmentalImpactSchedule": None,
        "eiaDevelopmentDescription": None,
        "eiaSensitiveAreaDetails": None,
        "eiaColumnTwoThreshold": None,
        "eiaScreeningOpinion": None,
        "eiaRequiresEnvironmentalStatement": None,
        "eiaCompletedEnvironmentalStatement": None,
        "hasStatutoryConsultees": None,
        "consultedBodiesDetails": None,
        "hasInfrastructureLevy": None,
        "isInfrastructureLevyFormallyAdopted": None,
        "infrastructureLevyAdoptedDate": None,
        "infrastructureLevyExpectedDate": None,
        "lpaProcedurePreference": None,
        "lpaProcedurePreferenceDetails": None,
        "lpaProcedurePreferenceDuration": None,
        "caseworkReason": None,
        "importantInformation": None,
        "jurisdiction": None,
        "redeterminedIndicator": None,
        "dateCostsReportDespatched": None,
        "dateNotRecoveredOrDerecovered": None,
        "dateRecovered": None,
        "originalCaseDecisionDate": None,
        "targetDate": None,
        "appellantCommentsSubmittedDate": None,
        "appellantStatementDueDate": None,
        "appellantStatementSubmittedDate": None,
        "appellantProofsSubmittedDate": None,
        "finalCommentsDueDate": None,
        "interestedPartyRepsDueDate": None,
        "lpaCommentsSubmittedDate": None,
        "lpaProofsSubmittedDate": None,
        "lpaStatementSubmittedDate": None,
        "proofsOfEvidenceDueDate": None,
        "siteNoticesSentDate": None,
        "statementDueDate": None,
        "caseManagementConferenceDate": None,
        "numberOfResidencesNetChange": None,
        "siteGridReferenceEasting": None,
        "siteGridReferenceNorthing": None,
        "siteViewableFromRoad": None,
        "siteWithinSSSI": None,
        "typeOfPlanningApplication": "full-appeal",
        "developmentType": "minor-dwellings",
        "statementOfCommonGroundDueDate": None,
        "planningObligationDueDate": None,
        "hasLandownersPermission": None,
        "wasApplicationRefusedDueToHighwayOrTraffic": None,
        "didAppellantSubmitCompletePhotosAndPlans": None,
        "isSiteInAreaOfSpecialControlAdverts": None,
        "advertDetails": None,
        "padsSapId": None,
        "enforcementNoticeReference": None,
        "descriptionOfAllegedBreach": None,
        "dateAppellantContactedPins": None,
        "ownerOccupancyStatus": None,
        "occupancyConditionsMet": None,
        "enforcementAppealGroundsDetails": None,
        "applicationElbAppealGroundsDetails": None,
        "applicationMadeAndFeePaid": None,
        "noticeRelatesToBuildingEngineeringMiningOther": None,
        "changeOfUseRefuseOrWaste": None,
        "changeOfUseMineralExtraction": None,
        "changeOfUseMineralStorage": None,
        "relatesToErectionOfBuildingOrBuildings": None,
        "relatesToBuildingWithAgriculturalPurpose": None,
        "relatesToBuildingSingleDwellingHouse": None,
        "previousPlanningPermissionGranted": None,
        "issueDateOfEnforcementNotice": None,
        "effectiveDateOfEnforcementNotice": None,
        "didAppellantAppealLpaDecision": None,
        "dateLpaDecisionDue": None,
        "dateLpaDecisionReceived": None,
        "areaOfAllegedBreachInSquareMetres": None,
        "doesAllegedBreachCreateFloorSpace": None,
        "floorSpaceCreatedByBreachInSquareMetres": None,
        "applicationPartOrWholeDevelopment": None,
        "hasPcnBeenServed": None,
        "isSiteWithin67MOfTrunkRd": None,
        "affectedTrunkRoadName": None,
        "isSiteOnCrownLand": None,
        "stopNoticeExists": None,
        "isSiteWithin400MOfMineralInterest": None,
        "isSiteWithin250MOfLandfill": None,
        "hasDevelopmentInvolvedWasteImportation": None,
        "isSiteSubjectToArticle4Direction": None,
        "article4AffectedDevelopmentRights": None,
        "pcnRestrictedDevelopmentRights": None,
        "applicationMadeUnderActSection": None,
        "siteUseAtTimeOfApplication": None,
        "appealUnderActSection": None,
        "lpaConsiderAppealInvalid": None,
        "lpaAppealInvalidReasons": None,
        "discontinuanceNoticeServedReason": None,
        "discontinuanceNoticeServedOtherReason": None,
        "wasRetrospectivePlanningApplicationMade": None,
        "reasonForAppealAppellant": None,
        "screeningOpinionIndicatesEiaRequired": None,
        "significantChangesAffectingApplicationAppellant": None,
        "significantChangesAffectingApplicationLpa": None,
        "migrated": None,
        "ODTSourceSystem": "ODT",
        "SourceSystemID": "5",
        "IngestionDate": datetime(2031, 1, 1),
        "ValidTo": "2040-01-01 00:00:00.000",
        "RowID": "",
        "IsActive": "Y",
        "message_id": "crvykejvkjgh3ekghjgkg34",
        "listOfDocumentsBeforeDecision": None,
    }
    return base | overrides


def _harmonised_schema():
    return StructType(
        [
            StructField("caseReference", StringType(), True),
            StructField("AppealS78ID", LongType(), True),
            StructField("caseId", LongType(), True),
            StructField("submissionId", StringType(), True),
            StructField("caseStatus", StringType(), True),
            StructField("caseType", StringType(), True),
            StructField("caseProcedure", StringType(), True),
            StructField("lpaCode", StringType(), True),
            StructField("caseOfficerId", StringType(), True),
            StructField("inspectorId", StringType(), True),
            StructField("allocationLevel", StringType(), True),
            StructField("allocationBand", DoubleType(), True),
            StructField("caseSpecialisms", ArrayType(StringType(), True), True),
            StructField("caseSubmittedDate", StringType(), True),
            StructField("caseCreatedDate", StringType(), True),
            StructField("caseUpdatedDate", StringType(), True),
            StructField("caseValidDate", StringType(), True),
            StructField("caseValidationDate", StringType(), True),
            StructField("caseValidationOutcome", StringType(), True),
            StructField(
                "caseValidationInvalidDetails", ArrayType(StringType(), True), True
            ),
            StructField(
                "caseValidationIncompleteDetails", ArrayType(StringType(), True), True
            ),
            StructField("caseExtensionDate", StringType(), True),
            StructField("caseStartedDate", StringType(), True),
            StructField("casePublishedDate", StringType(), True),
            StructField("linkedCaseStatus", StringType(), True),
            StructField("leadCaseReference", StringType(), True),
            StructField("lpaQuestionnaireDueDate", StringType(), True),
            StructField("lpaQuestionnaireSubmittedDate", StringType(), True),
            StructField("lpaQuestionnaireCreatedDate", StringType(), True),
            StructField("lpaQuestionnairePublishedDate", StringType(), True),
            StructField("lpaQuestionnaireValidationOutcome", StringType(), True),
            StructField("lpaQuestionnaireValidationOutcomeDate", StringType(), True),
            StructField(
                "lpaQuestionnaireValidationDetails", ArrayType(StringType(), True), True
            ),
            StructField("lpaStatement", StringType(), True),
            StructField("caseWithdrawnDate", StringType(), True),
            StructField("caseTransferredDate", StringType(), True),
            StructField("transferredCaseClosedDate", StringType(), True),
            StructField("caseDecisionOutcomeDate", StringType(), True),
            StructField("caseDecisionPublishedDate", StringType(), True),
            StructField("caseDecisionOutcome", StringType(), True),
            StructField("caseCompletedDate", StringType(), True),
            StructField("enforcementNotice", BooleanType(), True),
            StructField("applicationReference", StringType(), True),
            StructField("applicationDate", StringType(), True),
            StructField("applicationDecision", StringType(), True),
            StructField("applicationDecisionDate", StringType(), True),
            StructField("applicationDecisionDueDate", StringType(), True),
            StructField("caseSubmissionDueDate", StringType(), True),
            StructField("siteAddressLine1", StringType(), True),
            StructField("siteAddressLine2", StringType(), True),
            StructField("siteAddressTown", StringType(), True),
            StructField("siteAddressCounty", StringType(), True),
            StructField("siteAddressPostcode", StringType(), True),
            StructField("siteAccessDetails", ArrayType(StringType(), True), True),
            StructField("siteSafetyDetails", ArrayType(StringType(), True), True),
            StructField("siteAreaSquareMetres", DoubleType(), True),
            StructField("floorSpaceSquareMetres", DoubleType(), True),
            StructField("isCorrectAppealType", BooleanType(), True),
            StructField("isGreenBelt", BooleanType(), True),
            StructField("inConservationArea", BooleanType(), True),
            StructField("ownsAllLand", BooleanType(), True),
            StructField("ownsSomeLand", BooleanType(), True),
            StructField("knowsOtherOwners", StringType(), True),
            StructField("knowsAllOwners", StringType(), True),
            StructField("advertisedAppeal", BooleanType(), True),
            StructField("notificationMethod", ArrayType(StringType(), True), True),
            StructField("ownersInformed", BooleanType(), True),
            StructField("originalDevelopmentDescription", StringType(), True),
            StructField("changedDevelopmentDescription", BooleanType(), True),
            StructField("newConditionDetails", StringType(), True),
            StructField("extraConditionsDetails", StringType(), True),
            StructField("nearbyCaseReferences", ArrayType(StringType(), True), True),
            StructField(
                "neighbouringSiteAddresses",
                ArrayType(
                    StructType(
                        [
                            StructField(
                                "neighbouringSiteAddressLine1", StringType(), True
                            ),
                            StructField(
                                "neighbouringSiteAddressLine2", StringType(), True
                            ),
                            StructField(
                                "neighbouringSiteAddressTown", StringType(), True
                            ),
                            StructField(
                                "neighbouringSiteAddressCounty", StringType(), True
                            ),
                            StructField(
                                "neighbouringSiteAddressPostcode", StringType(), True
                            ),
                            StructField(
                                "neighbouringSiteAccessDetails", StringType(), True
                            ),
                            StructField(
                                "neighbouringSiteSafetyDetails", StringType(), True
                            ),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("reasonForNeighbourVisits", StringType(), True),
            StructField(
                "affectedListedBuildingNumbers", ArrayType(StringType(), True), True
            ),
            StructField(
                "changedListedBuildingNumbers", ArrayType(StringType(), True), True
            ),
            StructField("preserveGrantLoan", BooleanType(), True),
            StructField("consultHistoricEngland", BooleanType(), True),
            StructField("appellantCostsAppliedFor", BooleanType(), True),
            StructField("lpaCostsAppliedFor", BooleanType(), True),
            StructField("agriculturalHolding", BooleanType(), True),
            StructField("tenantAgriculturalHolding", BooleanType(), True),
            StructField("otherTenantsAgriculturalHolding", BooleanType(), True),
            StructField("informedTenantsAgriculturalHolding", BooleanType(), True),
            StructField("appellantProcedurePreference", StringType(), True),
            StructField("appellantProcedurePreferenceDetails", StringType(), True),
            StructField("appellantProcedurePreferenceDuration", DoubleType(), True),
            StructField("appellantProcedurePreferenceWitnessCount", DoubleType(), True),
            StructField("statusPlanningObligation", StringType(), True),
            StructField("affectsScheduledMonument", BooleanType(), True),
            StructField("hasProtectedSpecies", BooleanType(), True),
            StructField("isAonbNationalLandscape", BooleanType(), True),
            StructField("designatedSitesNames", ArrayType(StringType(), True), True),
            StructField("isGypsyOrTravellerSite", BooleanType(), True),
            StructField("isPublicRightOfWay", BooleanType(), True),
            StructField("eiaEnvironmentalImpactSchedule", StringType(), True),
            StructField("eiaDevelopmentDescription", StringType(), True),
            StructField("eiaSensitiveAreaDetails", StringType(), True),
            StructField("eiaColumnTwoThreshold", BooleanType(), True),
            StructField("eiaScreeningOpinion", BooleanType(), True),
            StructField("eiaRequiresEnvironmentalStatement", BooleanType(), True),
            StructField("eiaCompletedEnvironmentalStatement", BooleanType(), True),
            StructField("hasStatutoryConsultees", BooleanType(), True),
            StructField("consultedBodiesDetails", StringType(), True),
            StructField("hasInfrastructureLevy", BooleanType(), True),
            StructField("isInfrastructureLevyFormallyAdopted", BooleanType(), True),
            StructField("infrastructureLevyAdoptedDate", StringType(), True),
            StructField("infrastructureLevyExpectedDate", StringType(), True),
            StructField("lpaProcedurePreference", StringType(), True),
            StructField("lpaProcedurePreferenceDetails", StringType(), True),
            StructField("lpaProcedurePreferenceDuration", DoubleType(), True),
            StructField("caseworkReason", StringType(), True),
            StructField("importantInformation", StringType(), True),
            StructField("jurisdiction", StringType(), True),
            StructField("redeterminedIndicator", StringType(), True),
            StructField("dateCostsReportDespatched", StringType(), True),
            StructField("dateNotRecoveredOrDerecovered", StringType(), True),
            StructField("dateRecovered", StringType(), True),
            StructField("originalCaseDecisionDate", StringType(), True),
            StructField("targetDate", StringType(), True),
            StructField("appellantCommentsSubmittedDate", StringType(), True),
            StructField("appellantStatementDueDate", StringType(), True),
            StructField("appellantStatementSubmittedDate", StringType(), True),
            StructField("appellantProofsSubmittedDate", StringType(), True),
            StructField("finalCommentsDueDate", StringType(), True),
            StructField("interestedPartyRepsDueDate", StringType(), True),
            StructField("lpaCommentsSubmittedDate", StringType(), True),
            StructField("lpaProofsSubmittedDate", StringType(), True),
            StructField("lpaStatementSubmittedDate", StringType(), True),
            StructField("proofsOfEvidenceDueDate", StringType(), True),
            StructField("siteNoticesSentDate", StringType(), True),
            StructField("statementDueDate", StringType(), True),
            StructField("caseManagementConferenceDate", StringType(), True),
            StructField("numberOfResidencesNetChange", DoubleType(), True),
            StructField("siteGridReferenceEasting", StringType(), True),
            StructField("siteGridReferenceNorthing", StringType(), True),
            StructField("siteViewableFromRoad", BooleanType(), True),
            StructField("siteWithinSSSI", BooleanType(), True),
            StructField("typeOfPlanningApplication", StringType(), True),
            StructField("developmentType", StringType(), True),
            StructField("statementOfCommonGroundDueDate", StringType(), True),
            StructField("planningObligationDueDate", StringType(), True),
            StructField("hasLandownersPermission", BooleanType(), True),
            StructField(
                "wasApplicationRefusedDueToHighwayOrTraffic", BooleanType(), True
            ),
            StructField(
                "didAppellantSubmitCompletePhotosAndPlans", BooleanType(), True
            ),
            StructField("isSiteInAreaOfSpecialControlAdverts", BooleanType(), True),
            StructField(
                "advertDetails",
                ArrayType(
                    StructType(
                        [
                            StructField("advertType", StringType(), True),
                            StructField("isAdvertInPosition", BooleanType(), True),
                            StructField("isSiteOnHighwayLand", BooleanType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("padsSapId", StringType(), True),
            StructField("enforcementNoticeReference", StringType(), True),
            StructField("descriptionOfAllegedBreach", StringType(), True),
            StructField("dateAppellantContactedPins", StringType(), True),
            StructField("ownerOccupancyStatus", StringType(), True),
            StructField("occupancyConditionsMet", BooleanType(), True),
            StructField(
                "enforcementAppealGroundsDetails",
                ArrayType(
                    StructType(
                        [
                            StructField("appealGroundLetter", StringType(), True),
                            StructField("groundForAppealStartDate", StringType(), True),
                            StructField("groundFacts", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField(
                "applicationElbAppealGroundsDetails",
                ArrayType(
                    StructType(
                        [
                            StructField("appealGroundLetter", StringType(), True),
                            StructField("groundForAppealStartDate", StringType(), True),
                            StructField("groundFacts", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("applicationMadeAndFeePaid", BooleanType(), True),
            StructField(
                "noticeRelatesToBuildingEngineeringMiningOther", BooleanType(), True
            ),
            StructField("changeOfUseRefuseOrWaste", BooleanType(), True),
            StructField("changeOfUseMineralExtraction", BooleanType(), True),
            StructField("changeOfUseMineralStorage", BooleanType(), True),
            StructField("relatesToErectionOfBuildingOrBuildings", BooleanType(), True),
            StructField(
                "relatesToBuildingWithAgriculturalPurpose", BooleanType(), True
            ),
            StructField("relatesToBuildingSingleDwellingHouse", BooleanType(), True),
            StructField("previousPlanningPermissionGranted", BooleanType(), True),
            StructField("issueDateOfEnforcementNotice", StringType(), True),
            StructField("effectiveDateOfEnforcementNotice", StringType(), True),
            StructField("didAppellantAppealLpaDecision", BooleanType(), True),
            StructField("dateLpaDecisionDue", StringType(), True),
            StructField("dateLpaDecisionReceived", StringType(), True),
            StructField("areaOfAllegedBreachInSquareMetres", DoubleType(), True),
            StructField("doesAllegedBreachCreateFloorSpace", BooleanType(), True),
            StructField("floorSpaceCreatedByBreachInSquareMetres", DoubleType(), True),
            StructField("applicationPartOrWholeDevelopment", StringType(), True),
            StructField("hasPcnBeenServed", BooleanType(), True),
            StructField("isSiteWithin67MOfTrunkRd", BooleanType(), True),
            StructField("affectedTrunkRoadName", StringType(), True),
            StructField("isSiteOnCrownLand", BooleanType(), True),
            StructField("stopNoticeExists", BooleanType(), True),
            StructField("isSiteWithin400MOfMineralInterest", BooleanType(), True),
            StructField("isSiteWithin250MOfLandfill", BooleanType(), True),
            StructField("hasDevelopmentInvolvedWasteImportation", BooleanType(), True),
            StructField("isSiteSubjectToArticle4Direction", BooleanType(), True),
            StructField("article4AffectedDevelopmentRights", StringType(), True),
            StructField("pcnRestrictedDevelopmentRights", BooleanType(), True),
            StructField("applicationMadeUnderActSection", StringType(), True),
            StructField("siteUseAtTimeOfApplication", StringType(), True),
            StructField("appealUnderActSection", StringType(), True),
            StructField("lpaConsiderAppealInvalid", BooleanType(), True),
            StructField("lpaAppealInvalidReasons", StringType(), True),
            StructField("discontinuanceNoticeServedReason", StringType(), True),
            StructField("discontinuanceNoticeServedOtherReason", StringType(), True),
            StructField("wasRetrospectivePlanningApplicationMade", BooleanType(), True),
            StructField("reasonForAppealAppellant", StringType(), True),
            StructField("screeningOpinionIndicatesEiaRequired", BooleanType(), True),
            StructField(
                "significantChangesAffectingApplicationAppellant",
                ArrayType(
                    StructType(
                        [
                            StructField("value", StringType(), True),
                            StructField("comment", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField(
                "significantChangesAffectingApplicationLpa",
                ArrayType(
                    StructType(
                        [
                            StructField("value", StringType(), True),
                            StructField("comment", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("migrated", StringType(), True),
            StructField("ODTSourceSystem", StringType(), True),
            StructField("SourceSystemID", StringType(), True),
            StructField("IngestionDate", TimestampType(), True),
            StructField("ValidTo", StringType(), True),
            StructField("RowID", StringType(), True),
            StructField("IsActive", StringType(), True),
            StructField("message_id", StringType(), True),
            StructField("listOfDocumentsBeforeDecision", StringType(), True),
        ]
    )


def _curated_row(**overrides):
    base = {
        "caseReference": "12345",
        "caseId": 123,
        "submissionId": "fkgf3gl3lgiufd3ukg3dgdlgj",
        "caseStatus": "assign_case_officer",
        "caseType": "W",
        "caseProcedure": "written",
        "lpaCode": "someCodeA",
        "caseOfficerId": None,
        "inspectorId": None,
        "allocationLevel": None,
        "allocationBand": None,
        "caseSpecialisms": None,
        "caseSubmittedDate": "2025-01-01T00:00:00.000Z",
        "caseCreatedDate": "2026-01-01T00:00:00.000Z",
        "caseUpdatedDate": "2027-01-01T00:00:00.000Z",
        "caseValidDate": None,
        "caseValidationDate": None,
        "caseValidationOutcome": None,
        "caseValidationInvalidDetails": None,
        "caseValidationIncompleteDetails": None,
        "caseExtensionDate": None,
        "caseStartedDate": None,
        "casePublishedDate": None,
        "linkedCaseStatus": None,
        "leadCaseReference": None,
        "lpaQuestionnaireDueDate": None,
        "lpaQuestionnaireSubmittedDate": None,
        "lpaQuestionnaireCreatedDate": None,
        "lpaQuestionnairePublishedDate": None,
        "lpaQuestionnaireValidationOutcome": None,
        "lpaQuestionnaireValidationOutcomeDate": None,
        "lpaQuestionnaireValidationDetails": None,
        "lpaStatement": None,
        "caseWithdrawnDate": None,
        "caseTransferredDate": None,
        "transferredCaseClosedDate": None,
        "caseDecisionOutcomeDate": None,
        "caseDecisionPublishedDate": None,
        "caseDecisionOutcome": None,
        "caseCompletedDate": None,
        "enforcementNotice": None,
        "applicationReference": "123",
        "applicationDate": "2028-01-01T00:00:00.000Z",
        "applicationDecision": "refused",
        "applicationDecisionDate": "2029-01-01T00:00:00.000Z",
        "caseSubmissionDueDate": "2030-01-01T00:00:00.000Z",
        "siteAddressLine1": "e2e Test Address",
        "siteAddressLine2": "Somewhere St",
        "siteAddressTown": "Somewhereville",
        "siteAddressCounty": "Somewhere",
        "siteAddressPostcode": "BS21 6LE",
        "siteAccessDetails": ["Come and see", ""],
        "siteSafetyDetails": ["It's dangerous", ""],
        "siteAreaSquareMetres": 22.0,
        "floorSpaceSquareMetres": 22.0,
        "isCorrectAppealType": None,
        "isGreenBelt": False,
        "inConservationArea": None,
        "ownsAllLand": True,
        "ownsSomeLand": True,
        "knowsOtherOwners": "Some",
        "knowsAllOwners": "Some",
        "advertisedAppeal": True,
        "notificationMethod": None,
        "ownersInformed": True,
        "originalDevelopmentDescription": "A test description",
        "changedDevelopmentDescription": False,
        "newConditionDetails": None,
        "nearbyCaseReferences": [],
        "neighbouringSiteAddresses": None,
        "affectedListedBuildingNumbers": None,
        "changedListedBuildingNumbers": None,
        "appellantCostsAppliedFor": False,
        "lpaCostsAppliedFor": None,
        "agriculturalHolding": True,
        "tenantAgriculturalHolding": True,
        "otherTenantsAgriculturalHolding": None,
        "informedTenantsAgriculturalHolding": None,
        "appellantProcedurePreference": None,
        "appellantProcedurePreferenceDetails": "eiusmod ex exercitation",
        "appellantProcedurePreferenceDuration": 1.0,
        "appellantProcedurePreferenceWitnessCount": 5.0,
        "statusPlanningObligation": "proident aute",
        "affectsScheduledMonument": None,
        "hasProtectedSpecies": None,
        "isAonbNationalLandscape": None,
        "designatedSitesNames": [],
        "isGypsyOrTravellerSite": None,
        "isPublicRightOfWay": None,
        "eiaEnvironmentalImpactSchedule": None,
        "eiaDevelopmentDescription": None,
        "eiaSensitiveAreaDetails": None,
        "eiaColumnTwoThreshold": None,
        "eiaScreeningOpinion": None,
        "eiaRequiresEnvironmentalStatement": None,
        "eiaCompletedEnvironmentalStatement": None,
        "hasStatutoryConsultees": None,
        "consultedBodiesDetails": None,
        "hasInfrastructureLevy": None,
        "isInfrastructureLevyFormallyAdopted": None,
        "infrastructureLevyAdoptedDate": None,
        "infrastructureLevyExpectedDate": None,
        "lpaProcedurePreference": None,
        "lpaProcedurePreferenceDetails": None,
        "lpaProcedurePreferenceDuration": None,
        "caseworkReason": None,
        "developmentType": "minor-dwellings",
        "importantInformation": None,
        "jurisdiction": None,
        "redeterminedIndicator": None,
        "dateCostsReportDespatched": None,
        "dateNotRecoveredOrDerecovered": None,
        "dateRecovered": None,
        "originalCaseDecisionDate": None,
        "targetDate": None,
        "appellantCommentsSubmittedDate": None,
        "appellantStatementSubmittedDate": None,
        "appellantProofsSubmittedDate": None,
        "finalCommentsDueDate": None,
        "interestedPartyRepsDueDate": None,
        "lpaCommentsSubmittedDate": None,
        "lpaProofsSubmittedDate": None,
        "lpaStatementSubmittedDate": None,
        "proofsOfEvidenceDueDate": None,
        "siteNoticesSentDate": None,
        "statementDueDate": None,
        "reasonForNeighbourVisits": None,
        "numberOfResidencesNetChange": None,
        "siteGridReferenceEasting": None,
        "siteGridReferenceNorthing": None,
        "siteViewableFromRoad": None,
        "siteWithinSSSI": None,
        "typeOfPlanningApplication": "full-appeal",
        "preserveGrantLoan": None,
        "consultHistoricEngland": None,
        "planningObligationDueDate": None,
        "hasLandownersPermission": None,
        "wasApplicationRefusedDueToHighwayOrTraffic": None,
        "didAppellantSubmitCompletePhotosAndPlans": None,
        "isSiteInAreaOfSpecialControlAdverts": None,
        "advertDetails": None,
        "padsSapId": None,
        "statementOfCommonGroundDueDate": None,
        "issueDateOfEnforcementNotice": None,
        "effectiveDateOfEnforcementNotice": None,
        "enforcementAppealGroundsDetails": None,
        "ownerOccupancyStatus": None,
        "occupancyConditionsMet": None,
        "applicationMadeAndFeePaid": None,
        "noticeRelatesToBuildingEngineeringMiningOther": None,
        "changeOfUseRefuseOrWaste": None,
        "changeOfUseMineralExtraction": None,
        "changeOfUseMineralStorage": None,
        "relatesToErectionOfBuildingOrBuildings": None,
        "relatesToBuildingWithAgriculturalPurpose": None,
        "relatesToBuildingSingleDwellingHouse": None,
        "previousPlanningPermissionGranted": None,
        "didAppellantAppealLpaDecision": None,
        "dateLpaDecisionDue": None,
        "dateLpaDecisionReceived": None,
        "areaOfAllegedBreachInSquareMetres": None,
        "doesAllegedBreachCreateFloorSpace": None,
        "floorSpaceCreatedByBreachInSquareMetres": None,
        "applicationPartOrWholeDevelopment": None,
        "hasPcnBeenServed": None,
        "isSiteWithin67MOfTrunkRd": None,
        "affectedTrunkRoadName": None,
        "isSiteOnCrownLand": None,
        "stopNoticeExists": None,
        "isSiteWithin400MOfMineralInterest": None,
        "isSiteWithin250MOfLandfill": None,
        "hasDevelopmentInvolvedWasteImportation": None,
        "isSiteSubjectToArticle4Direction": None,
        "article4AffectedDevelopmentRights": None,
        "pcnRestrictedDevelopmentRights": None,
        "enforcementNoticeReference": None,
        "descriptionOfAllegedBreach": None,
        "dateAppellantContactedPins": None,
        "applicationMadeUnderActSection": None,
        "siteUseAtTimeOfApplication": None,
        "appealUnderActSection": None,
        "lpaConsiderAppealInvalid": None,
        "lpaAppealInvalidReasons": None,
        "applicationElbAppealGroundsDetails": None,
        "extraConditionsDetails": None,
        "reasonForAppealAppellant": None,
        "significantChangesAffectingApplicationAppellant": None,
        "screeningOpinionIndicatesEiaRequired": None,
        "significantChangesAffectingApplicationLpa": None,
        "listOfDocumentsBeforeDecision": None,
    }
    return base | overrides


def _curated_schema():
    return StructType(
        [
            StructField("caseReference", StringType(), True),
            StructField("caseId", LongType(), True),
            StructField("submissionId", StringType(), True),
            StructField("caseStatus", StringType(), True),
            StructField("caseType", StringType(), True),
            StructField("caseProcedure", StringType(), True),
            StructField("lpaCode", StringType(), True),
            StructField("caseOfficerId", StringType(), True),
            StructField("inspectorId", StringType(), True),
            StructField("allocationLevel", StringType(), True),
            StructField("allocationBand", DoubleType(), True),
            StructField("caseSpecialisms", ArrayType(StringType(), True), True),
            StructField("caseSubmittedDate", StringType(), True),
            StructField("caseCreatedDate", StringType(), True),
            StructField("caseUpdatedDate", StringType(), True),
            StructField("caseValidDate", StringType(), True),
            StructField("caseValidationDate", StringType(), True),
            StructField("caseValidationOutcome", StringType(), True),
            StructField(
                "caseValidationInvalidDetails", ArrayType(StringType(), True), True
            ),
            StructField(
                "caseValidationIncompleteDetails", ArrayType(StringType(), True), True
            ),
            StructField("caseExtensionDate", StringType(), True),
            StructField("caseStartedDate", StringType(), True),
            StructField("casePublishedDate", StringType(), True),
            StructField("linkedCaseStatus", StringType(), True),
            StructField("leadCaseReference", StringType(), True),
            StructField("lpaQuestionnaireDueDate", StringType(), True),
            StructField("lpaQuestionnaireSubmittedDate", StringType(), True),
            StructField("lpaQuestionnaireCreatedDate", StringType(), True),
            StructField("lpaQuestionnairePublishedDate", StringType(), True),
            StructField("lpaQuestionnaireValidationOutcome", StringType(), True),
            StructField("lpaQuestionnaireValidationOutcomeDate", StringType(), True),
            StructField(
                "lpaQuestionnaireValidationDetails", ArrayType(StringType(), True), True
            ),
            StructField("lpaStatement", StringType(), True),
            StructField("caseWithdrawnDate", StringType(), True),
            StructField("caseTransferredDate", StringType(), True),
            StructField("transferredCaseClosedDate", StringType(), True),
            StructField("caseDecisionOutcomeDate", StringType(), True),
            StructField("caseDecisionPublishedDate", StringType(), True),
            StructField("caseDecisionOutcome", StringType(), True),
            StructField("caseCompletedDate", StringType(), True),
            StructField("enforcementNotice", BooleanType(), True),
            StructField("applicationReference", StringType(), True),
            StructField("applicationDate", StringType(), True),
            StructField("applicationDecision", StringType(), True),
            StructField("applicationDecisionDate", StringType(), True),
            StructField("caseSubmissionDueDate", StringType(), True),
            StructField("siteAddressLine1", StringType(), True),
            StructField("siteAddressLine2", StringType(), True),
            StructField("siteAddressTown", StringType(), True),
            StructField("siteAddressCounty", StringType(), True),
            StructField("siteAddressPostcode", StringType(), True),
            StructField("siteAccessDetails", ArrayType(StringType(), True), True),
            StructField("siteSafetyDetails", ArrayType(StringType(), True), True),
            StructField("siteAreaSquareMetres", DoubleType(), True),
            StructField("floorSpaceSquareMetres", DoubleType(), True),
            StructField("isCorrectAppealType", BooleanType(), True),
            StructField("isGreenBelt", BooleanType(), True),
            StructField("inConservationArea", BooleanType(), True),
            StructField("ownsAllLand", BooleanType(), True),
            StructField("ownsSomeLand", BooleanType(), True),
            StructField("knowsOtherOwners", StringType(), True),
            StructField("knowsAllOwners", StringType(), True),
            StructField("advertisedAppeal", BooleanType(), True),
            StructField("notificationMethod", ArrayType(StringType(), True), True),
            StructField("ownersInformed", BooleanType(), True),
            StructField("originalDevelopmentDescription", StringType(), True),
            StructField("changedDevelopmentDescription", BooleanType(), True),
            StructField("newConditionDetails", StringType(), True),
            StructField("nearbyCaseReferences", ArrayType(StringType(), True), True),
            StructField(
                "neighbouringSiteAddresses",
                ArrayType(
                    StructType(
                        [
                            StructField(
                                "neighbouringSiteAddressLine1", StringType(), True
                            ),
                            StructField(
                                "neighbouringSiteAddressLine2", StringType(), True
                            ),
                            StructField(
                                "neighbouringSiteAddressTown", StringType(), True
                            ),
                            StructField(
                                "neighbouringSiteAddressCounty", StringType(), True
                            ),
                            StructField(
                                "neighbouringSiteAddressPostcode", StringType(), True
                            ),
                            StructField(
                                "neighbouringSiteAccessDetails", StringType(), True
                            ),
                            StructField(
                                "neighbouringSiteSafetyDetails", StringType(), True
                            ),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField(
                "affectedListedBuildingNumbers", ArrayType(StringType(), True), True
            ),
            StructField(
                "changedListedBuildingNumbers", ArrayType(StringType(), True), True
            ),
            StructField("appellantCostsAppliedFor", BooleanType(), True),
            StructField("lpaCostsAppliedFor", BooleanType(), True),
            StructField("agriculturalHolding", BooleanType(), True),
            StructField("tenantAgriculturalHolding", BooleanType(), True),
            StructField("otherTenantsAgriculturalHolding", BooleanType(), True),
            StructField("informedTenantsAgriculturalHolding", BooleanType(), True),
            StructField("appellantProcedurePreference", StringType(), True),
            StructField("appellantProcedurePreferenceDetails", StringType(), True),
            StructField("appellantProcedurePreferenceDuration", DoubleType(), True),
            StructField("appellantProcedurePreferenceWitnessCount", DoubleType(), True),
            StructField("statusPlanningObligation", StringType(), True),
            StructField("affectsScheduledMonument", BooleanType(), True),
            StructField("hasProtectedSpecies", BooleanType(), True),
            StructField("isAonbNationalLandscape", BooleanType(), True),
            StructField("designatedSitesNames", ArrayType(StringType(), True), True),
            StructField("isGypsyOrTravellerSite", BooleanType(), True),
            StructField("isPublicRightOfWay", BooleanType(), True),
            StructField("eiaEnvironmentalImpactSchedule", StringType(), True),
            StructField("eiaDevelopmentDescription", StringType(), True),
            StructField("eiaSensitiveAreaDetails", StringType(), True),
            StructField("eiaColumnTwoThreshold", BooleanType(), True),
            StructField("eiaScreeningOpinion", BooleanType(), True),
            StructField("eiaRequiresEnvironmentalStatement", BooleanType(), True),
            StructField("eiaCompletedEnvironmentalStatement", BooleanType(), True),
            StructField("hasStatutoryConsultees", BooleanType(), True),
            StructField("consultedBodiesDetails", StringType(), True),
            StructField("hasInfrastructureLevy", BooleanType(), True),
            StructField("isInfrastructureLevyFormallyAdopted", BooleanType(), True),
            StructField("infrastructureLevyAdoptedDate", StringType(), True),
            StructField("infrastructureLevyExpectedDate", StringType(), True),
            StructField("lpaProcedurePreference", StringType(), True),
            StructField("lpaProcedurePreferenceDetails", StringType(), True),
            StructField("lpaProcedurePreferenceDuration", DoubleType(), True),
            StructField("caseworkReason", StringType(), True),
            StructField("developmentType", StringType(), True),
            StructField("importantInformation", StringType(), True),
            StructField("jurisdiction", StringType(), True),
            StructField("redeterminedIndicator", StringType(), True),
            StructField("dateCostsReportDespatched", StringType(), True),
            StructField("dateNotRecoveredOrDerecovered", StringType(), True),
            StructField("dateRecovered", StringType(), True),
            StructField("originalCaseDecisionDate", StringType(), True),
            StructField("targetDate", StringType(), True),
            StructField("appellantCommentsSubmittedDate", StringType(), True),
            StructField("appellantStatementSubmittedDate", StringType(), True),
            StructField("appellantProofsSubmittedDate", StringType(), True),
            StructField("finalCommentsDueDate", StringType(), True),
            StructField("interestedPartyRepsDueDate", StringType(), True),
            StructField("lpaCommentsSubmittedDate", StringType(), True),
            StructField("lpaProofsSubmittedDate", StringType(), True),
            StructField("lpaStatementSubmittedDate", StringType(), True),
            StructField("proofsOfEvidenceDueDate", StringType(), True),
            StructField("siteNoticesSentDate", StringType(), True),
            StructField("statementDueDate", StringType(), True),
            StructField("reasonForNeighbourVisits", StringType(), True),
            StructField("numberOfResidencesNetChange", DoubleType(), True),
            StructField("siteGridReferenceEasting", StringType(), True),
            StructField("siteGridReferenceNorthing", StringType(), True),
            StructField("siteViewableFromRoad", BooleanType(), True),
            StructField("siteWithinSSSI", BooleanType(), True),
            StructField("typeOfPlanningApplication", StringType(), True),
            StructField("preserveGrantLoan", BooleanType(), True),
            StructField("consultHistoricEngland", BooleanType(), True),
            StructField("planningObligationDueDate", StringType(), True),
            StructField("hasLandownersPermission", BooleanType(), True),
            StructField(
                "wasApplicationRefusedDueToHighwayOrTraffic", BooleanType(), True
            ),
            StructField(
                "didAppellantSubmitCompletePhotosAndPlans", BooleanType(), True
            ),
            StructField("isSiteInAreaOfSpecialControlAdverts", BooleanType(), True),
            StructField(
                "advertDetails",
                ArrayType(
                    StructType(
                        [
                            StructField("advertType", StringType(), True),
                            StructField("isAdvertInPosition", BooleanType(), True),
                            StructField("isSiteOnHighwayLand", BooleanType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("padsSapId", StringType(), True),
            StructField("statementOfCommonGroundDueDate", StringType(), True),
            StructField("issueDateOfEnforcementNotice", StringType(), True),
            StructField("effectiveDateOfEnforcementNotice", StringType(), True),
            StructField(
                "enforcementAppealGroundsDetails",
                ArrayType(
                    StructType(
                        [
                            StructField("appealGroundLetter", StringType(), True),
                            StructField("groundForAppealStartDate", StringType(), True),
                            StructField("groundFacts", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("ownerOccupancyStatus", StringType(), True),
            StructField("occupancyConditionsMet", BooleanType(), True),
            StructField("applicationMadeAndFeePaid", BooleanType(), True),
            StructField(
                "noticeRelatesToBuildingEngineeringMiningOther", BooleanType(), True
            ),
            StructField("changeOfUseRefuseOrWaste", BooleanType(), True),
            StructField("changeOfUseMineralExtraction", BooleanType(), True),
            StructField("changeOfUseMineralStorage", BooleanType(), True),
            StructField("relatesToErectionOfBuildingOrBuildings", BooleanType(), True),
            StructField(
                "relatesToBuildingWithAgriculturalPurpose", BooleanType(), True
            ),
            StructField("relatesToBuildingSingleDwellingHouse", BooleanType(), True),
            StructField("previousPlanningPermissionGranted", BooleanType(), True),
            StructField("didAppellantAppealLpaDecision", BooleanType(), True),
            StructField("dateLpaDecisionDue", StringType(), True),
            StructField("dateLpaDecisionReceived", StringType(), True),
            StructField("areaOfAllegedBreachInSquareMetres", DoubleType(), True),
            StructField("doesAllegedBreachCreateFloorSpace", BooleanType(), True),
            StructField("floorSpaceCreatedByBreachInSquareMetres", DoubleType(), True),
            StructField("applicationPartOrWholeDevelopment", StringType(), True),
            StructField("hasPcnBeenServed", BooleanType(), True),
            StructField("isSiteWithin67MOfTrunkRd", BooleanType(), True),
            StructField("affectedTrunkRoadName", StringType(), True),
            StructField("isSiteOnCrownLand", BooleanType(), True),
            StructField("stopNoticeExists", BooleanType(), True),
            StructField("isSiteWithin400MOfMineralInterest", BooleanType(), True),
            StructField("isSiteWithin250MOfLandfill", BooleanType(), True),
            StructField("hasDevelopmentInvolvedWasteImportation", BooleanType(), True),
            StructField("isSiteSubjectToArticle4Direction", BooleanType(), True),
            StructField("article4AffectedDevelopmentRights", StringType(), True),
            StructField("pcnRestrictedDevelopmentRights", BooleanType(), True),
            StructField("enforcementNoticeReference", StringType(), True),
            StructField("descriptionOfAllegedBreach", StringType(), True),
            StructField("dateAppellantContactedPins", StringType(), True),
            StructField("applicationMadeUnderActSection", StringType(), True),
            StructField("siteUseAtTimeOfApplication", StringType(), True),
            StructField("appealUnderActSection", StringType(), True),
            StructField("lpaConsiderAppealInvalid", BooleanType(), True),
            StructField("lpaAppealInvalidReasons", StringType(), True),
            StructField(
                "applicationElbAppealGroundsDetails",
                ArrayType(
                    StructType(
                        [
                            StructField("appealGroundLetter", StringType(), True),
                            StructField("groundForAppealStartDate", StringType(), True),
                            StructField("groundFacts", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("extraConditionsDetails", StringType(), True),
            StructField("reasonForAppealAppellant", StringType(), True),
            StructField(
                "significantChangesAffectingApplicationAppellant",
                ArrayType(
                    StructType(
                        [
                            StructField("value", StringType(), True),
                            StructField("comment", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("screeningOpinionIndicatesEiaRequired", BooleanType(), True),
            StructField(
                "significantChangesAffectingApplicationLpa",
                ArrayType(
                    StructType(
                        [
                            StructField("value", StringType(), True),
                            StructField("comment", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("listOfDocumentsBeforeDecision", StringType(), True),
        ]
    )


class TestAppealS78CurationProcess(ETLTestCase):
    def assert_curation_successful(self, test_case: str):
        spark = PytestSparkSessionUtil().get_spark_session()
        harmonised_data = spark.createDataFrame(
            (_harmonised_row(),), schema=_harmonised_schema()
        )
        harmonised_table = f"{test_case}_appeal_s78"
        self.write_existing_table(
            spark,
            harmonised_data,
            harmonised_table,
            "odw_harmonised_db",
            "odw-harmonised",
            harmonised_table,
            "overwrite",
        )
        expected_curated_data = spark.createDataFrame(
            (_curated_row(),), schema=_curated_schema()
        )
        curated_table = f"{test_case}_appeal_s78"
        with (
            mock.patch.object(
                AppealS78CurationProcess, "HARMONISED_TABLE", harmonised_table
            ),
            mock.patch.object(AppealS78CurationProcess, "OUTPUT_TABLE", curated_table),
            mock.patch.object(AppealS78CurationProcess, "__init__", return_value=None),
        ):
            inst = AppealS78CurationProcess()
            result = inst.run()
            assert_etl_result_successful(result)
            actual_curated_data = spark.table(f"odw_curated_db.{curated_table}")
            assert_dataframes_equal(expected_curated_data, actual_curated_data)

    def test__appeal_s78_curation_process__run__with_no_existing_data(self):
        """
        - Given I have some harmonised s78 data
        - When I call AppealS78CurationProcess.run
        - Then the curated s78 table should be created
        """
        self.assert_curation_successful("t_as78cp_r_wned")

    def test__appeal_s78_curation_process__run__with_existing_data(self):
        """
        - Given I have some harmonised s78 data and an existing curated s78 table
        - When I call AppealS78CurationProcess.run
        - Then the curated s78 table should be created which overwrites the old curated table
        """
        test_case = "t_as78cp_r_wed"
        spark = PytestSparkSessionUtil().get_spark_session()
        existing_curated_data = spark.createDataFrame(
            (_curated_row(caseReference="99999"),), schema=_curated_schema()
        )
        curated_table = f"{test_case}_appeal_s78"
        self.write_existing_table(
            spark,
            existing_curated_data,
            curated_table,
            "odw_curated_db",
            "odw-curated",
            curated_table,
            "overwrite",
            format="parquet",
        )
        self.assert_curation_successful(test_case)
