import pytest
import odw.test.util.mock_util.import_mock_notebook_utils  # noqa: F401
from odw.core.etl.transformation.curated.appeal_s78_mipins_curation_process import (
    AppealS78MIPINSCurationProcess,
)
from odw.test.integration_test.etl.etl_test_case import ETLTestCase
from odw.test.util.session_util import PytestSparkSessionUtil
from odw.test.util.assertion import (
    assert_dataframes_equal,
    assert_etl_result_successful,
)
from pyspark.sql.types import (
    StructType,
    StructField,
    StringType,
    IntegerType,
    LongType,
    BooleanType,
    TimestampType,
    DecimalType,
    DoubleType,
    ArrayType,
)
from datetime import datetime
from decimal import Decimal
import mock


pytestmark = pytest.mark.skip(reason="Curated logic not implemented yet")


def generate_appeal_s78_row(**overrides):
    # todo need to convert dates to string
    base = {
        "caseReference": "6000001",
        "AppealS78ID": 0,
        "caseId": 0,
        "submissionId": "submissionIdValue",
        "caseStatus": "caseStatusValue",
        "caseType": "caseTypeValue",
        "caseProcedure": "caseProcedureValue",
        "lpaCode": "lpaCodeValue",
        "caseOfficerId": "caseOfficerIdValue",
        "inspectorId": "inspectorIdValue",
        "allocationLevel": "allocationLevelValue",
        "allocationBand": 0.0,
        "caseSpecialisms": [],
        "caseSubmittedDate": "2025-01-01T00:00:00.000Z",
        "caseCreatedDate": "2025-01-02T00:00:00.000Z",
        "caseUpdatedDate": "2025-01-03T00:00:00.000Z",
        "caseValidDate": "2025-01-04T00:00:00.000Z",
        "caseValidationDate": "2025-01-05T00:00:00.000Z",
        "caseValidationOutcome": "caseValidationOutcomeValue",
        "caseValidationInvalidDetails": [],
        "caseValidationIncompleteDetails": [
            "caseValidationIncompleteDetailsA",
            "caseValidationIncompleteDetailsB",
        ],
        "caseExtensionDate": "2025-01-06T00:00:00.000Z",
        "caseStartedDate": "2025-01-07T00:00:00.000Z",
        "casePublishedDate": "2025-01-08T00:00:00.000Z",
        "linkedCaseStatus": "linkedCaseStatusValue",
        "leadCaseReference": "leadCaseReferenceValue",
        "lpaQuestionnaireDueDate": "2025-01-09T00:00:00.000Z",
        "lpaQuestionnaireSubmittedDate": "2025-01-10T00:00:00.000Z",
        "lpaQuestionnaireCreatedDate": "2025-01-11T00:00:00.000Z",
        "lpaQuestionnairePublishedDate": "2025-01-12T00:00:00.000Z",
        "lpaQuestionnaireValidationOutcome": "lpaQuestionnaireValidationOutcomeValue",
        "lpaQuestionnaireValidationOutcomeDate": "2025-01-13T00:00:00.000Z",
        "lpaQuestionnaireValidationDetails": [
            "lpaQuestionnaireValidationDetailsA",
            "lpaQuestionnaireValidationDetailsB",
        ],
        "lpaStatement": "lpaStatementValue",
        "caseWithdrawnDate": "2025-01-14T00:00:00.000Z",
        "caseTransferredDate": "2025-01-15T00:00:00.000Z",
        "transferredCaseClosedDate": "2025-01-16T00:00:00.000Z",
        "caseDecisionOutcomeDate": "2025-01-17T00:00:00.000Z",
        "caseDecisionPublishedDate": "2025-01-18T00:00:00.000Z",
        "caseDecisionOutcome": "caseDecisionOutcomeValue",
        "caseCompletedDate": "2025-01-19T00:00:00.000Z",
        "enforcementNotice": True,
        "applicationReference": "applicationReferenceValue",
        "applicationDate": "2025-01-20T00:00:00.000Z",
        "applicationDecision": "applicationDecisionValue",
        "applicationDecisionDate": "2025-01-21T00:00:00.000Z",
        "applicationDecisionDueDate": "applicationDecisionDueDateValue",
        "caseSubmissionDueDate": "2025-01-22T00:00:00.000Z",
        "siteAddressLine1": "siteAddressLine1Value",
        "siteAddressLine2": "siteAddressLine2Value",
        "siteAddressTown": "siteAddressTownValue",
        "siteAddressCounty": "siteAddressCountyValue",
        "siteAddressPostcode": "siteAddressPostcodeValue",
        "siteAccessDetails": ["siteAccessDetailsA", "siteAccessDetailsB"],
        "siteSafetyDetails": ["siteSafetyDetailsA", "siteSafetyDetailsB"],
        "siteAreaSquareMetres": 0.0,
        "floorSpaceSquareMetres": 0.0,
        "isCorrectAppealType": True,
        "isGreenBelt": True,
        "inConservationArea": True,
        "ownsAllLand": True,
        "ownsSomeLand": True,
        "knowsOtherOwners": "knowsOtherOwnersValue",
        "knowsAllOwners": "knowsAllOwnersValue",
        "advertisedAppeal": True,
        "notificationMethod": ["notificationMethodA", "notificationMethodB"],
        "ownersInformed": True,
        "originalDevelopmentDescription": "originalDevelopmentDescriptionValue",
        "changedDevelopmentDescription": True,
        "newConditionDetails": "newConditionDetailsValue",
        "extraConditionsDetails": "extraConditionsDetailsValue",
        "nearbyCaseReferences": ["nearbyCaseReferencesA", "nearbyCaseReferencesB"],
        "neighbouringSiteAddresses": [
            {
                "neighbouringSiteAddressLine1": "neighbouringSiteAddressLine1A",
                "neighbouringSiteAddressLine2": "neighbouringSiteAddressLine2A",
                "neighbouringSiteAddressTown": "neighbouringSiteAddressTownA",
                "neighbouringSiteAddressCounty": "neighbouringSiteAddressCountyA",
                "neighbouringSiteAddressPostcode": "neighbouringSiteAddressPostcodeA",
                "neighbouringSiteAccessDetails": "neighbouringSiteAccessDetailsA",
                "neighbouringSiteSafetyDetails": "neighbouringSiteSafetyDetailsA",
            },
            {
                "neighbouringSiteAddressLine1": "neighbouringSiteAddressLine1B",
                "neighbouringSiteAddressLine2": "neighbouringSiteAddressLine2B",
                "neighbouringSiteAddressTown": "neighbouringSiteAddressTownB",
                "neighbouringSiteAddressCounty": "neighbouringSiteAddressCountyB",
                "neighbouringSiteAddressPostcode": "neighbouringSiteAddressPostcodeB",
                "neighbouringSiteAccessDetails": "neighbouringSiteAccessDetailsB",
                "neighbouringSiteSafetyDetails": "neighbouringSiteSafetyDetailsB",
            },
        ],
        "reasonForNeighbourVisits": "reasonForNeighbourVisitsValue",
        "affectedListedBuildingNumbers": [
            "affectedListedBuildingNumbersA",
            "affectedListedBuildingNumbersB",
        ],
        "changedListedBuildingNumbers": [
            "changedListedBuildingNumbersA",
            "changedListedBuildingNumbersB",
        ],
        "preserveGrantLoan": True,
        "consultHistoricEngland": True,
        "appellantCostsAppliedFor": True,
        "lpaCostsAppliedFor": True,
        "agriculturalHolding": True,
        "tenantAgriculturalHolding": True,
        "otherTenantsAgriculturalHolding": True,
        "informedTenantsAgriculturalHolding": True,
        "appellantProcedurePreference": "appellantProcedurePreferenceValue",
        "appellantProcedurePreferenceDetails": "appellantProcedurePreferenceDetailsValue",
        "appellantProcedurePreferenceDuration": 0.0,
        "appellantProcedurePreferenceWitnessCount": 0.0,
        "statusPlanningObligation": "statusPlanningObligationValue",
        "affectsScheduledMonument": True,
        "hasProtectedSpecies": True,
        "isAonbNationalLandscape": True,
        "designatedSitesNames": ["designatedSitesNamesA", "designatedSitesNamesB"],
        "isGypsyOrTravellerSite": True,
        "isPublicRightOfWay": True,
        "eiaEnvironmentalImpactSchedule": "eiaEnvironmentalImpactScheduleValue",
        "eiaDevelopmentDescription": "eiaDevelopmentDescriptionValue",
        "eiaSensitiveAreaDetails": "eiaSensitiveAreaDetailsValue",
        "eiaColumnTwoThreshold": True,
        "eiaScreeningOpinion": True,
        "eiaRequiresEnvironmentalStatement": True,
        "eiaCompletedEnvironmentalStatement": True,
        "hasStatutoryConsultees": True,
        "consultedBodiesDetails": "consultedBodiesDetailsValue",
        "hasInfrastructureLevy": True,
        "isInfrastructureLevyFormallyAdopted": True,
        "infrastructureLevyAdoptedDate": "2025-01-23T00:00:00.000Z",
        "infrastructureLevyExpectedDate": "2025-01-24T00:00:00.000Z",
        "lpaProcedurePreference": "lpaProcedurePreferenceValue",
        "lpaProcedurePreferenceDetails": "lpaProcedurePreferenceDetailsValue",
        "lpaProcedurePreferenceDuration": 0.0,
        "caseworkReason": "caseworkReasonValue",
        "importantInformation": "importantInformationValue",
        "jurisdiction": "jurisdictionValue",
        "redeterminedIndicator": "redeterminedIndicatorValue",
        "dateCostsReportDespatched": "2025-01-01T00:00:00.000Z",
        "dateNotRecoveredOrDerecovered": "2025-01-01T00:00:00.000Z",
        "dateRecovered": "2025-01-01T00:00:00.000Z",
        "originalCaseDecisionDate": "2025-01-01T00:00:00.000Z",
        "targetDate": "targetDateValue",
        "appellantCommentsSubmittedDate": "2025-01-01T00:00:00.000Z",
        "appellantStatementDueDate": "2025-01-01T00:00:00.000Z",
        "appellantStatementSubmittedDate": "2025-01-01T00:00:00.000Z",
        "appellantProofsSubmittedDate": "2025-01-01T00:00:00.000Z",
        "finalCommentsDueDate": "2025-01-25T00:00:00.000Z",
        "interestedPartyRepsDueDate": "2025-01-26T00:00:00.000Z",
        "lpaCommentsSubmittedDate": "2025-01-01T00:00:00.000Z",
        "lpaProofsSubmittedDate": "2025-01-01T00:00:00.000Z",
        "lpaStatementSubmittedDate": "2025-01-01T00:00:00.000Z",
        "proofsOfEvidenceDueDate": "2025-01-01T00:00:00.000Z",
        "siteNoticesSentDate": "2025-01-01T00:00:00.000Z",
        "statementDueDate": "2025-01-27T00:00:00.000Z",
        "caseManagementConferenceDate": "caseManagementConferenceDateValue",
        "numberOfResidencesNetChange": 0.0,
        "siteGridReferenceEasting": "siteGridReferenceEastingValue",
        "siteGridReferenceNorthing": "siteGridReferenceNorthingValue",
        "siteViewableFromRoad": True,
        "siteWithinSSSI": True,
        "typeOfPlanningApplication": "typeOfPlanningApplicationValue",
        "developmentType": "developmentTypeValue",
        "statementOfCommonGroundDueDate": None,
        "planningObligationDueDate": None,
        "hasLandownersPermission": True,
        "wasApplicationRefusedDueToHighwayOrTraffic": True,
        "didAppellantSubmitCompletePhotosAndPlans": True,
        "isSiteInAreaOfSpecialControlAdverts": True,
        "advertDetails": [],
        "padsSapId": "padsSapIdValue",
        "enforcementNoticeReference": "enforcementNoticeReferenceValue",
        "descriptionOfAllegedBreach": "descriptionOfAllegedBreachValue",
        "dateAppellantContactedPins": None,
        "ownerOccupancyStatus": "ownerOccupancyStatusValue",
        "occupancyConditionsMet": True,
        "enforcementAppealGroundsDetails": [],
        "applicationElbAppealGroundsDetails": [],
        "applicationMadeAndFeePaid": True,
        "noticeRelatesToBuildingEngineeringMiningOther": True,
        "changeOfUseRefuseOrWaste": True,
        "changeOfUseMineralExtraction": True,
        "changeOfUseMineralStorage": True,
        "relatesToErectionOfBuildingOrBuildings": True,
        "relatesToBuildingWithAgriculturalPurpose": True,
        "relatesToBuildingSingleDwellingHouse": True,
        "previousPlanningPermissionGranted": True,
        "issueDateOfEnforcementNotice": None,
        "effectiveDateOfEnforcementNotice": None,
        "didAppellantAppealLpaDecision": True,
        "dateLpaDecisionDue": None,
        "dateLpaDecisionReceived": None,
        "areaOfAllegedBreachInSquareMetres": 0.0,
        "doesAllegedBreachCreateFloorSpace": True,
        "floorSpaceCreatedByBreachInSquareMetres": 0.0,
        "applicationPartOrWholeDevelopment": "applicationPartOrWholeDevelopmentValue",
        "hasPcnBeenServed": True,
        "isSiteWithin67MOfTrunkRd": True,
        "affectedTrunkRoadName": "affectedTrunkRoadNameValue",
        "isSiteOnCrownLand": True,
        "stopNoticeExists": True,
        "isSiteWithin400MOfMineralInterest": True,
        "isSiteWithin250MOfLandfill": True,
        "hasDevelopmentInvolvedWasteImportation": True,
        "isSiteSubjectToArticle4Direction": True,
        "article4AffectedDevelopmentRights": "article4AffectedDevelopmentRightsValue",
        "pcnRestrictedDevelopmentRights": True,
        "applicationMadeUnderActSection": "applicationMadeUnderActSectionValue",
        "siteUseAtTimeOfApplication": "siteUseAtTimeOfApplicationValue",
        "appealUnderActSection": "appealUnderActSectionValue",
        "lpaConsiderAppealInvalid": True,
        "lpaAppealInvalidReasons": "lpaAppealInvalidReasonsValue",
        "discontinuanceNoticeServedReason": "discontinuanceNoticeServedReasonValue",
        "discontinuanceNoticeServedOtherReason": "discontinuanceNoticeServedOtherReasonValue",
        "wasRetrospectivePlanningApplicationMade": True,
        "reasonForAppealAppellant": "reasonForAppealAppellantValue",
        "screeningOpinionIndicatesEiaRequired": True,
        "significantChangesAffectingApplicationAppellant": [],
        "significantChangesAffectingApplicationLpa": [],
        "migrated": "migratedValue",
        "ODTSourceSystem": "ODT",
        "SourceSystemID": "SourceSystemIDValue",
        "IngestionDate": datetime(2025, 1, 28),
        "ValidTo": "2025-01-29T00:00:00.000Z",
        "RowID": "RowIDValue",
        "IsActive": "IsActiveValue",
        "message_id": "message_idValue",
        "listOfDocumentsBeforeDecision": "listOfDocumentsBeforeDecisionValue",
    }
    combined = base | overrides
    return combined


def generate_appeal_s78_schema():
    return StructType(
        [
            StructField("caseReference", StringType(), True),
            StructField("AppealS78ID", LongType(), True),
            StructField("caseId", LongType(), True),
            StructField("submissionId", StringType(), True),
            StructField("caseStatus", StringType(), True),
            StructField("caseType", StringType(), True),
            StructField("caseProcedure", StringType(), True),
            StructField("lpaCode", StringType(), True),
            StructField("caseOfficerId", StringType(), True),
            StructField("inspectorId", StringType(), True),
            StructField("allocationLevel", StringType(), True),
            StructField("allocationBand", DoubleType(), True),
            StructField("caseSpecialisms", ArrayType(StringType(), True), True),
            StructField("caseSubmittedDate", StringType(), True),
            StructField("caseCreatedDate", StringType(), True),
            StructField("caseUpdatedDate", StringType(), True),
            StructField("caseValidDate", StringType(), True),
            StructField("caseValidationDate", StringType(), True),
            StructField("caseValidationOutcome", StringType(), True),
            StructField(
                "caseValidationInvalidDetails", ArrayType(StringType(), True), True
            ),
            StructField(
                "caseValidationIncompleteDetails", ArrayType(StringType(), True), True
            ),
            StructField("caseExtensionDate", StringType(), True),
            StructField("caseStartedDate", StringType(), True),
            StructField("casePublishedDate", StringType(), True),
            StructField("linkedCaseStatus", StringType(), True),
            StructField("leadCaseReference", StringType(), True),
            StructField("lpaQuestionnaireDueDate", StringType(), True),
            StructField("lpaQuestionnaireSubmittedDate", StringType(), True),
            StructField("lpaQuestionnaireCreatedDate", StringType(), True),
            StructField("lpaQuestionnairePublishedDate", StringType(), True),
            StructField("lpaQuestionnaireValidationOutcome", StringType(), True),
            StructField("lpaQuestionnaireValidationOutcomeDate", StringType(), True),
            StructField(
                "lpaQuestionnaireValidationDetails", ArrayType(StringType(), True), True
            ),
            StructField("lpaStatement", StringType(), True),
            StructField("caseWithdrawnDate", StringType(), True),
            StructField("caseTransferredDate", StringType(), True),
            StructField("transferredCaseClosedDate", StringType(), True),
            StructField("caseDecisionOutcomeDate", StringType(), True),
            StructField("caseDecisionPublishedDate", StringType(), True),
            StructField("caseDecisionOutcome", StringType(), True),
            StructField("caseCompletedDate", StringType(), True),
            StructField("enforcementNotice", BooleanType(), True),
            StructField("applicationReference", StringType(), True),
            StructField("applicationDate", StringType(), True),
            StructField("applicationDecision", StringType(), True),
            StructField("applicationDecisionDate", StringType(), True),
            StructField("applicationDecisionDueDate", StringType(), True),
            StructField("caseSubmissionDueDate", StringType(), True),
            StructField("siteAddressLine1", StringType(), True),
            StructField("siteAddressLine2", StringType(), True),
            StructField("siteAddressTown", StringType(), True),
            StructField("siteAddressCounty", StringType(), True),
            StructField("siteAddressPostcode", StringType(), True),
            StructField("siteAccessDetails", ArrayType(StringType(), True), True),
            StructField("siteSafetyDetails", ArrayType(StringType(), True), True),
            StructField("siteAreaSquareMetres", DoubleType(), True),
            StructField("floorSpaceSquareMetres", DoubleType(), True),
            StructField("isCorrectAppealType", BooleanType(), True),
            StructField("isGreenBelt", BooleanType(), True),
            StructField("inConservationArea", BooleanType(), True),
            StructField("ownsAllLand", BooleanType(), True),
            StructField("ownsSomeLand", BooleanType(), True),
            StructField("knowsOtherOwners", StringType(), True),
            StructField("knowsAllOwners", StringType(), True),
            StructField("advertisedAppeal", BooleanType(), True),
            StructField("notificationMethod", ArrayType(StringType(), True), True),
            StructField("ownersInformed", BooleanType(), True),
            StructField("originalDevelopmentDescription", StringType(), True),
            StructField("changedDevelopmentDescription", BooleanType(), True),
            StructField("newConditionDetails", StringType(), True),
            StructField("extraConditionsDetails", StringType(), True),
            StructField("nearbyCaseReferences", ArrayType(StringType(), True), True),
            StructField(
                "neighbouringSiteAddresses",
                ArrayType(
                    StructType(
                        [
                            StructField(
                                "neighbouringSiteAddressLine1", StringType(), True
                            ),
                            StructField(
                                "neighbouringSiteAddressLine2", StringType(), True
                            ),
                            StructField(
                                "neighbouringSiteAddressTown", StringType(), True
                            ),
                            StructField(
                                "neighbouringSiteAddressCounty", StringType(), True
                            ),
                            StructField(
                                "neighbouringSiteAddressPostcode", StringType(), True
                            ),
                            StructField(
                                "neighbouringSiteAccessDetails", StringType(), True
                            ),
                            StructField(
                                "neighbouringSiteSafetyDetails", StringType(), True
                            ),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("reasonForNeighbourVisits", StringType(), True),
            StructField(
                "affectedListedBuildingNumbers", ArrayType(StringType(), True), True
            ),
            StructField(
                "changedListedBuildingNumbers", ArrayType(StringType(), True), True
            ),
            StructField("preserveGrantLoan", BooleanType(), True),
            StructField("consultHistoricEngland", BooleanType(), True),
            StructField("appellantCostsAppliedFor", BooleanType(), True),
            StructField("lpaCostsAppliedFor", BooleanType(), True),
            StructField("agriculturalHolding", BooleanType(), True),
            StructField("tenantAgriculturalHolding", BooleanType(), True),
            StructField("otherTenantsAgriculturalHolding", BooleanType(), True),
            StructField("informedTenantsAgriculturalHolding", BooleanType(), True),
            StructField("appellantProcedurePreference", StringType(), True),
            StructField("appellantProcedurePreferenceDetails", StringType(), True),
            StructField("appellantProcedurePreferenceDuration", DoubleType(), True),
            StructField("appellantProcedurePreferenceWitnessCount", DoubleType(), True),
            StructField("statusPlanningObligation", StringType(), True),
            StructField("affectsScheduledMonument", BooleanType(), True),
            StructField("hasProtectedSpecies", BooleanType(), True),
            StructField("isAonbNationalLandscape", BooleanType(), True),
            StructField("designatedSitesNames", ArrayType(StringType(), True), True),
            StructField("isGypsyOrTravellerSite", BooleanType(), True),
            StructField("isPublicRightOfWay", BooleanType(), True),
            StructField("eiaEnvironmentalImpactSchedule", StringType(), True),
            StructField("eiaDevelopmentDescription", StringType(), True),
            StructField("eiaSensitiveAreaDetails", StringType(), True),
            StructField("eiaColumnTwoThreshold", BooleanType(), True),
            StructField("eiaScreeningOpinion", BooleanType(), True),
            StructField("eiaRequiresEnvironmentalStatement", BooleanType(), True),
            StructField("eiaCompletedEnvironmentalStatement", BooleanType(), True),
            StructField("hasStatutoryConsultees", BooleanType(), True),
            StructField("consultedBodiesDetails", StringType(), True),
            StructField("hasInfrastructureLevy", BooleanType(), True),
            StructField("isInfrastructureLevyFormallyAdopted", BooleanType(), True),
            StructField("infrastructureLevyAdoptedDate", StringType(), True),
            StructField("infrastructureLevyExpectedDate", StringType(), True),
            StructField("lpaProcedurePreference", StringType(), True),
            StructField("lpaProcedurePreferenceDetails", StringType(), True),
            StructField("lpaProcedurePreferenceDuration", DoubleType(), True),
            StructField("caseworkReason", StringType(), True),
            StructField("importantInformation", StringType(), True),
            StructField("jurisdiction", StringType(), True),
            StructField("redeterminedIndicator", StringType(), True),
            StructField("dateCostsReportDespatched", StringType(), True),
            StructField("dateNotRecoveredOrDerecovered", StringType(), True),
            StructField("dateRecovered", StringType(), True),
            StructField("originalCaseDecisionDate", StringType(), True),
            StructField("targetDate", StringType(), True),
            StructField("appellantCommentsSubmittedDate", StringType(), True),
            StructField("appellantStatementDueDate", StringType(), True),
            StructField("appellantStatementSubmittedDate", StringType(), True),
            StructField("appellantProofsSubmittedDate", StringType(), True),
            StructField("finalCommentsDueDate", StringType(), True),
            StructField("interestedPartyRepsDueDate", StringType(), True),
            StructField("lpaCommentsSubmittedDate", StringType(), True),
            StructField("lpaProofsSubmittedDate", StringType(), True),
            StructField("lpaStatementSubmittedDate", StringType(), True),
            StructField("proofsOfEvidenceDueDate", StringType(), True),
            StructField("siteNoticesSentDate", StringType(), True),
            StructField("statementDueDate", StringType(), True),
            StructField("caseManagementConferenceDate", StringType(), True),
            StructField("numberOfResidencesNetChange", DoubleType(), True),
            StructField("siteGridReferenceEasting", StringType(), True),
            StructField("siteGridReferenceNorthing", StringType(), True),
            StructField("siteViewableFromRoad", BooleanType(), True),
            StructField("siteWithinSSSI", BooleanType(), True),
            StructField("typeOfPlanningApplication", StringType(), True),
            StructField("developmentType", StringType(), True),
            StructField("statementOfCommonGroundDueDate", StringType(), True),
            StructField("planningObligationDueDate", StringType(), True),
            StructField("hasLandownersPermission", BooleanType(), True),
            StructField(
                "wasApplicationRefusedDueToHighwayOrTraffic", BooleanType(), True
            ),
            StructField(
                "didAppellantSubmitCompletePhotosAndPlans", BooleanType(), True
            ),
            StructField("isSiteInAreaOfSpecialControlAdverts", BooleanType(), True),
            StructField(
                "advertDetails",
                ArrayType(
                    StructType(
                        [
                            StructField("advertType", StringType(), True),
                            StructField("isAdvertInPosition", BooleanType(), True),
                            StructField("isSiteOnHighwayLand", BooleanType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("padsSapId", StringType(), True),
            StructField("enforcementNoticeReference", StringType(), True),
            StructField("descriptionOfAllegedBreach", StringType(), True),
            StructField("dateAppellantContactedPins", StringType(), True),
            StructField("ownerOccupancyStatus", StringType(), True),
            StructField("occupancyConditionsMet", BooleanType(), True),
            StructField(
                "enforcementAppealGroundsDetails",
                ArrayType(
                    StructType(
                        [
                            StructField("appealGroundLetter", StringType(), True),
                            StructField("groundForAppealStartDate", StringType(), True),
                            StructField("groundFacts", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField(
                "applicationElbAppealGroundsDetails",
                ArrayType(
                    StructType(
                        [
                            StructField("appealGroundLetter", StringType(), True),
                            StructField("groundForAppealStartDate", StringType(), True),
                            StructField("groundFacts", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("applicationMadeAndFeePaid", BooleanType(), True),
            StructField(
                "noticeRelatesToBuildingEngineeringMiningOther", BooleanType(), True
            ),
            StructField("changeOfUseRefuseOrWaste", BooleanType(), True),
            StructField("changeOfUseMineralExtraction", BooleanType(), True),
            StructField("changeOfUseMineralStorage", BooleanType(), True),
            StructField("relatesToErectionOfBuildingOrBuildings", BooleanType(), True),
            StructField(
                "relatesToBuildingWithAgriculturalPurpose", BooleanType(), True
            ),
            StructField("relatesToBuildingSingleDwellingHouse", BooleanType(), True),
            StructField("previousPlanningPermissionGranted", BooleanType(), True),
            StructField("issueDateOfEnforcementNotice", StringType(), True),
            StructField("effectiveDateOfEnforcementNotice", StringType(), True),
            StructField("didAppellantAppealLpaDecision", BooleanType(), True),
            StructField("dateLpaDecisionDue", StringType(), True),
            StructField("dateLpaDecisionReceived", StringType(), True),
            StructField("areaOfAllegedBreachInSquareMetres", DoubleType(), True),
            StructField("doesAllegedBreachCreateFloorSpace", BooleanType(), True),
            StructField("floorSpaceCreatedByBreachInSquareMetres", DoubleType(), True),
            StructField("applicationPartOrWholeDevelopment", StringType(), True),
            StructField("hasPcnBeenServed", BooleanType(), True),
            StructField("isSiteWithin67MOfTrunkRd", BooleanType(), True),
            StructField("affectedTrunkRoadName", StringType(), True),
            StructField("isSiteOnCrownLand", BooleanType(), True),
            StructField("stopNoticeExists", BooleanType(), True),
            StructField("isSiteWithin400MOfMineralInterest", BooleanType(), True),
            StructField("isSiteWithin250MOfLandfill", BooleanType(), True),
            StructField("hasDevelopmentInvolvedWasteImportation", BooleanType(), True),
            StructField("isSiteSubjectToArticle4Direction", BooleanType(), True),
            StructField("article4AffectedDevelopmentRights", StringType(), True),
            StructField("pcnRestrictedDevelopmentRights", BooleanType(), True),
            StructField("applicationMadeUnderActSection", StringType(), True),
            StructField("siteUseAtTimeOfApplication", StringType(), True),
            StructField("appealUnderActSection", StringType(), True),
            StructField("lpaConsiderAppealInvalid", BooleanType(), True),
            StructField("lpaAppealInvalidReasons", StringType(), True),
            StructField("discontinuanceNoticeServedReason", StringType(), True),
            StructField("discontinuanceNoticeServedOtherReason", StringType(), True),
            StructField("wasRetrospectivePlanningApplicationMade", BooleanType(), True),
            StructField("reasonForAppealAppellant", StringType(), True),
            StructField("screeningOpinionIndicatesEiaRequired", BooleanType(), True),
            StructField(
                "significantChangesAffectingApplicationAppellant",
                ArrayType(
                    StructType(
                        [
                            StructField("value", StringType(), True),
                            StructField("comment", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField(
                "significantChangesAffectingApplicationLpa",
                ArrayType(
                    StructType(
                        [
                            StructField("value", StringType(), True),
                            StructField("comment", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("migrated", StringType(), True),
            StructField("ODTSourceSystem", StringType(), True),
            StructField("SourceSystemID", StringType(), True),
            StructField("IngestionDate", TimestampType(), True),
            StructField("ValidTo", StringType(), True),
            StructField("RowID", StringType(), True),
            StructField("IsActive", StringType(), True),
            StructField("message_id", StringType(), True),
            StructField("listOfDocumentsBeforeDecision", StringType(), True),
        ]
    )


def generate_curated_appeal_s78_row(**overrides):
    base = {
        "caseId": 0,
        "caseReference": "6000001",
        "submissionId": "submissionIdValue",
        "caseStatus": "caseStatusValue",
        "caseType": "caseTypeValue",
        "caseProcedure": "caseProcedureValue",
        "lpaCode": "lpaCodeValue",
        "caseOfficerId": "caseOfficerIdValue",
        "inspectorId": "inspectorIdValue",
        "allocationLevel": "allocationLevelValue",
        "allocationBand": Decimal("0"),
        "caseSpecialisms": [],
        "caseSubmittedDate": datetime(2025, 1, 1, 0, 0),
        "caseCreatedDate": datetime(2025, 1, 2, 0, 0),
        "caseUpdatedDate": datetime(2025, 1, 3, 0, 0),
        "caseValidDate": datetime(2025, 1, 4, 0, 0),
        "caseValidationDate": datetime(2025, 1, 5, 0, 0),
        "caseValidationOutcome": "caseValidationOutcomeValue",
        "caseValidationInvalidDetails": [],
        "caseValidationIncompleteDetails": "[caseValidationIncompleteDetailsA, caseValidationIncompleteDetailsB]",
        "caseExtensionDate": datetime(2025, 1, 6, 0, 0),
        "caseStartedDate": datetime(2025, 1, 7, 0, 0),
        "casePublishedDate": datetime(2025, 1, 8, 0, 0),
        "linkedCaseStatus": "linkedCaseStatusValue",
        "leadCaseReference": "leadCaseReferenceValue",
        "lpaQuestionnaireDueDate": datetime(2025, 1, 9, 0, 0),
        "lpaQuestionnaireSubmittedDate": datetime(2025, 1, 10, 0, 0),
        "lpaQuestionnaireCreatedDate": datetime(2025, 1, 11, 0, 0),
        "lpaQuestionnairePublishedDate": datetime(2025, 1, 12, 0, 0),
        "lpaQuestionnaireValidationOutcome": "lpaQuestionnaireValidationOutcomeValue",
        "lpaQuestionnaireValidationOutcomeDate": datetime(2025, 1, 13, 0, 0),
        "lpaQuestionnaireValidationDetails": "[lpaQuestionnaireValidationDetailsA, lpaQuestionnaireValidationDetailsB]",
        "caseWithdrawnDate": datetime(2025, 1, 14, 0, 0),
        "caseTransferredDate": datetime(2025, 1, 15, 0, 0),
        "transferredCaseClosedDate": datetime(2025, 1, 16, 0, 0),
        "caseDecisionOutcomeDate": datetime(2025, 1, 17, 0, 0),
        "caseDecisionPublishedDate": datetime(2025, 1, 18, 0, 0),
        "caseDecisionOutcome": "caseDecisionOutcomeValue",
        "caseCompletedDate": datetime(2025, 1, 19, 0, 0),
        "enforcementNotice": True,
        "applicationReference": "applicationReferenceValue",
        "applicationDate": datetime(2025, 1, 20, 0, 0),
        "applicationDecision": "applicationDecisionValue",
        "applicationDecisionDate": datetime(2025, 1, 21, 0, 0),
        "caseSubmissionDueDate": datetime(2025, 1, 22, 0, 0),
        "siteAddressLine1": "siteAddressLine1Value",
        "siteAddressLine2": "siteAddressLine2Value",
        "siteAddressTown": "siteAddressTownValue",
        "siteAddressCounty": "siteAddressCountyValue",
        "siteAddressPostcode": "siteAddressPostcodeValue",
        "siteAccessDetails": "[siteAccessDetailsA, siteAccessDetailsB]",
        "siteSafetyDetails": "[siteSafetyDetailsA, siteSafetyDetailsB]",
        "siteAreaSquareMetres": Decimal("0"),
        "floorSpaceSquareMetres": Decimal("0"),
        "isCorrectAppealType": True,
        "isGreenBelt": True,
        "inConservationArea": True,
        "ownsAllLand": True,
        "ownsSomeLand": True,
        "knowsOtherOwners": "knowsOtherOwnersValue",
        "knowsAllOwners": "knowsAllOwnersValue",
        "advertisedAppeal": True,
        "notificationMethod": "[notificationMethodA, notificationMethodB]",
        "ownersInformed": True,
        "originalDevelopmentDescription": "originalDevelopmentDescriptionValue",
        "changedDevelopmentDescription": True,
        "newConditionDetails": "newConditionDetailsValue",
        "nearbyCaseReferences": "[nearbyCaseReferencesA, nearbyCaseReferencesB]",
        "neighbouringSiteAddresses": "[{neighbouringSiteAddressLine1A, neighbouringSiteAddressLine2A, neighbouringSiteAddressTownA, neighbouringSiteAddressCountyA, neighbouringSiteAddressPostcodeA, neighbouringSiteAccessDetailsA, neighbouringSiteSafetyDetailsA}, {neighbouringSiteAddressLine1B, neighbouringSiteAddressLine2B, neighbouringSiteAddressTownB, neighbouringSiteAddressCountyB, neighbouringSiteAddressPostcodeB, neighbouringSiteAccessDetailsB, neighbouringSiteSafetyDetailsB}]",
        "affectedListedBuildingNumbers": "[affectedListedBuildingNumbersA, affectedListedBuildingNumbersB]",
        "changedListedBuildingNumbers": "[changedListedBuildingNumbersA, changedListedBuildingNumbersB]",
        "appellantCostsAppliedFor": True,
        "lpaCostsAppliedFor": True,
        "agriculturalHolding": True,
        "tenantAgriculturalHolding": True,
        "otherTenantsAgriculturalHolding": True,
        "informedTenantsAgriculturalHolding": True,
        "appellantProcedurePreference": "appellantProcedurePreferenceValue",
        "appellantProcedurePreferenceDetails": "appellantProcedurePreferenceDetailsValue",
        "appellantProcedurePreferenceDuration": 0.0,
        "appellantProcedurePreferenceWitnessCount": 0.0,
        "statusPlanningObligation": "statusPlanningObligationValue",
        "affectsScheduledMonument": True,
        "hasProtectedSpecies": True,
        "isAonbNationalLandscape": True,
        "designatedSitesNames": "[designatedSitesNamesA, designatedSitesNamesB]",
        "isGypsyOrTravellerSite": True,
        "isPublicRightOfWay": True,
        "eiaEnvironmentalImpactSchedule": "eiaEnvironmentalImpactScheduleValue",
        "eiaDevelopmentDescription": "eiaDevelopmentDescriptionValue",
        "eiaSensitiveAreaDetails": "eiaSensitiveAreaDetailsValue",
        "eiaColumnTwoThreshold": True,
        "eiaScreeningOpinion": True,
        "eiaRequiresEnvironmentalStatement": True,
        "eiaCompletedEnvironmentalStatement": True,
        "hasStatutoryConsultees": True,
        "consultedBodiesDetails": "consultedBodiesDetailsValue",
        "hasInfrastructureLevy": True,
        "isInfrastructureLevyFormallyAdopted": True,
        "infrastructureLevyAdoptedDate": datetime(2025, 1, 23, 0, 0),
        "infrastructureLevyExpectedDate": datetime(2025, 1, 24, 0, 0),
        "lpaProcedurePreference": "lpaProcedurePreferenceValue",
        "lpaProcedurePreferenceDetails": "lpaProcedurePreferenceDetailsValue",
        "lpaProcedurePreferenceDuration": 0.0,
        "developmentType": "developmentTypeValue",
        "importantInformation": "importantInformationValue",
        "jurisdiction": "jurisdictionValue",
        "redeterminedIndicator": "redeterminedIndicatorValue",
        "dateCostsReportDespatched": "2025-01-01T00:00:00.000Z",
        "dateNotRecoveredOrDerecovered": "2025-01-01T00:00:00.000Z",
        "dateRecovered": "2025-01-01T00:00:00.000Z",
        "originalCaseDecisionDate": "2025-01-01T00:00:00.000Z",
        "appellantCommentsSubmittedDate": "2025-01-01T00:00:00.000Z",
        "appellantStatementSubmittedDate": "2025-01-01T00:00:00.000Z",
        "appellantProofsSubmittedDate": "2025-01-01T00:00:00.000Z",
        "finalCommentsDueDate": datetime(2025, 1, 25, 0, 0),
        "interestedPartyRepsDueDate": datetime(2025, 1, 26, 0, 0),
        "lpaCommentsSubmittedDate": "2025-01-01T00:00:00.000Z",
        "lpaProofsSubmittedDate": "2025-01-01T00:00:00.000Z",
        "lpaStatementSubmittedDate": "2025-01-01T00:00:00.000Z",
        "proofsOfEvidenceDueDate": "2025-01-01T00:00:00.000Z",
        "siteNoticesSentDate": "2025-01-01T00:00:00.000Z",
        "statementDueDate": datetime(2025, 1, 27, 0, 0),
        "reasonForNeighbourVisits": "reasonForNeighbourVisitsValue",
        "numberOfResidencesNetChange": 0.0,
        "siteGridReferenceEasting": "siteGridReferenceEastingValue",
        "siteGridReferenceNorthing": "siteGridReferenceNorthingValue",
        "siteViewableFromRoad": True,
        "siteWithinSSSI": True,
        "typeOfPlanningApplication": "typeOfPlanningApplicationValue",
        "preserveGrantLoan": True,
        "consultHistoricEngland": True,
        "padsSapId": "padsSapIdValue",
        "IngestionDate": datetime(2025, 1, 28, 0, 0),
        "ValidTo": datetime(2025, 1, 29, 0, 0),
        "IsActive": "IsActiveValue",
        "planningObligationDueDate": None,
        "statementOfCommonGroundDueDate": None,
        "hasLandownersPermission": True,
        "wasApplicationRefusedDueToHighwayOrTraffic": True,
        "didAppellantSubmitCompletePhotosAndPlans": True,
        "isSiteInAreaOfSpecialControlAdverts": True,
        "advertDetails": [],
        "ownerOccupancyStatus": "ownerOccupancyStatusValue",
        "occupancyConditionsMet": True,
        "enforcementAppealGroundsDetails": [],
        "applicationMadeAndFeePaid": True,
        "noticeRelatesToBuildingEngineeringMiningOther": True,
        "changeOfUseRefuseOrWaste": True,
        "changeOfUseMineralExtraction": True,
        "changeOfUseMineralStorage": True,
        "relatesToErectionOfBuildingOrBuildings": True,
        "relatesToBuildingWithAgriculturalPurpose": True,
        "relatesToBuildingSingleDwellingHouse": True,
        "previousPlanningPermissionGranted": True,
        "issueDateOfEnforcementNotice": None,
        "effectiveDateOfEnforcementNotice": None,
        "didAppellantAppealLpaDecision": True,
        "dateLpaDecisionDue": None,
        "dateLpaDecisionReceived": None,
        "areaOfAllegedBreachInSquareMetres": 0.0,
        "doesAllegedBreachCreateFloorSpace": True,
        "floorSpaceCreatedByBreachInSquareMetres": 0.0,
        "applicationPartOrWholeDevelopment": "applicationPartOrWholeDevelopmentValue",
        "hasPcnBeenServed": True,
        "isSiteWithin67MOfTrunkRd": True,
        "affectedTrunkRoadName": "affectedTrunkRoadNameValue",
        "isSiteOnCrownLand": True,
        "stopNoticeExists": True,
        "isSiteWithin400MOfMineralInterest": True,
        "isSiteWithin250MOfLandfill": True,
        "hasDevelopmentInvolvedWasteImportation": True,
        "isSiteSubjectToArticle4Direction": True,
        "article4AffectedDevelopmentRights": "article4AffectedDevelopmentRightsValue",
        "pcnRestrictedDevelopmentRights": True,
        "enforcementNoticeReference": "enforcementNoticeReferenceValue",
        "descriptionOfAllegedBreach": "descriptionOfAllegedBreachValue",
        "dateAppellantContactedPins": None,
        "applicationMadeUnderActSection": "applicationMadeUnderActSectionValue",
        "siteUseAtTimeOfApplication": "siteUseAtTimeOfApplicationValue",
        "appealUnderActSection": "appealUnderActSectionValue",
        "lpaConsiderAppealInvalid": True,
        "lpaAppealInvalidReasons": "lpaAppealInvalidReasonsValue",
        "applicationElbAppealGroundsDetails": [],
        "extraConditionsDetails": "extraConditionsDetailsValue",
        "reasonForAppealAppellant": "reasonForAppealAppellantValue",
        "significantChangesAffectingApplicationAppellant": [],
        "screeningOpinionIndicatesEiaRequired": True,
        "significantChangesAffectingApplicationLpa": [],
        "listOfDocumentsBeforeDecision": "listOfDocumentsBeforeDecisionValue",
    }
    return base | overrides


def generate_curated_appeal_s78_schema():
    return StructType(
        [
            StructField("caseId", IntegerType(), True),
            StructField("caseReference", StringType(), True),
            StructField("submissionId", StringType(), True),
            StructField("caseStatus", StringType(), True),
            StructField("caseType", StringType(), True),
            StructField("caseProcedure", StringType(), True),
            StructField("lpaCode", StringType(), True),
            StructField("caseOfficerId", StringType(), True),
            StructField("inspectorId", StringType(), True),
            StructField("allocationLevel", StringType(), True),
            StructField("allocationBand", DecimalType(10, 0), True),
            StructField("caseSpecialisms", ArrayType(StringType(), True), True),
            StructField("caseSubmittedDate", TimestampType(), True),
            StructField("caseCreatedDate", TimestampType(), True),
            StructField("caseUpdatedDate", TimestampType(), True),
            StructField("caseValidDate", TimestampType(), True),
            StructField("caseValidationDate", TimestampType(), True),
            StructField("caseValidationOutcome", StringType(), True),
            StructField(
                "caseValidationInvalidDetails", ArrayType(StringType(), True), True
            ),
            StructField("caseValidationIncompleteDetails", StringType(), True),
            StructField("caseExtensionDate", TimestampType(), True),
            StructField("caseStartedDate", TimestampType(), True),
            StructField("casePublishedDate", TimestampType(), True),
            StructField("linkedCaseStatus", StringType(), True),
            StructField("leadCaseReference", StringType(), True),
            StructField("lpaQuestionnaireDueDate", TimestampType(), True),
            StructField("lpaQuestionnaireSubmittedDate", TimestampType(), True),
            StructField("lpaQuestionnaireCreatedDate", TimestampType(), True),
            StructField("lpaQuestionnairePublishedDate", TimestampType(), True),
            StructField("lpaQuestionnaireValidationOutcome", StringType(), True),
            StructField("lpaQuestionnaireValidationOutcomeDate", TimestampType(), True),
            StructField("lpaQuestionnaireValidationDetails", StringType(), True),
            StructField("caseWithdrawnDate", TimestampType(), True),
            StructField("caseTransferredDate", TimestampType(), True),
            StructField("transferredCaseClosedDate", TimestampType(), True),
            StructField("caseDecisionOutcomeDate", TimestampType(), True),
            StructField("caseDecisionPublishedDate", TimestampType(), True),
            StructField("caseDecisionOutcome", StringType(), True),
            StructField("caseCompletedDate", TimestampType(), True),
            StructField("enforcementNotice", BooleanType(), True),
            StructField("applicationReference", StringType(), True),
            StructField("applicationDate", TimestampType(), True),
            StructField("applicationDecision", StringType(), True),
            StructField("applicationDecisionDate", TimestampType(), True),
            StructField("caseSubmissionDueDate", TimestampType(), True),
            StructField("siteAddressLine1", StringType(), True),
            StructField("siteAddressLine2", StringType(), True),
            StructField("siteAddressTown", StringType(), True),
            StructField("siteAddressCounty", StringType(), True),
            StructField("siteAddressPostcode", StringType(), True),
            StructField("siteAccessDetails", StringType(), True),
            StructField("siteSafetyDetails", StringType(), True),
            StructField(
                "siteAreaSquareMetres", DecimalType(10, 0), True
            ),  # This is boolean in the original notebook, which is wrong
            StructField("floorSpaceSquareMetres", DecimalType(10, 0), True),
            StructField("isCorrectAppealType", BooleanType(), True),
            StructField("isGreenBelt", BooleanType(), True),
            StructField("inConservationArea", BooleanType(), True),
            StructField("ownsAllLand", BooleanType(), True),
            StructField("ownsSomeLand", BooleanType(), True),
            StructField("knowsOtherOwners", StringType(), True),
            StructField("knowsAllOwners", StringType(), True),
            StructField("advertisedAppeal", BooleanType(), True),
            StructField("notificationMethod", StringType(), True),
            StructField("ownersInformed", BooleanType(), True),
            StructField("originalDevelopmentDescription", StringType(), True),
            StructField("changedDevelopmentDescription", BooleanType(), True),
            StructField("newConditionDetails", StringType(), True),
            StructField("nearbyCaseReferences", StringType(), True),
            StructField("neighbouringSiteAddresses", StringType(), True),
            StructField("affectedListedBuildingNumbers", StringType(), True),
            StructField("changedListedBuildingNumbers", StringType(), True),
            StructField("appellantCostsAppliedFor", BooleanType(), True),
            StructField("lpaCostsAppliedFor", BooleanType(), True),
            StructField("agriculturalHolding", BooleanType(), True),
            StructField("tenantAgriculturalHolding", BooleanType(), True),
            StructField("otherTenantsAgriculturalHolding", BooleanType(), True),
            StructField("informedTenantsAgriculturalHolding", BooleanType(), True),
            StructField("appellantProcedurePreference", StringType(), True),
            StructField("appellantProcedurePreferenceDetails", StringType(), True),
            StructField("appellantProcedurePreferenceDuration", DoubleType(), True),
            StructField("appellantProcedurePreferenceWitnessCount", DoubleType(), True),
            StructField("statusPlanningObligation", StringType(), True),
            StructField("affectsScheduledMonument", BooleanType(), True),
            StructField("hasProtectedSpecies", BooleanType(), True),
            StructField("isAonbNationalLandscape", BooleanType(), True),
            StructField("designatedSitesNames", StringType(), True),
            StructField("isGypsyOrTravellerSite", BooleanType(), True),
            StructField("isPublicRightOfWay", BooleanType(), True),
            StructField("eiaEnvironmentalImpactSchedule", StringType(), True),
            StructField("eiaDevelopmentDescription", StringType(), True),
            StructField("eiaSensitiveAreaDetails", StringType(), True),
            StructField("eiaColumnTwoThreshold", BooleanType(), True),
            StructField("eiaScreeningOpinion", BooleanType(), True),
            StructField("eiaRequiresEnvironmentalStatement", BooleanType(), True),
            StructField("eiaCompletedEnvironmentalStatement", BooleanType(), True),
            StructField("hasStatutoryConsultees", BooleanType(), True),
            StructField("consultedBodiesDetails", StringType(), True),
            StructField("hasInfrastructureLevy", BooleanType(), True),
            StructField("isInfrastructureLevyFormallyAdopted", BooleanType(), True),
            StructField("infrastructureLevyAdoptedDate", TimestampType(), True),
            StructField("infrastructureLevyExpectedDate", TimestampType(), True),
            StructField("lpaProcedurePreference", StringType(), True),
            StructField("lpaProcedurePreferenceDetails", StringType(), True),
            StructField("lpaProcedurePreferenceDuration", DoubleType(), True),
            StructField("developmentType", StringType(), True),
            StructField("importantInformation", StringType(), True),
            StructField("jurisdiction", StringType(), True),
            StructField("redeterminedIndicator", StringType(), True),
            StructField("dateCostsReportDespatched", StringType(), True),
            StructField("dateNotRecoveredOrDerecovered", StringType(), True),
            StructField("dateRecovered", StringType(), True),
            StructField("originalCaseDecisionDate", StringType(), True),
            StructField("appellantCommentsSubmittedDate", StringType(), True),
            StructField("appellantStatementSubmittedDate", StringType(), True),
            StructField("appellantProofsSubmittedDate", StringType(), True),
            StructField("finalCommentsDueDate", TimestampType(), True),
            StructField("interestedPartyRepsDueDate", TimestampType(), True),
            StructField("lpaCommentsSubmittedDate", StringType(), True),
            StructField("lpaProofsSubmittedDate", StringType(), True),
            StructField("lpaStatementSubmittedDate", StringType(), True),
            StructField("proofsOfEvidenceDueDate", StringType(), True),
            StructField("siteNoticesSentDate", StringType(), True),
            StructField("statementDueDate", TimestampType(), True),
            StructField("reasonForNeighbourVisits", StringType(), True),
            StructField("numberOfResidencesNetChange", DoubleType(), True),
            StructField("siteGridReferenceEasting", StringType(), True),
            StructField("siteGridReferenceNorthing", StringType(), True),
            StructField("siteViewableFromRoad", BooleanType(), True),
            StructField("siteWithinSSSI", BooleanType(), True),
            StructField("typeOfPlanningApplication", StringType(), True),
            StructField("preserveGrantLoan", BooleanType(), True),
            StructField("consultHistoricEngland", BooleanType(), True),
            StructField("padsSapId", StringType(), True),
            StructField("IngestionDate", TimestampType(), True),
            StructField("ValidTo", TimestampType(), True),
            StructField("IsActive", StringType(), True),
            StructField("planningObligationDueDate", StringType(), True),
            StructField("statementOfCommonGroundDueDate", StringType(), True),
            StructField("hasLandownersPermission", BooleanType(), True),
            StructField(
                "wasApplicationRefusedDueToHighwayOrTraffic", BooleanType(), True
            ),
            StructField(
                "didAppellantSubmitCompletePhotosAndPlans", BooleanType(), True
            ),
            StructField("isSiteInAreaOfSpecialControlAdverts", BooleanType(), True),
            StructField(
                "advertDetails",
                ArrayType(
                    StructType(
                        [
                            StructField("advertType", StringType(), True),
                            StructField("isAdvertInPosition", BooleanType(), True),
                            StructField("isSiteOnHighwayLand", BooleanType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("ownerOccupancyStatus", StringType(), True),
            StructField("occupancyConditionsMet", BooleanType(), True),
            StructField(
                "enforcementAppealGroundsDetails",
                ArrayType(
                    StructType(
                        [
                            StructField("appealGroundLetter", StringType(), True),
                            StructField("groundForAppealStartDate", StringType(), True),
                            StructField("groundFacts", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("applicationMadeAndFeePaid", BooleanType(), True),
            StructField(
                "noticeRelatesToBuildingEngineeringMiningOther", BooleanType(), True
            ),
            StructField("changeOfUseRefuseOrWaste", BooleanType(), True),
            StructField("changeOfUseMineralExtraction", BooleanType(), True),
            StructField("changeOfUseMineralStorage", BooleanType(), True),
            StructField("relatesToErectionOfBuildingOrBuildings", BooleanType(), True),
            StructField(
                "relatesToBuildingWithAgriculturalPurpose", BooleanType(), True
            ),
            StructField("relatesToBuildingSingleDwellingHouse", BooleanType(), True),
            StructField("previousPlanningPermissionGranted", BooleanType(), True),
            StructField("issueDateOfEnforcementNotice", StringType(), True),
            StructField("effectiveDateOfEnforcementNotice", StringType(), True),
            StructField("didAppellantAppealLpaDecision", BooleanType(), True),
            StructField("dateLpaDecisionDue", StringType(), True),
            StructField("dateLpaDecisionReceived", StringType(), True),
            StructField("areaOfAllegedBreachInSquareMetres", DoubleType(), True),
            StructField("doesAllegedBreachCreateFloorSpace", BooleanType(), True),
            StructField("floorSpaceCreatedByBreachInSquareMetres", DoubleType(), True),
            StructField("applicationPartOrWholeDevelopment", StringType(), True),
            StructField("hasPcnBeenServed", BooleanType(), True),
            StructField("isSiteWithin67MOfTrunkRd", BooleanType(), True),
            StructField("affectedTrunkRoadName", StringType(), True),
            StructField("isSiteOnCrownLand", BooleanType(), True),
            StructField("stopNoticeExists", BooleanType(), True),
            StructField("isSiteWithin400MOfMineralInterest", BooleanType(), True),
            StructField("isSiteWithin250MOfLandfill", BooleanType(), True),
            StructField("hasDevelopmentInvolvedWasteImportation", BooleanType(), True),
            StructField("isSiteSubjectToArticle4Direction", BooleanType(), True),
            StructField("article4AffectedDevelopmentRights", StringType(), True),
            StructField("pcnRestrictedDevelopmentRights", BooleanType(), True),
            StructField("enforcementNoticeReference", StringType(), True),
            StructField("descriptionOfAllegedBreach", StringType(), True),
            StructField("dateAppellantContactedPins", StringType(), True),
            StructField("applicationMadeUnderActSection", StringType(), True),
            StructField("siteUseAtTimeOfApplication", StringType(), True),
            StructField("appealUnderActSection", StringType(), True),
            StructField("lpaConsiderAppealInvalid", BooleanType(), True),
            StructField("lpaAppealInvalidReasons", StringType(), True),
            StructField(
                "applicationElbAppealGroundsDetails",
                ArrayType(
                    StructType(
                        [
                            StructField("appealGroundLetter", StringType(), True),
                            StructField("groundForAppealStartDate", StringType(), True),
                            StructField("groundFacts", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("extraConditionsDetails", StringType(), True),
            StructField("reasonForAppealAppellant", StringType(), True),
            StructField(
                "significantChangesAffectingApplicationAppellant",
                ArrayType(
                    StructType(
                        [
                            StructField("value", StringType(), True),
                            StructField("comment", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("screeningOpinionIndicatesEiaRequired", BooleanType(), True),
            StructField(
                "significantChangesAffectingApplicationLpa",
                ArrayType(
                    StructType(
                        [
                            StructField("value", StringType(), True),
                            StructField("comment", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("listOfDocumentsBeforeDecision", StringType(), True),
        ]
    )


class TestAppealS78MIPinsCurationProcess(ETLTestCase):
    def assert_successful_run(self, test_case: str):
        spark = PytestSparkSessionUtil().get_spark_session()
        appeal_s78 = spark.createDataFrame(
            (
                generate_appeal_s78_schema(),
                generate_appeal_s78_schema(),  # Duplicate row should be dropped
            ),
            schema=generate_appeal_s78_schema(),
        )
        appeal_s78_table = f"{test_case}_appeal_s78"
        self.write_existing_table(
            spark,
            appeal_s78,
            appeal_s78_table,
            "odw_curated_db",
            "odw-curated-db",
            appeal_s78_table,
            "overwrite",
        )
        expected_curated_data_after_writing = spark.createDataFrame(
            (generate_curated_appeal_s78_row(),),
            schema=generate_curated_appeal_s78_schema(),
        )
        expected_output_table = f"{test_case}_appeals_s78_curated_mipins"
        with mock.patch.object(
            AppealS78MIPINSCurationProcess, "APPEALS_S78_TABLE", appeal_s78_table
        ):
            with mock.patch.object(
                AppealS78MIPINSCurationProcess, "OUTPUT_TABLE", expected_output_table
            ):
                inst = AppealS78MIPINSCurationProcess(spark)
                result = inst.run(
                    orchestration_run_id=test_case,
                    orchestration_entity_name="appeal_s78_mipins",
                    orchestration_stage_name="curate",
                )
                assert_etl_result_successful(result)
                actual_table_data = spark.table(
                    f"odw_curated_db.{expected_output_table}"
                )
                assert_dataframes_equal(
                    expected_curated_data_after_writing, actual_table_data
                )

    def test__appeal_s78_mipins_curation_process__run__with_no_existing_data(self):
        """
        - Given I have appeal_s78 data in the curated layer
        - When I call AppealS78MIPINSCurationProcess.run
        - Then a appeals_s78_curated_mipins table should be created in the curated layer
        """
        test_case = "t_as78mcp_r_wned"
        self.assert_successful_run(test_case)

    def test__appeal_s78_mipins_curation_process__run__with_existing_data(self):
        """
        - Given I have appeal_s78 data in the curated layer and an existing appeals_s78_curated_mipins in the curated layer
        - When I call AppealS78MIPINSCurationProcess.run
        - Then the appeals_s78_curated_mipins table should be created in the curated layer, overwriting the existing table
        """
        spark = PytestSparkSessionUtil().get_spark_session()
        test_case = "t_as78mcp_r_wed"
        existing_data = spark.createDataFrame(
            (generate_curated_appeal_s78_row(),),
            schema=generate_curated_appeal_s78_schema(),
        )
        existing_table_name = f"{test_case}_appeals_s78_curated_mipins"
        self.write_existing_table(
            spark,
            existing_data,
            existing_table_name,
            "odw_curated_db",
            "odw-curated-db",
            existing_table_name,
            "overwrite",
        )
        self.assert_successful_run(test_case)
