import odw.test.util.mock.import_mock_notebook_utils  # noqa: F401
from odw.core.etl.transformation.curated.dart_api_curation_process import DartApiCuratedProcess
from odw.test.integration_test.etl.etl_test_case import ETLTestCase
from odw.test.util.session_util import PytestSparkSessionUtil
from odw.test.util.assertion import assert_dataframes_equal, assert_etl_result_successful
from pyspark.sql.types import StringType, StructField, StructType, LongType, DoubleType, ArrayType, BooleanType, TimestampType
from datetime import datetime
import mock
#import pytest


#pytestmark = pytest.mark.xfail(reason="Curated logic not implemented yet")


def generate_harmonised_appeal_has_row(**overrides):
    base = {
        "caseReference": "6000001",
        "caseId": None,
        "submissionId": "",
        "caseStatus": "validation",
        "caseType": "D",
        "caseProcedure": "written",
        "lpaCode": "LOAD1",
        "caseOfficerId": "",
        "inspectorId": "",
        "allocationLevel": "",
        "allocationBand": 0.0,
        "caseSpecialisms": ["specialismA"],
        "caseSubmittedDate": "",
        "caseCreatedDate": "",
        "caseUpdatedDate": "",
        "caseValidDate": "",
        "caseValidationDate": "",
        "caseValidationOutcome": "",
        "caseValidationInvalidDetails": ["caseValidationInvalidDetails"],
        "caseValidationIncompleteDetails": ["caseValidationIncompleteDetails"],
        "caseExtensionDate": "",
        "caseStartedDate": "",
        "casePublishedDate": "",
        "linkedCaseStatus": "",
        "leadCaseReference": "",
        "lpaQuestionnaireDueDate": "",
        "lpaQuestionnaireSubmittedDate": "",
        "lpaQuestionnaireCreatedDate": "",
        "lpaQuestionnairePublishedDate": "",
        "lpaQuestionnaireValidationOutcome": "",
        "lpaQuestionnaireValidationOutcomeDate": "",
        "lpaQuestionnaireValidationDetails": ["lpaQuestionnaireValidationDetails"],
        "lpaStatement": "",
        "caseWithdrawnDate": "",
        "caseTransferredDate": "",
        "transferredCaseClosedDate": "",
        "caseDecisionOutcomeDate": "",
        "caseDecisionPublishedDate": "",
        "caseDecisionOutcome": "",
        "caseCompletedDate": "",
        "enforcementNotice": True,
        "applicationReference": "",
        "applicationDate": "",
        "applicationDecision": "refused",
        "applicationDecisionDate": "",
        "caseSubmissionDueDate": "",
        "siteAddressLine1": "",
        "siteAddressLine2": "",
        "siteAddressTown": "",
        "siteAddressCounty": "",
        "siteAddressPostcode": "",
        "siteAccessDetails": ["siteAccessDetails"],
        "siteSafetyDetails": ["siteSafetyDetails"],
        "siteAreaSquareMetres": 10.0,
        "floorSpaceSquareMetres": 5.0,
        "isCorrectAppealType": True,
        "isGreenBelt": True,
        "inConservationArea": True,
        "affectsScheduledMonument": True,
        "hasProtectedSpecies": True,
        "isAonbNationalLandscape": True,
        "isSiteOnHighwayLand": True,
        "designatedSitesNames": ["designatedSitesNames"],
        "hasInfrastructureLevy": True,
        "isInfrastructureLevyFormallyAdopted": True,
        "infrastructureLevyAdoptedDate": "",
        "infrastructureLevyExpectedDate": "",
        "lpaProcedurePreference": "",
        "lpaProcedurePreferenceDetails": "",
        "lpaProcedurePreferenceDuration": 0.0,
        "caseworkReason": "",
        "importantInformation": "",
        "jurisdiction": "",
        "redeterminedIndicator": True,
        "dateCostsReportDespatched": "",
        "dateNotRecoveredOrDerecovered": "",
        "dateRecovered": "",
        "originalCaseDecisionDate": "",
        "targetDate": "",
        "ownsAllLand": True,
        "ownsSomeLand": True,
        "knowsOtherOwners": "",
        "knowsAllOwners": "",
        "advertisedAppeal": True,
        "notificationMethod": ["notificationMethod"],
        "ownersInformed": True,
        "originalDevelopmentDescription": "",
        "changedDevelopmentDescription": True,
        "newConditionDetails": "",
        "nearbyCaseReferences": ["nearbyCaseReferences"],
        "neighbouringSiteAddresses": [
            {
                "neighbouringSiteAddressLine1": "",
                "neighbouringSiteAddressLine2": "",
                "neighbouringSiteAddressTown": "",
                "neighbouringSiteAddressCounty": "",
                "neighbouringSiteAddressPostcode": "",
                "neighbouringSiteAccessDetails": "",
                "neighbouringSiteSafetyDetails": "",
            }
        ],
        "reasonForNeighbourVisits": "",
        "affectedListedBuildingNumbers": ["affectedListedBuildingNumbers"],
        "appellantCostsAppliedFor": True,
        "lpaCostsAppliedFor": True,
        "typeOfPlanningApplication": "householder-planning",
        "siteGridReferenceEasting": "",
        "siteGridReferenceNorthing": "",
        "hasLandownersPermission": True,
        "wasApplicationRefusedDueToHighwayOrTraffic": True,
        "didAppellantSubmitCompletePhotosAndPlans": True,
        "isSiteInAreaOfSpecialControlAdverts": True,
        "advertDetails": [
            {
                "advertType": "",
                "isAdvertInPosition": True,
                "isSiteOnHighwayLand": True,
            }
        ],
        "padsSapId": "",
        "message_id": "",
        "applicationDecisionDueDate": "",
        "SourceSystemID": "5",
        "RowID": "",
        "migrated": "1",
        "ODTSourceSystem": "ODT",
        "ValidTo": "",
        "IsActive": "Y",
        "AppealsHasID": 1,
        "IngestionDate": datetime(2025, 1, 1),
        "appellantProcedurePreference": "",
        "appellantProcedurePreferenceDetails": "",
        "appellantProcedurePreferenceDuration": "",
        "appellantProcedurePreferenceWitnessCount": "",
        "consultedBodiesDetails": "",
        "designAccessStatementProvided": "",
        "developmentType": "",
        "hasEmergingPlan": True,
        "hasStatutoryConsultees": True,
        "numberOfResidencesNetChange": "",
        "planningObligation": "",
        "siteViewableFromRoad": "",
        "siteWithinSSSI": "",
        "statusPlanningObligation": "",
    }
    return base | overrides


def generate_harmonised_appeal_has_schema():
    return StructType(
        [
            StructField("caseReference", StringType(), True),
            StructField("caseId", LongType(), True),
            StructField("submissionId", StringType(), True),
            StructField("caseStatus", StringType(), True),
            StructField("caseType", StringType(), True),
            StructField("caseProcedure", StringType(), True),
            StructField("lpaCode", StringType(), True),
            StructField("caseOfficerId", StringType(), True),
            StructField("inspectorId", StringType(), True),
            StructField("allocationLevel", StringType(), True),
            StructField("allocationBand", DoubleType(), True),
            StructField("caseSpecialisms", ArrayType(StringType(), True), True),
            StructField("caseSubmittedDate", StringType(), True),
            StructField("caseCreatedDate", StringType(), True),
            StructField("caseUpdatedDate", StringType(), True),
            StructField("caseValidDate", StringType(), True),
            StructField("caseValidationDate", StringType(), True),
            StructField("caseValidationOutcome", StringType(), True),
            StructField("caseValidationInvalidDetails", ArrayType(StringType(), True), True),
            StructField("caseValidationIncompleteDetails", ArrayType(StringType(), True), True),
            StructField("caseExtensionDate", StringType(), True),
            StructField("caseStartedDate", StringType(), True),
            StructField("casePublishedDate", StringType(), True),
            StructField("linkedCaseStatus", StringType(), True),
            StructField("leadCaseReference", StringType(), True),
            StructField("lpaQuestionnaireDueDate", StringType(), True),
            StructField("lpaQuestionnaireSubmittedDate", StringType(), True),
            StructField("lpaQuestionnaireCreatedDate", StringType(), True),
            StructField("lpaQuestionnairePublishedDate", StringType(), True),
            StructField("lpaQuestionnaireValidationOutcome", StringType(), True),
            StructField("lpaQuestionnaireValidationOutcomeDate", StringType(), True),
            StructField("lpaQuestionnaireValidationDetails", ArrayType(StringType(), True), True),
            StructField("lpaStatement", StringType(), True),
            StructField("caseWithdrawnDate", StringType(), True),
            StructField("caseTransferredDate", StringType(), True),
            StructField("transferredCaseClosedDate", StringType(), True),
            StructField("caseDecisionOutcomeDate", StringType(), True),
            StructField("caseDecisionPublishedDate", StringType(), True),
            StructField("caseDecisionOutcome", StringType(), True),
            StructField("caseCompletedDate", StringType(), True),
            StructField("enforcementNotice", BooleanType(), True),
            StructField("applicationReference", StringType(), True),
            StructField("applicationDate", StringType(), True),
            StructField("applicationDecision", StringType(), True),
            StructField("applicationDecisionDate", StringType(), True),
            StructField("caseSubmissionDueDate", StringType(), True),
            StructField("siteAddressLine1", StringType(), True),
            StructField("siteAddressLine2", StringType(), True),
            StructField("siteAddressTown", StringType(), True),
            StructField("siteAddressCounty", StringType(), True),
            StructField("siteAddressPostcode", StringType(), True),
            StructField("siteAccessDetails", ArrayType(StringType(), True), True),
            StructField("siteSafetyDetails", ArrayType(StringType(), True), True),
            StructField("siteAreaSquareMetres", DoubleType(), True),
            StructField("floorSpaceSquareMetres", DoubleType(), True),
            StructField("isCorrectAppealType", BooleanType(), True),
            StructField("isGreenBelt", BooleanType(), True),
            StructField("inConservationArea", BooleanType(), True),
            StructField("affectsScheduledMonument", BooleanType(), True),
            StructField("hasProtectedSpecies", BooleanType(), True),
            StructField("isAonbNationalLandscape", BooleanType(), True),
            StructField("isSiteOnHighwayLand", BooleanType(), True),
            StructField("designatedSitesNames", ArrayType(StringType(), True), True),
            StructField("hasInfrastructureLevy", BooleanType(), True),
            StructField("isInfrastructureLevyFormallyAdopted", BooleanType(), True),
            StructField("infrastructureLevyAdoptedDate", StringType(), True),
            StructField("infrastructureLevyExpectedDate", StringType(), True),
            StructField("lpaProcedurePreference", StringType(), True),
            StructField("lpaProcedurePreferenceDetails", StringType(), True),
            StructField("lpaProcedurePreferenceDuration", DoubleType(), True),
            StructField("caseworkReason", StringType(), True),
            StructField("importantInformation", StringType(), True),
            StructField("jurisdiction", StringType(), True),
            StructField("redeterminedIndicator", BooleanType(), True),
            StructField("dateCostsReportDespatched", StringType(), True),
            StructField("dateNotRecoveredOrDerecovered", StringType(), True),
            StructField("dateRecovered", StringType(), True),
            StructField("originalCaseDecisionDate", StringType(), True),
            StructField("targetDate", StringType(), True),
            StructField("ownsAllLand", BooleanType(), True),
            StructField("ownsSomeLand", BooleanType(), True),
            StructField("knowsOtherOwners", StringType(), True),
            StructField("knowsAllOwners", StringType(), True),
            StructField("advertisedAppeal", BooleanType(), True),
            StructField("notificationMethod", ArrayType(StringType(), True), True),
            StructField("ownersInformed", BooleanType(), True),
            StructField("originalDevelopmentDescription", StringType(), True),
            StructField("changedDevelopmentDescription", BooleanType(), True),
            StructField("newConditionDetails", StringType(), True),
            StructField("nearbyCaseReferences", ArrayType(StringType(), True), True),
            StructField(
                "neighbouringSiteAddresses",
                ArrayType(
                    StructType(
                        [
                            StructField("neighbouringSiteAddressLine1", StringType(), True),
                            StructField("neighbouringSiteAddressLine2", StringType(), True),
                            StructField("neighbouringSiteAddressTown", StringType(), True),
                            StructField("neighbouringSiteAddressCounty", StringType(), True),
                            StructField("neighbouringSiteAddressPostcode", StringType(), True),
                            StructField("neighbouringSiteAccessDetails", StringType(), True),
                            StructField("neighbouringSiteSafetyDetails", StringType(), True),
                        ]
                    ),
                    True,
                ),
            ),
            StructField("reasonForNeighbourVisits", StringType(), True),
            StructField("affectedListedBuildingNumbers", ArrayType(StringType(), True), True),
            StructField("appellantCostsAppliedFor", BooleanType(), True),
            StructField("lpaCostsAppliedFor", BooleanType(), True),
            StructField("typeOfPlanningApplication", StringType(), True),
            StructField("siteGridReferenceEasting", StringType(), True),
            StructField("siteGridReferenceNorthing", StringType(), True),
            StructField("hasLandownersPermission", BooleanType(), True),
            StructField("wasApplicationRefusedDueToHighwayOrTraffic", BooleanType(), True),
            StructField("didAppellantSubmitCompletePhotosAndPlans", BooleanType(), True),
            StructField("isSiteInAreaOfSpecialControlAdverts", BooleanType(), True),
            StructField(
                "advertDetails",
                ArrayType(
                    StructType(
                        [
                            StructField("advertType", StringType(), True),
                            StructField("isAdvertInPosition", BooleanType(), True),
                            StructField("isSiteOnHighwayLand", BooleanType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("padsSapId", StringType(), True),
            StructField("message_id", StringType(), True),
            StructField("applicationDecisionDueDate", StringType(), True),
            StructField("SourceSystemID", StringType(), True),
            StructField("RowID", StringType(), True),
            StructField("migrated", StringType(), True),
            StructField("ODTSourceSystem", StringType(), True),
            StructField("ValidTo", StringType(), True),
            StructField("IsActive", StringType(), True),
            StructField("AppealsHasID", LongType(), True),
            StructField("IngestionDate", TimestampType(), True),
            StructField("appellantProcedurePreference", StringType(), True),
            StructField("appellantProcedurePreferenceDetails", StringType(), True),
            StructField("appellantProcedurePreferenceDuration", StringType(), True),
            StructField("appellantProcedurePreferenceWitnessCount", StringType(), True),
            StructField("consultedBodiesDetails", StringType(), True),
            StructField("designAccessStatementProvided", StringType(), True),
            StructField("developmentType", StringType(), True),
            StructField("hasEmergingPlan", BooleanType(), True),
            StructField("hasStatutoryConsultees", BooleanType(), True),
            StructField("numberOfResidencesNetChange", StringType(), True),
            StructField("planningObligation", StringType(), True),
            StructField("siteViewableFromRoad", StringType(), True),
            StructField("siteWithinSSSI", StringType(), True),
            StructField("statusPlanningObligation", StringType(), True),
        ]
    )


def generate_harmonised_pins_lpa_row(**overrides):
    base = {
        "LPAId": None,
        "lpaName": None,
        "organisationType": None,
        "pinsLpaCode": None,
        "poBox": None,
        "address1": None,
        "address2": None,
        "city": None,
        "county": None,
        "postcode": None,
        "country": None,
        "telephoneNumber": None,
        "fax": None,
        "emailAddress": None,
        "migrated": None,
        "ODTSourceSystem": None,
        "SourceSystemID": None,
        "IngestionDate": datetime(2025, 1, 1),
        "ValidTo": None,
        "RowID": None,
        "IsActive": "Y",
    }
    return base | overrides


def generate_harmonised_pins_lpa_schema():
    return StructType(
        [
            StructField("LPAId", LongType(), True),
            StructField("lpaName", StringType(), True),
            StructField("organisationType", StringType(), True),
            StructField("pinsLpaCode", StringType(), True),
            StructField("poBox", StringType(), True),
            StructField("address1", StringType(), True),
            StructField("address2", StringType(), True),
            StructField("city", StringType(), True),
            StructField("county", StringType(), True),
            StructField("postcode", StringType(), True),
            StructField("country", StringType(), True),
            StructField("telephoneNumber", StringType(), True),
            StructField("fax", StringType(), True),
            StructField("emailAddress", StringType(), True),
            StructField("migrated", StringType(), True),
            StructField("ODTSourceSystem", StringType(), True),
            StructField("SourceSystemID", StringType(), True),
            StructField("IngestionDate", StringType(), True),
            StructField("ValidTo", StringType(), True),
            StructField("RowID", StringType(), True),
            StructField("IsActive", StringType(), True),
        ]
    )


def generate_harmonised_sb_service_user_row(**overrides):
    base = {
        "id": None,
        "salutation": None,
        "firstName": None,
        "lastName": None,
        "addressLine1": None,
        "addressLine2": None,
        "addressTown": None,
        "addressCounty": None,
        "postcode": None,
        "addressCountry": None,
        "organisation": None,
        "organisationType": None,
        "role": None,
        "telephoneNumber": None,
        "otherPhoneNumber": None,
        "faxNumber": None,
        "emailAddress": None,
        "webAddress": None,
        "serviceUserType": None,
        "caseReference": None,
        "sourceSystem": None,
        "sourceSuid": None,
        "migrated": None,
        "ODTSourceSystem": None,
        "SourceSystemID": None,
        "IngestionDate": None,
        "ValidTo": None,
        "RowID": None,
        "IsActive": "Y",
        "message_id": None,
        "ServiceUserID": 1,
    }
    return base | overrides


def generate_harmonised_sb_service_user_schema():
    return StructType(
        [
            StructField("id", StringType(), True),
            StructField("salutation", StringType(), True),
            StructField("firstName", StringType(), True),
            StructField("lastName", StringType(), True),
            StructField("addressLine1", StringType(), True),
            StructField("addressLine2", StringType(), True),
            StructField("addressTown", StringType(), True),
            StructField("addressCounty", StringType(), True),
            StructField("postcode", StringType(), True),
            StructField("addressCountry", StringType(), True),
            StructField("organisation", StringType(), True),
            StructField("organisationType", StringType(), True),
            StructField("role", StringType(), True),
            StructField("telephoneNumber", StringType(), True),
            StructField("otherPhoneNumber", StringType(), True),
            StructField("faxNumber", StringType(), True),
            StructField("emailAddress", StringType(), True),
            StructField("webAddress", StringType(), True),
            StructField("serviceUserType", StringType(), True),
            StructField("caseReference", StringType(), True),
            StructField("sourceSystem", StringType(), True),
            StructField("sourceSuid", StringType(), True),
            StructField("migrated", StringType(), True),
            StructField("ODTSourceSystem", StringType(), True),
            StructField("SourceSystemID", StringType(), True),
            StructField("IngestionDate", StringType(), True),
            StructField("ValidTo", StringType(), True),
            StructField("RowID", StringType(), True),
            StructField("IsActive", StringType(), True),
            StructField("message_id", StringType(), True),
            StructField("ServiceUserID", LongType(), True),
        ]
    )


def generate_harmonised_sb_appeal_event_row(**overrides):
    base = {
        "eventId": None,
        "caseReference": None,
        "eventType": None,
        "eventName": None,
        "eventStatus": None,
        "isUrgent": True,
        "eventPublished": True,
        "eventStartDateTime": None,
        "eventEndDateTime": None,
        "notificationOfSiteVisit": None,
        "addressLine1": None,
        "addressLine2": None,
        "addressTown": None,
        "addressCounty": None,
        "addressPostcode": None,
        "ODTSourceSystem": None,
        "SourceSystemID": None,
        "IngestionDate": None,
        "ValidTo": None,
        "RowID": None,
        "IsActive": "Y",
        "message_id": None,
        "migrated": None,
        "AppealsEventId": 1,
    }
    return base | overrides


def generate_harmonised_sb_appeal_event_schema():
    return StructType(
        [
            StructField("eventId", StringType(), True),
            StructField("caseReference", StringType(), True),
            StructField("eventType", StringType(), True),
            StructField("eventName", StringType(), True),
            StructField("eventStatus", StringType(), True),
            StructField("isUrgent", BooleanType(), True),
            StructField("eventPublished", BooleanType(), True),
            StructField("eventStartDateTime", StringType(), True),
            StructField("eventEndDateTime", StringType(), True),
            StructField("notificationOfSiteVisit", StringType(), True),
            StructField("addressLine1", StringType(), True),
            StructField("addressLine2", StringType(), True),
            StructField("addressTown", StringType(), True),
            StructField("addressCounty", StringType(), True),
            StructField("addressPostcode", StringType(), True),
            StructField("ODTSourceSystem", StringType(), True),
            StructField("SourceSystemID", StringType(), True),
            StructField("IngestionDate", StringType(), True),
            StructField("ValidTo", StringType(), True),
            StructField("RowID", StringType(), True),
            StructField("IsActive", StringType(), True),
            StructField("message_id", StringType(), True),
            StructField("migrated", StringType(), True),
            StructField("AppealsEventId", LongType(), True),
        ]
    )


def generate_harmonised_entraid_row(**overrides):
    base = {
        "EmployeeEntraId": None,
        "employeeId": None,
        "id": None,
        "givenName": None,
        "surname": None,
        "userPrincipalName": None,
        "migrated": None,
        "ODTSourceSystem": None,
        "SourceSystemID": None,
        "IngestionDate": None,
        "ValidTo": None,
        "RowID": None,
        "IsActive": "Y",
    }
    return base | overrides


def generate_harmonised_entraid_schema():
    return StructType(
        [
            StructField("EmployeeEntraId", LongType(), True),
            StructField("employeeId", StringType(), True),
            StructField("id", StringType(), True),
            StructField("givenName", StringType(), True),
            StructField("surname", StringType(), True),
            StructField("userPrincipalName", StringType(), True),
            StructField("migrated", StringType(), True),
            StructField("ODTSourceSystem", StringType(), True),
            StructField("SourceSystemID", StringType(), True),
            StructField("IngestionDate", StringType(), True),
            StructField("ValidTo", StringType(), True),
            StructField("RowID", StringType(), True),
            StructField("IsActive", StringType(), True),
        ]
    )


def generate_harmonised_horizon_pins_inspector_row(**overrides):
    base = {
        "ingested_datetime": datetime(2025, 1, 1),
        "expected_from": datetime(2025, 1, 1),
        "expected_to": datetime(2025, 1, 1),
        "horizonId": None,
        "firstName": None,
        "lastName": None,
        "postName": None,
        "organisationName": None,
        "title": None,
        "salutation": None,
        "qualifications": None,
        "email": None,
        "ingested_by_process_name": None,
        "input_file": None,
        "modified_datetime": datetime(2025, 1, 1),
        "modified_by_process_name": None,
        "entity_name": None,
        "file_id": None,
        "IngestionDate": datetime(2025, 1, 1),
        "Migrated": None,
        "ODTSourceSystem": None,
        "ValidTo": datetime(2025, 1, 1),
        "RowID": None,
        "IsActive": "Y",
        "SourceSystemID": None,
    }
    return base | overrides


def generate_harmonised_horizon_pins_inspector_schema():
    return StructType(
        [
            StructField("ingested_datetime", TimestampType(), True),
            StructField("expected_from", TimestampType(), True),
            StructField("expected_to", TimestampType(), True),
            StructField("horizonId", StringType(), True),
            StructField("firstName", StringType(), True),
            StructField("lastName", StringType(), True),
            StructField("postName", StringType(), True),
            StructField("organisationName", StringType(), True),
            StructField("title", StringType(), True),
            StructField("salutation", StringType(), True),
            StructField("qualifications", StringType(), True),
            StructField("email", StringType(), True),
            StructField("ingested_by_process_name", StringType(), True),
            StructField("input_file", StringType(), True),
            StructField("modified_datetime", TimestampType(), True),
            StructField("modified_by_process_name", StringType(), True),
            StructField("entity_name", StringType(), True),
            StructField("file_id", StringType(), True),
            StructField("IngestionDate", TimestampType(), True),
            StructField("Migrated", StringType(), True),
            StructField("ODTSourceSystem", StringType(), True),
            StructField("ValidTo", TimestampType(), True),
            StructField("RowID", StringType(), True),
            StructField("IsActive", StringType(), True),
            StructField("SourceSystemID", StringType(), True),
        ]
    )


def generate_harmonised_appeal_s78_row(**overrides):
    base = {
        "caseReference": "6000001",
        "AppealS78ID": 1,
        "caseId": None,
        "submissionId": "",
        "caseStatus": "validation",
        "caseType": "D",
        "caseProcedure": "written",
        "lpaCode": "LOAD1",
        "caseOfficerId": "",
        "inspectorId": "",
        "allocationLevel": "",
        "allocationBand": 0.0,
        "caseSpecialisms": ["specialismA"],
        "caseSubmittedDate": "",
        "caseCreatedDate": "",
        "caseUpdatedDate": "",
        "caseValidDate": "",
        "caseValidationDate": "",
        "caseValidationOutcome": "",
        "caseValidationInvalidDetails": ["caseValidationInvalidDetails"],
        "caseValidationIncompleteDetails": ["caseValidationIncompleteDetails"],
        "caseExtensionDate": "",
        "caseStartedDate": "",
        "casePublishedDate": "",
        "linkedCaseStatus": "",
        "leadCaseReference": "",
        "lpaQuestionnaireDueDate": "",
        "lpaQuestionnaireSubmittedDate": "",
        "lpaQuestionnaireCreatedDate": "",
        "lpaQuestionnairePublishedDate": "",
        "lpaQuestionnaireValidationOutcome": "",
        "lpaQuestionnaireValidationOutcomeDate": "",
        "lpaQuestionnaireValidationDetails": ["lpaQuestionnaireValidationDetails"],
        "lpaStatement": "",
        "caseWithdrawnDate": "",
        "caseTransferredDate": "",
        "transferredCaseClosedDate": "",
        "caseDecisionOutcomeDate": "",
        "caseDecisionPublishedDate": "",
        "caseDecisionOutcome": "",
        "caseCompletedDate": "",
        "enforcementNotice": True,
        "applicationReference": "",
        "applicationDate": "",
        "applicationDecision": "refused",
        "applicationDecisionDate": "",
        "applicationDecisionDueDate": "",
        "caseSubmissionDueDate": "",
        "siteAddressLine1": "",
        "siteAddressLine2": "",
        "siteAddressTown": "",
        "siteAddressCounty": "",
        "siteAddressPostcode": "",
        "siteAccessDetails": ["siteAccessDetails"],
        "siteSafetyDetails": ["siteSafetyDetails"],
        "siteAreaSquareMetres": 10.0,
        "floorSpaceSquareMetres": 5.0,
        "isCorrectAppealType": True,
        "isGreenBelt": True,
        "inConservationArea": True,
        "ownsAllLand": True,
        "ownsSomeLand": True,
        "knowsOtherOwners": "",
        "knowsAllOwners": "",
        "advertisedAppeal": True,
        "notificationMethod": ["notificationMethod"],
        "ownersInformed": True,
        "originalDevelopmentDescription": "",
        "changedDevelopmentDescription": True,
        "newConditionDetails": "",
        "extraConditionsDetails": None,
        "nearbyCaseReferences": ["nearbyCaseReferences"],
        "neighbouringSiteAddresses": [
            {
                "neighbouringSiteAddressLine1": "",
                "neighbouringSiteAddressLine2": "",
                "neighbouringSiteAddressTown": "",
                "neighbouringSiteAddressCounty": "",
                "neighbouringSiteAddressPostcode": "",
                "neighbouringSiteAccessDetails": "",
                "neighbouringSiteSafetyDetails": "",
            }
        ],
        "reasonForNeighbourVisits": "",
        "affectedListedBuildingNumbers": ["affectedListedBuildingNumbers"],
        "changedListedBuildingNumbers": [""],
        "preserveGrantLoan": True,
        "consultHistoricEngland": True,
        "appellantCostsAppliedFor": True,
        "lpaCostsAppliedFor": True,
        "agriculturalHolding": True,
        "tenantAgriculturalHolding": True,
        "otherTenantsAgriculturalHolding": True,
        "informedTenantsAgriculturalHolding": True,
        "appellantProcedurePreference": "",
        "appellantProcedurePreferenceDetails": "",
        "appellantProcedurePreferenceDuration": 0.0,
        "appellantProcedurePreferenceWitnessCount": 0.0,
        "statusPlanningObligation": "",
        "affectsScheduledMonument": True,
        "hasProtectedSpecies": True,
        "isAonbNationalLandscape": True,
        "designatedSitesNames": ["designatedSitesNames"],
        "isGypsyOrTravellerSite": True,
        "isPublicRightOfWay": True,
        "eiaEnvironmentalImpactSchedule": None,
        "eiaDevelopmentDescription": None,
        "eiaSensitiveAreaDetails": None,
        "eiaColumnTwoThreshold": True,
        "eiaScreeningOpinion": True,
        "eiaRequiresEnvironmentalStatement": True,
        "eiaCompletedEnvironmentalStatement": True,
        "hasStatutoryConsultees": True,
        "consultedBodiesDetails": "",
        "hasInfrastructureLevy": True,
        "isInfrastructureLevyFormallyAdopted": True,
        "infrastructureLevyAdoptedDate": "",
        "infrastructureLevyExpectedDate": "",
        "lpaProcedurePreference": "",
        "lpaProcedurePreferenceDetails": "",
        "lpaProcedurePreferenceDuration": 0.0,
        "caseworkReason": "",
        "importantInformation": "",
        "jurisdiction": "",
        "redeterminedIndicator": None,
        "dateCostsReportDespatched": "",
        "dateNotRecoveredOrDerecovered": "",
        "dateRecovered": "",
        "originalCaseDecisionDate": "",
        "targetDate": "",
        "appellantCommentsSubmittedDate": None,
        "appellantStatementDueDate": None,
        "appellantStatementSubmittedDate": None,
        "appellantProofsSubmittedDate": None,
        "finalCommentsDueDate": None,
        "interestedPartyRepsDueDate": None,
        "lpaCommentsSubmittedDate": None,
        "lpaProofsSubmittedDate": None,
        "lpaStatementSubmittedDate": None,
        "proofsOfEvidenceDueDate": None,
        "siteNoticesSentDate": None,
        "statementDueDate": None,
        "caseManagementConferenceDate": None,
        "numberOfResidencesNetChange": 0.0,
        "siteGridReferenceEasting": "",
        "siteGridReferenceNorthing": "",
        "siteViewableFromRoad": True,
        "siteWithinSSSI": True,
        "typeOfPlanningApplication": "householder-planning",
        "developmentType": "",
        "statementOfCommonGroundDueDate": None,
        "planningObligationDueDate": None,
        "hasLandownersPermission": True,
        "wasApplicationRefusedDueToHighwayOrTraffic": True,
        "didAppellantSubmitCompletePhotosAndPlans": True,
        "isSiteInAreaOfSpecialControlAdverts": True,
        "advertDetails": [{"advertType": "", "isAdvertInPosition": True, "isSiteOnHighwayLand": True}],
        "padsSapId": "",
        "enforcementNoticeReference": None,
        "descriptionOfAllegedBreach": None,
        "dateAppellantContactedPins": None,
        "ownerOccupancyStatus": None,
        "occupancyConditionsMet": True,
        "enforcementAppealGroundsDetails": [{"appealGroundLetter": None, "groundForAppealStartDate": None, "groundFacts": None}],
        "applicationElbAppealGroundsDetails": [{"appealGroundLetter": None, "groundForAppealStartDate": None, "groundFacts": None}],
        "applicationMadeAndFeePaid": True,
        "noticeRelatesToBuildingEngineeringMiningOther": True,
        "changeOfUseRefuseOrWaste": True,
        "changeOfUseMineralExtraction": True,
        "changeOfUseMineralStorage": True,
        "relatesToErectionOfBuildingOrBuildings": True,
        "relatesToBuildingWithAgriculturalPurpose": True,
        "relatesToBuildingSingleDwellingHouse": True,
        "previousPlanningPermissionGranted": True,
        "issueDateOfEnforcementNotice": None,
        "effectiveDateOfEnforcementNotice": None,
        "didAppellantAppealLpaDecision": True,
        "dateLpaDecisionDue": None,
        "dateLpaDecisionReceived": None,
        "areaOfAllegedBreachInSquareMetres": 0.0,
        "doesAllegedBreachCreateFloorSpace": True,
        "floorSpaceCreatedByBreachInSquareMetres": 0.0,
        "applicationPartOrWholeDevelopment": None,
        "hasPcnBeenServed": True,
        "isSiteWithin67MOfTrunkRd": True,
        "affectedTrunkRoadName": None,
        "isSiteOnCrownLand": True,
        "stopNoticeExists": True,
        "isSiteWithin400MOfMineralInterest": True,
        "isSiteWithin250MOfLandfill": True,
        "hasDevelopmentInvolvedWasteImportation": True,
        "isSiteSubjectToArticle4Direction": True,
        "article4AffectedDevelopmentRights": None,
        "pcnRestrictedDevelopmentRights": True,
        "applicationMadeUnderActSection": None,
        "siteUseAtTimeOfApplication": None,
        "appealUnderActSection": None,
        "lpaConsiderAppealInvalid": True,
        "lpaAppealInvalidReasons": None,
        "discontinuanceNoticeServedReason": None,
        "discontinuanceNoticeServedOtherReason": None,
        "wasRetrospectivePlanningApplicationMade": True,
        "reasonForAppealAppellant": None,
        "screeningOpinionIndicatesEiaRequired": True,
        "significantChangesAffectingApplicationAppellant": [{"value": None, "comment": ""}],
        "significantChangesAffectingApplicationLpa": [{"value": None, "comment": ""}],
        "migrated": "1",
        "ODTSourceSystem": "ODT",
        "SourceSystemID": "5",
        "IngestionDate": datetime(2025, 1, 1),
        "ValidTo": "",
        "RowID": "",
        "IsActive": "Y",
        "message_id": "",
        "listOfDocumentsBeforeDecision": None,
    }
    return base | overrides


def generate_harmonised_appeal_s78_schema():
    return StructType(
        [
            StructField("caseReference", StringType(), True),
            StructField("AppealS78ID", LongType(), True),
            StructField("caseId", LongType(), True),
            StructField("submissionId", StringType(), True),
            StructField("caseStatus", StringType(), True),
            StructField("caseType", StringType(), True),
            StructField("caseProcedure", StringType(), True),
            StructField("lpaCode", StringType(), True),
            StructField("caseOfficerId", StringType(), True),
            StructField("inspectorId", StringType(), True),
            StructField("allocationLevel", StringType(), True),
            StructField("allocationBand", DoubleType(), True),
            StructField("caseSpecialisms", ArrayType(StringType(), True), True),
            StructField("caseSubmittedDate", StringType(), True),
            StructField("caseCreatedDate", StringType(), True),
            StructField("caseUpdatedDate", StringType(), True),
            StructField("caseValidDate", StringType(), True),
            StructField("caseValidationDate", StringType(), True),
            StructField("caseValidationOutcome", StringType(), True),
            StructField("caseValidationInvalidDetails", ArrayType(StringType(), True), True),
            StructField("caseValidationIncompleteDetails", ArrayType(StringType(), True), True),
            StructField("caseExtensionDate", StringType(), True),
            StructField("caseStartedDate", StringType(), True),
            StructField("casePublishedDate", StringType(), True),
            StructField("linkedCaseStatus", StringType(), True),
            StructField("leadCaseReference", StringType(), True),
            StructField("lpaQuestionnaireDueDate", StringType(), True),
            StructField("lpaQuestionnaireSubmittedDate", StringType(), True),
            StructField("lpaQuestionnaireCreatedDate", StringType(), True),
            StructField("lpaQuestionnairePublishedDate", StringType(), True),
            StructField("lpaQuestionnaireValidationOutcome", StringType(), True),
            StructField("lpaQuestionnaireValidationOutcomeDate", StringType(), True),
            StructField("lpaQuestionnaireValidationDetails", ArrayType(StringType(), True), True),
            StructField("lpaStatement", StringType(), True),
            StructField("caseWithdrawnDate", StringType(), True),
            StructField("caseTransferredDate", StringType(), True),
            StructField("transferredCaseClosedDate", StringType(), True),
            StructField("caseDecisionOutcomeDate", StringType(), True),
            StructField("caseDecisionPublishedDate", StringType(), True),
            StructField("caseDecisionOutcome", StringType(), True),
            StructField("caseCompletedDate", StringType(), True),
            StructField("enforcementNotice", BooleanType(), True),
            StructField("applicationReference", StringType(), True),
            StructField("applicationDate", StringType(), True),
            StructField("applicationDecision", StringType(), True),
            StructField("applicationDecisionDate", StringType(), True),
            StructField("applicationDecisionDueDate", StringType(), True),
            StructField("caseSubmissionDueDate", StringType(), True),
            StructField("siteAddressLine1", StringType(), True),
            StructField("siteAddressLine2", StringType(), True),
            StructField("siteAddressTown", StringType(), True),
            StructField("siteAddressCounty", StringType(), True),
            StructField("siteAddressPostcode", StringType(), True),
            StructField("siteAccessDetails", ArrayType(StringType(), True), True),
            StructField("siteSafetyDetails", ArrayType(StringType(), True), True),
            StructField("siteAreaSquareMetres", DoubleType(), True),
            StructField("floorSpaceSquareMetres", DoubleType(), True),
            StructField("isCorrectAppealType", BooleanType(), True),
            StructField("isGreenBelt", BooleanType(), True),
            StructField("inConservationArea", BooleanType(), True),
            StructField("ownsAllLand", BooleanType(), True),
            StructField("ownsSomeLand", BooleanType(), True),
            StructField("knowsOtherOwners", StringType(), True),
            StructField("knowsAllOwners", StringType(), True),
            StructField("advertisedAppeal", BooleanType(), True),
            StructField("notificationMethod", ArrayType(StringType(), True), True),
            StructField("ownersInformed", BooleanType(), True),
            StructField("originalDevelopmentDescription", StringType(), True),
            StructField("changedDevelopmentDescription", BooleanType(), True),
            StructField("newConditionDetails", StringType(), True),
            StructField("extraConditionsDetails", StringType(), True),
            StructField("nearbyCaseReferences", ArrayType(StringType(), True), True),
            StructField(
                "neighbouringSiteAddresses",
                ArrayType(
                    StructType(
                        [
                            StructField("neighbouringSiteAddressLine1", StringType(), True),
                            StructField("neighbouringSiteAddressLine2", StringType(), True),
                            StructField("neighbouringSiteAddressTown", StringType(), True),
                            StructField("neighbouringSiteAddressCounty", StringType(), True),
                            StructField("neighbouringSiteAddressPostcode", StringType(), True),
                            StructField("neighbouringSiteAccessDetails", StringType(), True),
                            StructField("neighbouringSiteSafetyDetails", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("reasonForNeighbourVisits", StringType(), True),
            StructField("affectedListedBuildingNumbers", ArrayType(StringType(), True), True),
            StructField("changedListedBuildingNumbers", ArrayType(StringType(), True), True),
            StructField("preserveGrantLoan", BooleanType(), True),
            StructField("consultHistoricEngland", BooleanType(), True),
            StructField("appellantCostsAppliedFor", BooleanType(), True),
            StructField("lpaCostsAppliedFor", BooleanType(), True),
            StructField("agriculturalHolding", BooleanType(), True),
            StructField("tenantAgriculturalHolding", BooleanType(), True),
            StructField("otherTenantsAgriculturalHolding", BooleanType(), True),
            StructField("informedTenantsAgriculturalHolding", BooleanType(), True),
            StructField("appellantProcedurePreference", StringType(), True),
            StructField("appellantProcedurePreferenceDetails", StringType(), True),
            StructField("appellantProcedurePreferenceDuration", DoubleType(), True),
            StructField("appellantProcedurePreferenceWitnessCount", DoubleType(), True),
            StructField("statusPlanningObligation", StringType(), True),
            StructField("affectsScheduledMonument", BooleanType(), True),
            StructField("hasProtectedSpecies", BooleanType(), True),
            StructField("isAonbNationalLandscape", BooleanType(), True),
            StructField("designatedSitesNames", ArrayType(StringType(), True), True),
            StructField("isGypsyOrTravellerSite", BooleanType(), True),
            StructField("isPublicRightOfWay", BooleanType(), True),
            StructField("eiaEnvironmentalImpactSchedule", StringType(), True),
            StructField("eiaDevelopmentDescription", StringType(), True),
            StructField("eiaSensitiveAreaDetails", StringType(), True),
            StructField("eiaColumnTwoThreshold", BooleanType(), True),
            StructField("eiaScreeningOpinion", BooleanType(), True),
            StructField("eiaRequiresEnvironmentalStatement", BooleanType(), True),
            StructField("eiaCompletedEnvironmentalStatement", BooleanType(), True),
            StructField("hasStatutoryConsultees", BooleanType(), True),
            StructField("consultedBodiesDetails", StringType(), True),
            StructField("hasInfrastructureLevy", BooleanType(), True),
            StructField("isInfrastructureLevyFormallyAdopted", BooleanType(), True),
            StructField("infrastructureLevyAdoptedDate", StringType(), True),
            StructField("infrastructureLevyExpectedDate", StringType(), True),
            StructField("lpaProcedurePreference", StringType(), True),
            StructField("lpaProcedurePreferenceDetails", StringType(), True),
            StructField("lpaProcedurePreferenceDuration", DoubleType(), True),
            StructField("caseworkReason", StringType(), True),
            StructField("importantInformation", StringType(), True),
            StructField("jurisdiction", StringType(), True),
            StructField("redeterminedIndicator", StringType(), True),
            StructField("dateCostsReportDespatched", StringType(), True),
            StructField("dateNotRecoveredOrDerecovered", StringType(), True),
            StructField("dateRecovered", StringType(), True),
            StructField("originalCaseDecisionDate", StringType(), True),
            StructField("targetDate", StringType(), True),
            StructField("appellantCommentsSubmittedDate", StringType(), True),
            StructField("appellantStatementDueDate", StringType(), True),
            StructField("appellantStatementSubmittedDate", StringType(), True),
            StructField("appellantProofsSubmittedDate", StringType(), True),
            StructField("finalCommentsDueDate", StringType(), True),
            StructField("interestedPartyRepsDueDate", StringType(), True),
            StructField("lpaCommentsSubmittedDate", StringType(), True),
            StructField("lpaProofsSubmittedDate", StringType(), True),
            StructField("lpaStatementSubmittedDate", StringType(), True),
            StructField("proofsOfEvidenceDueDate", StringType(), True),
            StructField("siteNoticesSentDate", StringType(), True),
            StructField("statementDueDate", StringType(), True),
            StructField("caseManagementConferenceDate", StringType(), True),
            StructField("numberOfResidencesNetChange", DoubleType(), True),
            StructField("siteGridReferenceEasting", StringType(), True),
            StructField("siteGridReferenceNorthing", StringType(), True),
            StructField("siteViewableFromRoad", BooleanType(), True),
            StructField("siteWithinSSSI", BooleanType(), True),
            StructField("typeOfPlanningApplication", StringType(), True),
            StructField("developmentType", StringType(), True),
            StructField("statementOfCommonGroundDueDate", StringType(), True),
            StructField("planningObligationDueDate", StringType(), True),
            StructField("hasLandownersPermission", BooleanType(), True),
            StructField("wasApplicationRefusedDueToHighwayOrTraffic", BooleanType(), True),
            StructField("didAppellantSubmitCompletePhotosAndPlans", BooleanType(), True),
            StructField("isSiteInAreaOfSpecialControlAdverts", BooleanType(), True),
            StructField(
                "advertDetails",
                ArrayType(
                    StructType(
                        [
                            StructField("advertType", StringType(), True),
                            StructField("isAdvertInPosition", BooleanType(), True),
                            StructField("isSiteOnHighwayLand", BooleanType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("padsSapId", StringType(), True),
            StructField("enforcementNoticeReference", StringType(), True),
            StructField("descriptionOfAllegedBreach", StringType(), True),
            StructField("dateAppellantContactedPins", StringType(), True),
            StructField("ownerOccupancyStatus", StringType(), True),
            StructField("occupancyConditionsMet", BooleanType(), True),
            StructField(
                "enforcementAppealGroundsDetails",
                ArrayType(
                    StructType(
                        [
                            StructField("appealGroundLetter", StringType(), True),
                            StructField("groundForAppealStartDate", StringType(), True),
                            StructField("groundFacts", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField(
                "applicationElbAppealGroundsDetails",
                ArrayType(
                    StructType(
                        [
                            StructField("appealGroundLetter", StringType(), True),
                            StructField("groundForAppealStartDate", StringType(), True),
                            StructField("groundFacts", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("applicationMadeAndFeePaid", BooleanType(), True),
            StructField("noticeRelatesToBuildingEngineeringMiningOther", BooleanType(), True),
            StructField("changeOfUseRefuseOrWaste", BooleanType(), True),
            StructField("changeOfUseMineralExtraction", BooleanType(), True),
            StructField("changeOfUseMineralStorage", BooleanType(), True),
            StructField("relatesToErectionOfBuildingOrBuildings", BooleanType(), True),
            StructField("relatesToBuildingWithAgriculturalPurpose", BooleanType(), True),
            StructField("relatesToBuildingSingleDwellingHouse", BooleanType(), True),
            StructField("previousPlanningPermissionGranted", BooleanType(), True),
            StructField("issueDateOfEnforcementNotice", StringType(), True),
            StructField("effectiveDateOfEnforcementNotice", StringType(), True),
            StructField("didAppellantAppealLpaDecision", BooleanType(), True),
            StructField("dateLpaDecisionDue", StringType(), True),
            StructField("dateLpaDecisionReceived", StringType(), True),
            StructField("areaOfAllegedBreachInSquareMetres", DoubleType(), True),
            StructField("doesAllegedBreachCreateFloorSpace", BooleanType(), True),
            StructField("floorSpaceCreatedByBreachInSquareMetres", DoubleType(), True),
            StructField("applicationPartOrWholeDevelopment", StringType(), True),
            StructField("hasPcnBeenServed", BooleanType(), True),
            StructField("isSiteWithin67MOfTrunkRd", BooleanType(), True),
            StructField("affectedTrunkRoadName", StringType(), True),
            StructField("isSiteOnCrownLand", BooleanType(), True),
            StructField("stopNoticeExists", BooleanType(), True),
            StructField("isSiteWithin400MOfMineralInterest", BooleanType(), True),
            StructField("isSiteWithin250MOfLandfill", BooleanType(), True),
            StructField("hasDevelopmentInvolvedWasteImportation", BooleanType(), True),
            StructField("isSiteSubjectToArticle4Direction", BooleanType(), True),
            StructField("article4AffectedDevelopmentRights", StringType(), True),
            StructField("pcnRestrictedDevelopmentRights", BooleanType(), True),
            StructField("applicationMadeUnderActSection", StringType(), True),
            StructField("siteUseAtTimeOfApplication", StringType(), True),
            StructField("appealUnderActSection", StringType(), True),
            StructField("lpaConsiderAppealInvalid", BooleanType(), True),
            StructField("lpaAppealInvalidReasons", StringType(), True),
            StructField("discontinuanceNoticeServedReason", StringType(), True),
            StructField("discontinuanceNoticeServedOtherReason", StringType(), True),
            StructField("wasRetrospectivePlanningApplicationMade", BooleanType(), True),
            StructField("reasonForAppealAppellant", StringType(), True),
            StructField("screeningOpinionIndicatesEiaRequired", BooleanType(), True),
            StructField(
                "significantChangesAffectingApplicationAppellant",
                ArrayType(StructType([StructField("value", StringType(), True), StructField("comment", StringType(), True)]), True),
                True,
            ),
            StructField(
                "significantChangesAffectingApplicationLpa",
                ArrayType(StructType([StructField("value", StringType(), True), StructField("comment", StringType(), True)]), True),
                True,
            ),
            StructField("migrated", StringType(), True),
            StructField("ODTSourceSystem", StringType(), True),
            StructField("SourceSystemID", StringType(), True),
            StructField("IngestionDate", TimestampType(), True),
            StructField("ValidTo", StringType(), True),
            StructField("RowID", StringType(), True),
            StructField("IsActive", StringType(), True),
            StructField("message_id", StringType(), True),
            StructField("listOfDocumentsBeforeDecision", StringType(), True),
        ]
    )


def generate_cleaned_row(**overrides):
    base = {
        "caseId": "1",
        "caseReference": "60000001",
        "caseStatus": "validation",
        "caseType": "D",
        "caseProcedure": "written",
        "lpaCode": "A",
        "allocationLevel": "",
        "allocationBand": 0.0,
        "caseSpecialisms": ["specialismA"],
        "caseSubmittedDate": "",
        "caseCreatedDate": "",
        "caseUpdatedDate": "",
        "caseValidDate": "",
        "caseValidationDate": "",
        "caseValidationOutcome": "",
        "caseValidationInvalidDetails": ["caseValidationInvalidDetails"],
        "caseValidationIncompleteDetails": ["caseValidationIncompleteDetails"],
        "caseExtensionDate": "",
        "caseStartedDate": "",
        "casePublishedDate": "",
        "linkedCaseStatus": "",
        "leadCaseReference": "",
        "caseWithdrawnDate": "",
        "caseTransferredDate": "",
        "transferredCaseClosedDate": "",
        "caseDecisionOutcomeDate": "",
        "caseDecisionPublishedDate": "",
        "caseDecisionOutcome": "",
        "caseCompletedDate": "",
        "enforcementNotice": True,
        "applicationReference": "UNKNOWN",
        "applicationDate": "",
        "applicationDecision": "refused",
        "lpaDecisionDate": "",
        "caseSubmissionDueDate": "",
        "siteAddressLine1": "",
        "siteAddressLine2": "",
        "siteAddressTown": "",
        "siteAddressCounty": "",
        "siteAddressPostcode": "",
        "isCorrectAppealType": True,
        "originalDevelopmentDescription": "",
        "changedDevelopmentDescription": True,
        "newConditionDetails": "",
        "nearbyCaseReferences": ["nearbyCaseReferences"],
        "neighbouringSiteAddresses": [
            {
                "neighbouringSiteAddressCounty": "",
                "neighbouringSiteAddressLine1": "",
                "neighbouringSiteSafetyDetails": "",
                "neighbouringSiteAccessDetails": "",
                "neighbouringSiteAddressTown": "",
                "neighbouringSiteAddressPostcode": "",
                "neighbouringSiteAddressLine2": "",
            }
        ],
        "affectedListedBuildingNumbers": ["affectedListedBuildingNumbers"],
        "appellantCostsAppliedFor": True,
        "lpaCostsAppliedFor": True,
        "appellantName": "A B",
        "inspectorName": "A X",
    }
    return base | overrides


def generate_cleaned_schema():
    return StructType(
        [
            StructField("caseId", LongType(), True),
            StructField("caseReference", StringType(), True),
            StructField("caseStatus", StringType(), True),
            StructField("caseType", StringType(), True),
            StructField("caseProcedure", StringType(), True),
            StructField("lpaCode", StringType(), True),
            StructField("lpaName", StringType(), True),
            StructField("allocationLevel", StringType(), True),
            StructField("allocationBand", DoubleType(), True),
            StructField("caseSpecialisms", ArrayType(StringType(), True), True),
            StructField("caseSubmittedDate", StringType(), True),
            StructField("caseCreatedDate", StringType(), True),
            StructField("caseUpdatedDate", StringType(), True),
            StructField("caseValidDate", StringType(), True),
            StructField("caseValidationDate", StringType(), True),
            StructField("caseValidationOutcome", StringType(), True),
            StructField("caseValidationInvalidDetails", ArrayType(StringType(), True), True),
            StructField("caseValidationIncompleteDetails", ArrayType(StringType(), True), True),
            StructField("caseExtensionDate", StringType(), True),
            StructField("caseStartedDate", StringType(), True),
            StructField("casePublishedDate", StringType(), True),
            StructField("linkedCaseStatus", StringType(), True),
            StructField("leadCaseReference", StringType(), True),
            StructField("caseWithdrawnDate", StringType(), True),
            StructField("caseTransferredDate", StringType(), True),
            StructField("transferredCaseClosedDate", StringType(), True),
            StructField("caseDecisionOutcomeDate", StringType(), True),
            StructField("caseDecisionPublishedDate", StringType(), True),
            StructField("caseDecisionOutcome", StringType(), True),
            StructField("caseCompletedDate", StringType(), True),
            StructField("enforcementNotice", BooleanType(), True),
            StructField("applicationReference", StringType(), True),
            StructField("applicationDate", StringType(), True),
            StructField("applicationDecision", StringType(), True),
            StructField("lpaDecisionDate", StringType(), True),
            StructField("caseSubmissionDueDate", StringType(), True),
            StructField("siteAddressLine1", StringType(), True),
            StructField("siteAddressLine2", StringType(), True),
            StructField("siteAddressTown", StringType(), True),
            StructField("siteAddressCounty", StringType(), True),
            StructField("siteAddressPostcode", StringType(), True),
            StructField("isCorrectAppealType", BooleanType(), True),
            StructField("originalDevelopmentDescription", StringType(), True),
            StructField("changedDevelopmentDescription", BooleanType(), True),
            StructField("newConditionDetails", StringType(), True),
            StructField("nearbyCaseReferences", ArrayType(StringType(), True), True),
            StructField(
                "neighbouringSiteAddresses",
                ArrayType(
                    StructType(
                        [
                            StructField("neighbouringSiteAddressLine1", StringType(), True),
                            StructField("neighbouringSiteAddressLine2", StringType(), True),
                            StructField("neighbouringSiteAddressTown", StringType(), True),
                            StructField("neighbouringSiteAddressCounty", StringType(), True),
                            StructField("neighbouringSiteAddressPostcode", StringType(), True),
                            StructField("neighbouringSiteAccessDetails", StringType(), True),
                            StructField("neighbouringSiteSafetyDetails", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("affectedListedBuildingNumbers", ArrayType(StringType(), True), True),
            StructField("appellantCostsAppliedFor", BooleanType(), True),
            StructField("lpaCostsAppliedFor", BooleanType(), True),
            StructField("appellantName", StringType(), True),
            StructField("typeOfEvent", StringType(), True),
            StructField("startDateOfTheEvent", StringType(), True),
            StructField("inspectorName", StringType(), True),
            StructField("caseOfficerName", StringType(), True),
            StructField("inspectorQualifications", StringType(), True),
        ]
    )


class TestDartApiCuratedProcess(ETLTestCase):
    def assert_etl_process(self, test_case: str):
        spark = PytestSparkSessionUtil().get_spark_session()
        appeal_has = spark.createDataFrame(
            (
                generate_harmonised_appeal_has_row(caseId=1, lpaCode="A", caseReference=60000001, inspectorId="insId1", caseOfficerId="insId7"),
                generate_harmonised_appeal_has_row(caseId=2, lpaCode="B", caseReference=60000002, inspectorId="insId2", caseOfficerId="insId6"),
                generate_harmonised_appeal_has_row(caseId=3, lpaCode="C", caseReference=60000003, inspectorId="insId3", caseOfficerId="insId5"),
                generate_harmonised_appeal_has_row(
                    caseId=4, lpaCode="D", caseReference=60000004, inspectorId="insId4", caseOfficerId="insId4"
                ),  # For the dropped pins_lpa row
                generate_harmonised_appeal_has_row(
                    caseId=5, lpaCode="E", caseReference=60000005, inspectorId="insId5", caseOfficerId="insId3"
                ),  # For the dropped service_user row
            ),
            schema=generate_harmonised_appeal_has_schema(),
        )
        appeal_has_table = f"{test_case}_appeal_has"
        self.write_existing_table(
            spark,
            appeal_has,
            appeal_has_table,
            "odw_harmonised_db",
            "odw-harmonised",
            appeal_has_table,
            "overwrite",
        )
        appeal_s78 = spark.createDataFrame(
            (
                generate_harmonised_appeal_s78_row(
                    caseId=6, lpaCode="F", caseReference=60000006, inspectorId="insId6", caseOfficerId="insId2"
                ),  # For the dropped service_user row
                generate_harmonised_appeal_s78_row(
                    caseId=7, lpaCode="G", caseReference=60000007, inspectorId="insId7", caseOfficerId="insId1"
                ),  # For the dropped appeal_event row
                generate_harmonised_appeal_s78_row(
                    caseId=8, lpaCode="H", caseReference=60000008, inspectorId="insId10", caseOfficerId="insId7"
                ),  # For the dropped entraid_ins row
                generate_harmonised_appeal_s78_row(
                    caseId=9, lpaCode="I", caseReference=60000009, inspectorId="insId7", caseOfficerId="insId10"
                ),  # For the dropped entraid_co row
            ),
            schema=generate_harmonised_appeal_s78_schema(),
        )
        appeal_s78_table = f"{test_case}_appeal_s78"
        self.write_existing_table(
            spark,
            appeal_s78,
            appeal_s78_table,
            "odw_harmonised_db",
            "odw-harmonised",
            appeal_s78_table,
            "overwrite",
        )
        pins_lpa = spark.createDataFrame(
            (
                generate_harmonised_pins_lpa_row(id=1, pinsLpaCode="A", caseReference=60000001),
                generate_harmonised_pins_lpa_row(id=2, pinsLpaCode="B", caseReference=60000002),
                generate_harmonised_pins_lpa_row(id=3, pinsLpaCode="C", caseReference=60000003),
                generate_harmonised_pins_lpa_row(id=3, pinsLpaCode="C", caseReference=60000004, isActive="N"),  # Should be dropped
            ),
            schema=generate_harmonised_pins_lpa_schema(),
        )
        pins_lpa_table = f"{test_case}_pins_lpa"
        self.write_existing_table(
            spark,
            pins_lpa,
            pins_lpa_table,
            "odw_harmonised_db",
            "odw-harmonised",
            pins_lpa_table,
            "overwrite",
        )
        sb_service_user = spark.createDataFrame(
            (
                generate_harmonised_sb_service_user_row(LPAId=1, firstName="A", caseReference=60000001, serviceUserType="Appellant", lastName="B"),
                generate_harmonised_sb_service_user_row(LPAId=2, firstName="B", caseReference=60000002, serviceUserType="Appellant"),
                generate_harmonised_sb_service_user_row(LPAId=3, firstName="C", caseReference=60000003, serviceUserType="Appellant"),
                generate_harmonised_sb_service_user_row(
                    LPAId=4, firstName="D", caseReference=60000005, serviceUserType="Something else"
                ),  # Should be dropped
                generate_harmonised_sb_service_user_row(LPAId=5, firstName="E", caseReference=60000006, isActive="N"),  # Should be dropped
            ),
            schema=generate_harmonised_sb_service_user_schema(),
        )
        sb_service_user_table = f"{test_case}_sb_service_user"
        self.write_existing_table(
            spark,
            sb_service_user,
            sb_service_user_table,
            "odw_harmonised_db",
            "odw-harmonised",
            sb_service_user_table,
            "overwrite",
        )
        sb_appeal_event = spark.createDataFrame(
            (
                generate_harmonised_sb_appeal_event_row(eventId="1", caseReference=60000001),
                generate_harmonised_sb_appeal_event_row(eventId="2", caseReference=60000002),
                generate_harmonised_sb_appeal_event_row(eventId="3", caseReference=60000003),
                generate_harmonised_sb_appeal_event_row(eventId="4", caseReference=60000004),  # Should be dropped
            ),
            schema=generate_harmonised_sb_appeal_event_schema(),
        )
        sb_appeal_event_table = f"{test_case}_sb_appeal_event"
        self.write_existing_table(
            spark,
            sb_appeal_event,
            sb_appeal_event_table,
            "odw_harmonised_db",
            "odw-harmonised",
            sb_appeal_event_table,
            "overwrite",
        )
        entraid = spark.createDataFrame(
            (
                generate_harmonised_entraid_row(
                    EmployeeEntraId=1, givenName="A", surname="X", id="insId1", userPrincipalName="x@pins.gov.uk"
                ),  # ent_ins
                generate_harmonised_entraid_row(
                    EmployeeEntraId=2, givenName="B", surname="Y", id="insId2", userPrincipalName="y@pins.gov.uk"
                ),  # ent_ins
                generate_harmonised_entraid_row(
                    EmployeeEntraId=3, givenName="C", surname="Z", id="insId3", userPrincipalName="z@pins.gov.uk"
                ),  # ent_co
                generate_harmonised_entraid_row(EmployeeEntraId=10, givenName="Z", surname="AA", id="insId10", isActive="N"),  # Should be dropped
            ),
            schema=generate_harmonised_entraid_schema(),
        )
        entraid_table = f"{test_case}_entraid"
        self.write_existing_table(
            spark,
            entraid,
            entraid_table,
            "odw_harmonised_db",
            "odw-harmonised",
            entraid_table,
            "overwrite",
        )
        horizon_pins_inspector = spark.createDataFrame(
            (
                generate_harmonised_horizon_pins_inspector_row(horizonId="1", firstName="A", lastName="D", email="x@pins.gov.uk"),
                generate_harmonised_horizon_pins_inspector_row(horizonId="2", firstName="B", lastName="E", email="y@pins.gov.uk"),
                generate_harmonised_horizon_pins_inspector_row(horizonId="3", firstName="C", lastName="F", email="z@pins.gov.uk"),
                generate_harmonised_horizon_pins_inspector_row(horizonId="4", firstName="D", lastName="G", email="a@pins.gov.uk", isActive="Y"),
            ),
            schema=generate_harmonised_horizon_pins_inspector_schema(),
        )
        horizon_pins_inspector_table = f"{test_case}_horizon_pins_inspector"
        self.write_existing_table(
            spark,
            horizon_pins_inspector,
            horizon_pins_inspector_table,
            "odw_harmonised_db",
            "odw-harmonised",
            horizon_pins_inspector_table,
            "overwrite",
        )
        expected_curated_data_after_writing = spark.createDataFrame(
            (
                generate_cleaned_row(
                    caseId=1, caseReference="60000001", lpaCode="A", applicationReference="UNKNOWN", appellantName="A B", inspectorName="A X"
                ),
                generate_cleaned_row(caseId=2, caseReference="60000002", lpaCode="B", applicationReference="UNKNOWN", inspectorName="B Y"),
                generate_cleaned_row(caseId=3, caseReference="60000003", lpaCode="C", applicationReference="UNKNOWN", inspectorName="C Z"),
                generate_cleaned_row(
                    caseId=4,
                    caseReference="60000004",
                    lpaCode="D",
                    applicationReference="UNKNOWN",
                ),
                generate_cleaned_row(caseId=5, caseReference="60000005", lpaCode="E", applicationReference="UNKNOWN", caseOfficerName="C Z"),
                generate_cleaned_row(caseId=6, caseReference="60000006", lpaCode="F", applicationReference="UNKNOWN", caseOfficerName="B Y"),
                generate_cleaned_row(caseId=7, caseReference="60000007", lpaCode="G", applicationReference="UNKNOWN", caseOfficerName="A X"),
                generate_cleaned_row(caseId=8, caseReference="60000008", lpaCode="H", applicationReference="UNKNOWN", inspectorName="Z AA"),
                generate_cleaned_row(caseId=9, caseReference="60000009", lpaCode="I", applicationReference="UNKNOWN", caseOfficerName="Z AA"),
            ),
            schema=generate_cleaned_schema(),
        )
        expected_curated_table = f"{test_case}_dart_api"
        with (
            mock.patch.object(DartApiCuratedProcess, "__init__", return_value=None),
            mock.patch.object(DartApiCuratedProcess, "HARMONISED_APPEAL_HAS", appeal_has_table),
            mock.patch.object(DartApiCuratedProcess, "HARMONISED_PINS_LPA", pins_lpa_table),
            mock.patch.object(DartApiCuratedProcess, "HARMONISED_SB_SERVICE_USER", sb_service_user_table),
            mock.patch.object(DartApiCuratedProcess, "HARMONISED_SB_APPEAL_EVENT", sb_appeal_event_table),
            mock.patch.object(DartApiCuratedProcess, "HARMONISED_ENTRAID", entraid_table),
            mock.patch.object(DartApiCuratedProcess, "HARMONISED_PINS_INSPECTOR", horizon_pins_inspector_table),
            mock.patch.object(DartApiCuratedProcess, "HARMONISED_APPEAL_S78", appeal_s78_table),
            mock.patch.object(DartApiCuratedProcess, "OUTPUT_TABLE", expected_curated_table),
        ):
            inst = DartApiCuratedProcess(spark)
            result = inst.run()
            assert_etl_result_successful(result)
            actual_table_data = spark.table(f"odw_curated_db.{expected_curated_table}")
            assert_dataframes_equal(expected_curated_data_after_writing, actual_table_data)

    def test__dart_api_curation_process__run__with_no_existing_data(self):
        """
        - Given I have existing appeals data in the harmonised layer
        - When I call DartApiCuratedProcess.run
        - Then the `dart_api` table should be created
        """
        self.assert_etl_process("t_dacp_r_wned")

    def test__dart_api_curation_process__run__withexisting_data(self):
        """
        - Given I have existing appeals data in the harmonised layer with an existing curated dart api table
        - When I call DartApiCuratedProcess.run
        - Then the `dart_api` table should be created which overwrites the existing data
        """
        test_case = "t_dacp_r_wed"
        spark = PytestSparkSessionUtil().get_spark_session()
        dart_api = spark.createDataFrame([], generate_cleaned_schema())
        dart_api_table = f"{test_case}_dart_api"
        self.write_existing_table(
            spark,
            dart_api,
            dart_api_table,
            "odw_curated_db",
            "odw-curated",
            dart_api_table,
            "overwrite",
        )
        self.assert_etl_process(test_case)
