from odw.core.etl.transformation.harmonised.nsip_s51_advice_harmonisation_process import (
    NsipS51AdviceHarmonisationProcess,
)
from odw.test.util.test_case import SparkTestCase
from odw.test.util.session_util import PytestSparkSessionUtil
from odw.test.util.assertion import assert_dataframes_equal
import pyspark.sql.types as T
from pyspark.sql import DataFrame


def compare_data(expected: DataFrame, actual: DataFrame):
    uncomparable_cols = ["RowID"]
    expected_cleaned = expected.drop(*uncomparable_cols)
    actual_cleaned = actual.drop(*uncomparable_cols)
    assert_dataframes_equal(expected_cleaned, actual_cleaned)


class TestNSIPS51AdviceHarmonisationProcess(SparkTestCase):
    def test__nsip_s51_advice_harmonisation_process__process__aggregates_attachments_and_applies_delete_logic(
        self,
    ):
        spark = PytestSparkSessionUtil().get_spark_session()

        service_bus_data = spark.createDataFrame(
            [
                (
                    1,
                    10,
                    "ADV-10",
                    100,
                    "EN010001",
                    "Title 10",
                    None,
                    "From 10",
                    "Agent 10",
                    "email",
                    "2025-01-01",
                    "Enquiry 10",
                    None,
                    "Advice By 10",
                    "2025-01-02",
                    "Advice 10",
                    None,
                    "Published",
                    None,
                    ["SBA1"],
                    "Yes",
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    "1",
                    "ODT",
                    "SRC1",
                    "2025-01-01 00:00:00",
                    None,
                    "",
                    "Y",
                ),
            ],
            T.StructType(
                [
                    T.StructField("NSIPAdviceID", T.IntegerType(), True),
                    T.StructField("adviceId", T.IntegerType(), True),
                    T.StructField("adviceReference", T.StringType(), True),
                    T.StructField("caseId", T.IntegerType(), True),
                    T.StructField("caseReference", T.StringType(), True),
                    T.StructField("title", T.StringType(), True),
                    T.StructField("titleWelsh", T.StringType(), True),
                    T.StructField("from", T.StringType(), True),
                    T.StructField("agent", T.StringType(), True),
                    T.StructField("method", T.StringType(), True),
                    T.StructField("enquiryDate", T.StringType(), True),
                    T.StructField("enquiryDetails", T.StringType(), True),
                    T.StructField("enquiryDetailsWelsh", T.StringType(), True),
                    T.StructField("adviceGivenBy", T.StringType(), True),
                    T.StructField("adviceDate", T.StringType(), True),
                    T.StructField("adviceDetails", T.StringType(), True),
                    T.StructField("adviceDetailsWelsh", T.StringType(), True),
                    T.StructField("status", T.StringType(), True),
                    T.StructField("redactionStatus", T.StringType(), True),
                    T.StructField("attachmentIds", T.ArrayType(T.StringType()), True),
                    T.StructField("Section51Advice", T.StringType(), True),
                    T.StructField("EnquirerFirstName", T.StringType(), True),
                    T.StructField("EnquirerLastName", T.StringType(), True),
                    T.StructField("AdviceLastModified", T.StringType(), True),
                    T.StructField("AttachmentCount", T.StringType(), True),
                    T.StructField("AttachmentsLastModified", T.StringType(), True),
                    T.StructField("LastPublishedDate", T.StringType(), True),
                    T.StructField("WelshLanguage", T.StringType(), True),
                    T.StructField("CaseWorkType", T.StringType(), True),
                    T.StructField("AttachmentModifyDate", T.StringType(), True),
                    T.StructField("Migrated", T.StringType(), True),
                    T.StructField("ODTSourceSystem", T.StringType(), True),
                    T.StructField("SourceSystemID", T.StringType(), True),
                    T.StructField("IngestionDate", T.StringType(), True),
                    T.StructField("ValidTo", T.StringType(), True),
                    T.StructField("RowID", T.StringType(), True),
                    T.StructField("IsActive", T.StringType(), True),
                ]
            ),
        )

        horizon_data = spark.createDataFrame(
            [
                (
                    20,
                    20,
                    "ADV-20",
                    200,
                    "EN010002",
                    "Title 20",
                    None,
                    "From 20",
                    "Agent 20",
                    "email",
                    "2025-02-01",
                    "Enquiry 20",
                    None,
                    "Advice By 20",
                    "2025-02-02",
                    "Advice 20",
                    None,
                    "Published",
                    None,
                    "HA2",
                    "Yes",
                    "A",
                    "B",
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    "0",
                    "Horizon",
                    None,
                    "2025-02-01 00:00:00",
                    None,
                    "",
                    "Y",
                ),
                (
                    20,
                    20,
                    "ADV-20",
                    200,
                    "EN010002",
                    "Title 20",
                    None,
                    "From 20",
                    "Agent 20",
                    "email",
                    "2025-02-01",
                    "Enquiry 20",
                    None,
                    "Advice By 20",
                    "2025-02-02",
                    "Advice 20",
                    None,
                    "Published",
                    None,
                    "HA1",
                    "Yes",
                    "A",
                    "B",
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    "0",
                    "Horizon",
                    None,
                    "2025-02-01 00:00:00",
                    None,
                    "",
                    "Y",
                ),
            ],
            T.StructType(
                [
                    T.StructField("NSIPAdviceID", T.IntegerType(), True),
                    T.StructField("adviceId", T.IntegerType(), True),
                    T.StructField("adviceReference", T.StringType(), True),
                    T.StructField("caseId", T.IntegerType(), True),
                    T.StructField("caseReference", T.StringType(), True),
                    T.StructField("title", T.StringType(), True),
                    T.StructField("titleWelsh", T.StringType(), True),
                    T.StructField("from", T.StringType(), True),
                    T.StructField("agent", T.StringType(), True),
                    T.StructField("method", T.StringType(), True),
                    T.StructField("enquiryDate", T.StringType(), True),
                    T.StructField("enquiryDetails", T.StringType(), True),
                    T.StructField("enquiryDetailsWelsh", T.StringType(), True),
                    T.StructField("adviceGivenBy", T.StringType(), True),
                    T.StructField("adviceDate", T.StringType(), True),
                    T.StructField("adviceDetails", T.StringType(), True),
                    T.StructField("adviceDetailsWelsh", T.StringType(), True),
                    T.StructField("status", T.StringType(), True),
                    T.StructField("redactionStatus", T.StringType(), True),
                    T.StructField("attachmentIds", T.StringType(), True),
                    T.StructField("Section51Advice", T.StringType(), True),
                    T.StructField("EnquirerFirstName", T.StringType(), True),
                    T.StructField("EnquirerLastName", T.StringType(), True),
                    T.StructField("AdviceLastModified", T.StringType(), True),
                    T.StructField("AttachmentCount", T.StringType(), True),
                    T.StructField("AttachmentsLastModified", T.StringType(), True),
                    T.StructField("LastPublishedDate", T.StringType(), True),
                    T.StructField("WelshLanguage", T.StringType(), True),
                    T.StructField("CaseWorkType", T.StringType(), True),
                    T.StructField("AttachmentModifyDate", T.StringType(), True),
                    T.StructField("Migrated", T.StringType(), True),
                    T.StructField("ODTSourceSystem", T.StringType(), True),
                    T.StructField("SourceSystemID", T.StringType(), True),
                    T.StructField("IngestionDate", T.StringType(), True),
                    T.StructField("ValidTo", T.StringType(), True),
                    T.StructField("RowID", T.StringType(), True),
                    T.StructField("IsActive", T.StringType(), True),
                ]
            ),
        )

        horizon_deleted = spark.createDataFrame(
            [(20,)],
            ["advicenodeid"],
        )

        sb_advice_ids = spark.createDataFrame(
            [(10,)],
            ["adviceId"],
        )
        expected_df = spark.createDataFrame(
            (
                {
                    "NSIPAdviceID": 1,
                    "adviceId": 10,
                    "adviceReference": "ADV-10",
                    "caseId": 100,
                    "caseReference": "EN010001",
                    "title": "Title 10",
                    "titleWelsh": None,
                    "from": "From 10",
                    "agent": "Agent 10",
                    "method": "email",
                    "enquiryDate": "2025-01-01",
                    "enquiryDetails": "Enquiry 10",
                    "enquiryDetailsWelsh": None,
                    "adviceGivenBy": "Advice By 10",
                    "adviceDate": "2025-01-02",
                    "adviceDetails": "Advice 10",
                    "adviceDetailsWelsh": None,
                    "status": "Published",
                    "redactionStatus": None,
                    "attachmentIds": ["SBA1"],
                    "Section51Advice": "Yes",
                    "EnquirerFirstName": None,
                    "EnquirerLastName": None,
                    "AdviceLastModified": None,
                    "AttachmentCount": None,
                    "AttachmentsLastModified": None,
                    "LastPublishedDate": None,
                    "WelshLanguage": None,
                    "CaseWorkType": None,
                    "Migrated": "1",
                    "ODTSourceSystem": "ODT",
                    "IngestionDate": "2025-01-01 00:00:00",
                    "ValidTo": None,
                    "RowID": "9ef7a4435a50df0cd6c38de84c26dcd2",
                    "IsActive": "Y",
                },
                {
                    "NSIPAdviceID": 2,
                    "adviceId": 20,
                    "adviceReference": "ADV-20",
                    "caseId": 200,
                    "caseReference": "EN010002",
                    "title": "Title 20",
                    "titleWelsh": None,
                    "from": "From 20",
                    "agent": "Agent 20",
                    "method": "email",
                    "enquiryDate": "2025-02-01",
                    "enquiryDetails": "Enquiry 20",
                    "enquiryDetailsWelsh": None,
                    "adviceGivenBy": "Advice By 20",
                    "adviceDate": "2025-02-02",
                    "adviceDetails": "Advice 20",
                    "adviceDetailsWelsh": None,
                    "status": "Published",
                    "redactionStatus": None,
                    "attachmentIds": ["HA1", "HA2"],
                    "Section51Advice": "Yes",
                    "EnquirerFirstName": "A",
                    "EnquirerLastName": "B",
                    "AdviceLastModified": None,
                    "AttachmentCount": None,
                    "AttachmentsLastModified": None,
                    "LastPublishedDate": None,
                    "WelshLanguage": None,
                    "CaseWorkType": None,
                    "Migrated": "0",
                    "ODTSourceSystem": "Horizon",
                    "IngestionDate": "2025-02-01 00:00:00",
                    "ValidTo": "2025-02-02 00:00:00",
                    "RowID": "69763bbee120cb58a0c7bfb77a233f96",
                    "IsActive": "N",
                },
                {
                    "NSIPAdviceID": 3,
                    "adviceId": 20,
                    "adviceReference": "ADV-20",
                    "caseId": 200,
                    "caseReference": "EN010002",
                    "title": "Title 20",
                    "titleWelsh": None,
                    "from": "From 20",
                    "agent": "Agent 20",
                    "method": "email",
                    "enquiryDate": "2025-02-01",
                    "enquiryDetails": "Enquiry 20",
                    "enquiryDetailsWelsh": None,
                    "adviceGivenBy": "Advice By 20",
                    "adviceDate": "2025-02-02",
                    "adviceDetails": "Advice 20",
                    "adviceDetailsWelsh": None,
                    "status": "Published",
                    "redactionStatus": None,
                    "attachmentIds": ["HA1", "HA2"],
                    "Section51Advice": "Yes",
                    "EnquirerFirstName": "A",
                    "EnquirerLastName": "B",
                    "AdviceLastModified": None,
                    "AttachmentCount": None,
                    "AttachmentsLastModified": None,
                    "LastPublishedDate": None,
                    "WelshLanguage": None,
                    "CaseWorkType": None,
                    "Migrated": "0",
                    "ODTSourceSystem": "Horizon",
                    "IngestionDate": "2025-02-01 00:00:00",
                    "ValidTo": "2025-02-01 00:00:00",
                    "RowID": "69763bbee120cb58a0c7bfb77a233f96",
                    "IsActive": "N",
                },
            ),
            schema=T.StructType(
                [
                    T.StructField("NSIPAdviceID", T.IntegerType(), False),
                    T.StructField("adviceId", T.IntegerType(), True),
                    T.StructField("adviceReference", T.StringType(), True),
                    T.StructField("caseId", T.IntegerType(), True),
                    T.StructField("caseReference", T.StringType(), True),
                    T.StructField("title", T.StringType(), True),
                    T.StructField("titleWelsh", T.StringType(), True),
                    T.StructField("from", T.StringType(), True),
                    T.StructField("agent", T.StringType(), True),
                    T.StructField("method", T.StringType(), True),
                    T.StructField("enquiryDate", T.StringType(), True),
                    T.StructField("enquiryDetails", T.StringType(), True),
                    T.StructField("enquiryDetailsWelsh", T.StringType(), True),
                    T.StructField("adviceGivenBy", T.StringType(), True),
                    T.StructField("adviceDate", T.StringType(), True),
                    T.StructField("adviceDetails", T.StringType(), True),
                    T.StructField("adviceDetailsWelsh", T.StringType(), True),
                    T.StructField("status", T.StringType(), True),
                    T.StructField("redactionStatus", T.StringType(), True),
                    T.StructField("attachmentIds", T.ArrayType(T.StringType(), True), True),
                    T.StructField("Section51Advice", T.StringType(), True),
                    T.StructField("EnquirerFirstName", T.StringType(), True),
                    T.StructField("EnquirerLastName", T.StringType(), True),
                    T.StructField("AdviceLastModified", T.StringType(), True),
                    T.StructField("AttachmentCount", T.StringType(), True),
                    T.StructField("AttachmentsLastModified", T.StringType(), True),
                    T.StructField("LastPublishedDate", T.StringType(), True),
                    T.StructField("WelshLanguage", T.StringType(), True),
                    T.StructField("CaseWorkType", T.StringType(), True),
                    T.StructField("Migrated", T.StringType(), False),
                    T.StructField("ODTSourceSystem", T.StringType(), True),
                    T.StructField("IngestionDate", T.StringType(), True),
                    T.StructField("ValidTo", T.StringType(), True),
                    T.StructField("RowID", T.StringType(), False),
                    T.StructField("IsActive", T.StringType(), False),
                ]
            ),
        )
        inst = NsipS51AdviceHarmonisationProcess(spark)
        data_to_write, result = inst.process(
            source_data={
                "service_bus_data": service_bus_data,
                "horizon_data": horizon_data,
                "horizon_deleted": horizon_deleted,
                "sb_advice_ids": sb_advice_ids,
            }
        )

        write_entry_key = f"odw_harmonised_db.{inst.OUTPUT_TABLE}"

        actual_df = data_to_write[write_entry_key]["data"]
        compare_data(expected_df, actual_df)
        assert result.metadata.insert_count == 3
