parameters:
  agentPool: ''
  env: ''

##
# Run ODW Package unit tests
##
jobs:
- job: RunODWPackageUnitTestsJob
  pool: ${{ parameters.agentPool }}
  steps:
  - checkout: self
    clean: true
  - template: ${{variables['System.DefaultWorkingDirectory']}}/pipelines/steps/azure-login.yaml@odw-common
  - script: |
      python3 -m pip install .
      python3 -m pip install .[test]
    displayName: 'install requirements'
  - script: |
      export PATH="$PATH:/home/AzDevOps/.local/bin/"
      python3 -m pytest $(Build.SourcesDirectory)/odw/test/unit_test -vv -rP -n 2 --dist loadscope
    displayName: 'pytest'
