parameters:
  agentPool: ''
  env: ''
  coverageThreshold: 1 #75  # This needs to be increased, this is set to the current unit test coverage percentage

##
# Run ODW Package unit tests
##
jobs:
- job: RunODWPackageUnitTestsJob
  pool: ${{ parameters.agentPool }}
  steps:
  - checkout: self
    clean: true
  - template: ${{variables['System.DefaultWorkingDirectory']}}/pipelines/steps/azure-login.yaml@odw-common
  - script: |
      python3 -m pip install .
      python3 -m pip install .[test]
    displayName: 'install requirements'
  - script: |
      set -e
      cd $(System.DefaultWorkingDirectory)
      export PATH="$PATH:/home/AzDevOps/.local/bin/"
      python3 -m pytest $(Build.SourcesDirectory)/odw/test/unit_test -vv -rP -n 2 --dist loadscope --junitxml=junit/unit_test_results.xml --cov="odw/core" --cov-report=
      python3 -m coverage report --fail-under=${{ parameters.coverageThreshold }} --show-missing
      mv .coverage .coverage.unit
    displayName: 'pytest'
  - task: PublishPipelineArtifact@1
    displayName: 'Upload unit test coverage report'
    inputs:
      targetPath: '.coverage.unit'
