parameters:
  agentPool: ''
  env: ''

##
# Run ODW Package integration tests
##
jobs:
- job: RunODWPackageIntegrationTestsJob
  pool: ${{ parameters.agentPool }}
  steps:
  - checkout: self
    clean: true
  - template: ${{variables['System.DefaultWorkingDirectory']}}/pipelines/steps/azure-login.yaml@odw-common
  - script: |
      python3 -m pip install .
      python3 -m pip install .[test]
    displayName: 'install requirements'
  - script: |
      set -e
      export PATH="$PATH:/home/AzDevOps/.local/bin/"
      rm /tmp/spark-*
      rm /tmp/blockmgr-*
      python3 -m pytest $(Build.SourcesDirectory)/odw/test/integration_test -vv -n 4 --durations=0
    displayName: 'pytest'
