import mock
from pyspark.sql.types import IntegerType, LongType, StringType, StructField, StructType, TimestampType, DoubleType, ArrayType, BooleanType
from odw.core.etl.transformation.harmonised.appeal_s78_harmonisation_process import AppealS78HarmonisationProcess
from odw.test.util.session_util import PytestSparkSessionUtil
from odw.test.integration_test.etl.etl_test_case import ETLTestCase
from odw.test.util.assertion import assert_dataframes_equal, assert_etl_result_successful
from datetime import datetime
import pytest


pytestmark = pytest.mark.xfail(reason="Harmonisation logic not implemented yet")


def _raw_service_bus_schema():
    return StructType(
        [
            StructField("AppealS78ID", LongType(), True),
            StructField("caseId", LongType(), True),
            StructField("caseReference", StringType(), True),
            StructField("submissionId", StringType(), True),
            StructField("caseStatus", StringType(), True),
            StructField("caseType", StringType(), True),
            StructField("caseProcedure", StringType(), True),
            StructField("lpaCode", StringType(), True),
            StructField("caseOfficerId", StringType(), True),
            StructField("inspectorId", StringType(), True),
            StructField("allocationLevel", StringType(), True),
            StructField("allocationBand", DoubleType(), True),
            StructField("caseSpecialisms", ArrayType(StringType(), True), True),
            StructField("caseSubmittedDate", StringType(), True),
            StructField("caseCreatedDate", StringType(), True),
            StructField("caseUpdatedDate", StringType(), True),
            StructField("caseValidDate", StringType(), True),
            StructField("caseValidationDate", StringType(), True),
            StructField("caseValidationOutcome", StringType(), True),
            StructField("caseValidationInvalidDetails", ArrayType(StringType(), True), True),
            StructField("caseValidationIncompleteDetails", ArrayType(StringType(), True), True),
            StructField("caseExtensionDate", StringType(), True),
            StructField("caseStartedDate", StringType(), True),
            StructField("casePublishedDate", StringType(), True),
            StructField("linkedCaseStatus", StringType(), True),
            StructField("leadCaseReference", StringType(), True),
            StructField("lpaQuestionnaireDueDate", StringType(), True),
            StructField("lpaQuestionnaireSubmittedDate", StringType(), True),
            StructField("lpaQuestionnaireCreatedDate", StringType(), True),
            StructField("lpaQuestionnairePublishedDate", StringType(), True),
            StructField("lpaQuestionnaireValidationOutcome", StringType(), True),
            StructField("lpaQuestionnaireValidationOutcomeDate", StringType(), True),
            StructField("lpaQuestionnaireValidationDetails", ArrayType(StringType(), True), True),
            StructField("lpaStatement", StringType(), True),
            StructField("caseWithdrawnDate", StringType(), True),
            StructField("caseTransferredDate", StringType(), True),
            StructField("transferredCaseClosedDate", StringType(), True),
            StructField("caseDecisionOutcomeDate", StringType(), True),
            StructField("caseDecisionPublishedDate", StringType(), True),
            StructField("caseDecisionOutcome", StringType(), True),
            StructField("caseCompletedDate", StringType(), True),
            StructField("enforcementNotice", BooleanType(), True),
            StructField("applicationReference", StringType(), True),
            StructField("applicationDate", StringType(), True),
            StructField("applicationDecision", StringType(), True),
            StructField("applicationDecisionDate", StringType(), True),
            StructField("applicationDecisionDueDate", StringType(), True),
            StructField("caseSubmissionDueDate", StringType(), True),
            StructField("siteAddressLine1", StringType(), True),
            StructField("siteAddressLine2", StringType(), True),
            StructField("siteAddressTown", StringType(), True),
            StructField("siteAddressCounty", StringType(), True),
            StructField("siteAddressPostcode", StringType(), True),
            StructField("siteAccessDetails", ArrayType(StringType(), True), True),
            StructField("siteSafetyDetails", ArrayType(StringType(), True), True),
            StructField("siteAreaSquareMetres", DoubleType(), True),
            StructField("floorSpaceSquareMetres", DoubleType(), True),
            StructField("isCorrectAppealType", BooleanType(), True),
            StructField("isGreenBelt", BooleanType(), True),
            StructField("inConservationArea", BooleanType(), True),
            StructField("ownsAllLand", BooleanType(), True),
            StructField("ownsSomeLand", BooleanType(), True),
            StructField("knowsOtherOwners", StringType(), True),
            StructField("knowsAllOwners", StringType(), True),
            StructField("advertisedAppeal", BooleanType(), True),
            StructField("notificationMethod", ArrayType(StringType(), True), True),
            StructField("ownersInformed", BooleanType(), True),
            StructField("originalDevelopmentDescription", StringType(), True),
            StructField("changedDevelopmentDescription", BooleanType(), True),
            StructField("newConditionDetails", StringType(), True),
            StructField("extraConditionsDetails", StringType(), True),
            StructField("nearbyCaseReferences", ArrayType(StringType(), True), True),
            StructField(
                "neighbouringSiteAddresses",
                ArrayType(
                    StructType(
                        [
                            StructField("neighbouringSiteAddressLine1", StringType(), True),
                            StructField("neighbouringSiteAddressLine2", StringType(), True),
                            StructField("neighbouringSiteAddressTown", StringType(), True),
                            StructField("neighbouringSiteAddressCounty", StringType(), True),
                            StructField("neighbouringSiteAddressPostcode", StringType(), True),
                            StructField("neighbouringSiteAccessDetails", StringType(), True),
                            StructField("neighbouringSiteSafetyDetails", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("reasonForNeighbourVisits", StringType(), True),
            StructField("affectedListedBuildingNumbers", ArrayType(StringType(), True), True),
            StructField("changedListedBuildingNumbers", ArrayType(StringType(), True), True),
            StructField("preserveGrantLoan", BooleanType(), True),
            StructField("consultHistoricEngland", BooleanType(), True),
            StructField("appellantCostsAppliedFor", BooleanType(), True),
            StructField("lpaCostsAppliedFor", BooleanType(), True),
            StructField("agriculturalHolding", BooleanType(), True),
            StructField("tenantAgriculturalHolding", BooleanType(), True),
            StructField("otherTenantsAgriculturalHolding", BooleanType(), True),
            StructField("informedTenantsAgriculturalHolding", BooleanType(), True),
            StructField("appellantProcedurePreference", StringType(), True),
            StructField("appellantProcedurePreferenceDetails", StringType(), True),
            StructField("appellantProcedurePreferenceDuration", DoubleType(), True),
            StructField("appellantProcedurePreferenceWitnessCount", DoubleType(), True),
            StructField("statusPlanningObligation", StringType(), True),
            StructField("affectsScheduledMonument", BooleanType(), True),
            StructField("hasProtectedSpecies", BooleanType(), True),
            StructField("isAonbNationalLandscape", BooleanType(), True),
            StructField("designatedSitesNames", ArrayType(StringType(), True), True),
            StructField("isGypsyOrTravellerSite", BooleanType(), True),
            StructField("isPublicRightOfWay", BooleanType(), True),
            StructField("eiaEnvironmentalImpactSchedule", StringType(), True),
            StructField("eiaDevelopmentDescription", StringType(), True),
            StructField("eiaSensitiveAreaDetails", StringType(), True),
            StructField("eiaColumnTwoThreshold", BooleanType(), True),
            StructField("eiaScreeningOpinion", BooleanType(), True),
            StructField("eiaRequiresEnvironmentalStatement", BooleanType(), True),
            StructField("eiaCompletedEnvironmentalStatement", BooleanType(), True),
            StructField("hasStatutoryConsultees", BooleanType(), True),
            StructField("consultedBodiesDetails", StringType(), True),
            StructField("hasInfrastructureLevy", BooleanType(), True),
            StructField("isInfrastructureLevyFormallyAdopted", BooleanType(), True),
            StructField("infrastructureLevyAdoptedDate", StringType(), True),
            StructField("infrastructureLevyExpectedDate", StringType(), True),
            StructField("lpaProcedurePreference", StringType(), True),
            StructField("lpaProcedurePreferenceDetails", StringType(), True),
            StructField("lpaProcedurePreferenceDuration", DoubleType(), True),
            StructField("caseworkReason", StringType(), True),
            StructField("importantInformation", StringType(), True),
            StructField("jurisdiction", StringType(), True),
            StructField("redeterminedIndicator", StringType(), True),
            StructField("dateCostsReportDespatched", StringType(), True),
            StructField("dateNotRecoveredOrDerecovered", StringType(), True),
            StructField("dateRecovered", StringType(), True),
            StructField("originalCaseDecisionDate", StringType(), True),
            StructField("targetDate", StringType(), True),
            StructField("appellantCommentsSubmittedDate", StringType(), True),
            StructField("appellantStatementDueDate", StringType(), True),
            StructField("appellantStatementSubmittedDate", StringType(), True),
            StructField("appellantProofsSubmittedDate", StringType(), True),
            StructField("finalCommentsDueDate", StringType(), True),
            StructField("interestedPartyRepsDueDate", StringType(), True),
            StructField("lpaCommentsSubmittedDate", StringType(), True),
            StructField("lpaProofsSubmittedDate", StringType(), True),
            StructField("lpaStatementSubmittedDate", StringType(), True),
            StructField("proofsOfEvidenceDueDate", StringType(), True),
            StructField("siteNoticesSentDate", StringType(), True),
            StructField("statementDueDate", StringType(), True),
            StructField("caseManagementConferenceDate", StringType(), True),
            StructField("numberOfResidencesNetChange", DoubleType(), True),
            StructField("siteGridReferenceEasting", StringType(), True),
            StructField("siteGridReferenceNorthing", StringType(), True),
            StructField("siteViewableFromRoad", BooleanType(), True),
            StructField("siteWithinSSSI", BooleanType(), True),
            StructField("typeOfPlanningApplication", StringType(), True),
            StructField("developmentType", StringType(), True),
            StructField("statementOfCommonGroundDueDate", StringType(), True),
            StructField("planningObligationDueDate", StringType(), True),
            StructField("hasLandownersPermission", BooleanType(), True),
            StructField("wasApplicationRefusedDueToHighwayOrTraffic", BooleanType(), True),
            StructField("didAppellantSubmitCompletePhotosAndPlans", BooleanType(), True),
            StructField("isSiteInAreaOfSpecialControlAdverts", BooleanType(), True),
            StructField(
                "advertDetails",
                ArrayType(
                    StructType(
                        [
                            StructField("advertType", StringType(), True),
                            StructField("isAdvertInPosition", BooleanType(), True),
                            StructField("isSiteOnHighwayLand", BooleanType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("padsSapId", StringType(), True),
            StructField("enforcementNoticeReference", StringType(), True),
            StructField("descriptionOfAllegedBreach", StringType(), True),
            StructField("dateAppellantContactedPins", StringType(), True),
            StructField("ownerOccupancyStatus", StringType(), True),
            StructField("occupancyConditionsMet", BooleanType(), True),
            StructField(
                "enforcementAppealGroundsDetails",
                ArrayType(
                    StructType(
                        [
                            StructField("appealGroundLetter", StringType(), True),
                            StructField("groundForAppealStartDate", StringType(), True),
                            StructField("groundFacts", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField(
                "applicationElbAppealGroundsDetails",
                ArrayType(
                    StructType(
                        [
                            StructField("appealGroundLetter", StringType(), True),
                            StructField("groundForAppealStartDate", StringType(), True),
                            StructField("groundFacts", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("applicationMadeAndFeePaid", BooleanType(), True),
            StructField("noticeRelatesToBuildingEngineeringMiningOther", BooleanType(), True),
            StructField("changeOfUseRefuseOrWaste", BooleanType(), True),
            StructField("changeOfUseMineralExtraction", BooleanType(), True),
            StructField("changeOfUseMineralStorage", BooleanType(), True),
            StructField("relatesToErectionOfBuildingOrBuildings", BooleanType(), True),
            StructField("relatesToBuildingWithAgriculturalPurpose", BooleanType(), True),
            StructField("relatesToBuildingSingleDwellingHouse", BooleanType(), True),
            StructField("previousPlanningPermissionGranted", BooleanType(), True),
            StructField("issueDateOfEnforcementNotice", StringType(), True),
            StructField("effectiveDateOfEnforcementNotice", StringType(), True),
            StructField("didAppellantAppealLpaDecision", BooleanType(), True),
            StructField("dateLpaDecisionDue", StringType(), True),
            StructField("dateLpaDecisionReceived", StringType(), True),
            StructField("areaOfAllegedBreachInSquareMetres", DoubleType(), True),
            StructField("doesAllegedBreachCreateFloorSpace", BooleanType(), True),
            StructField("floorSpaceCreatedByBreachInSquareMetres", DoubleType(), True),
            StructField("applicationPartOrWholeDevelopment", StringType(), True),
            StructField("hasPcnBeenServed", BooleanType(), True),
            StructField("isSiteWithin67MOfTrunkRd", BooleanType(), True),
            StructField("affectedTrunkRoadName", StringType(), True),
            StructField("isSiteOnCrownLand", BooleanType(), True),
            StructField("stopNoticeExists", BooleanType(), True),
            StructField("isSiteWithin400MOfMineralInterest", BooleanType(), True),
            StructField("isSiteWithin250MOfLandfill", BooleanType(), True),
            StructField("hasDevelopmentInvolvedWasteImportation", BooleanType(), True),
            StructField("isSiteSubjectToArticle4Direction", BooleanType(), True),
            StructField("article4AffectedDevelopmentRights", StringType(), True),
            StructField("pcnRestrictedDevelopmentRights", BooleanType(), True),
            StructField("applicationMadeUnderActSection", StringType(), True),
            StructField("siteUseAtTimeOfApplication", StringType(), True),
            StructField("appealUnderActSection", StringType(), True),
            StructField("lpaConsiderAppealInvalid", BooleanType(), True),
            StructField("lpaAppealInvalidReasons", StringType(), True),
            StructField("discontinuanceNoticeServedReason", StringType(), True),
            StructField("discontinuanceNoticeServedOtherReason", StringType(), True),
            StructField("wasRetrospectivePlanningApplicationMade", BooleanType(), True),
            StructField("reasonForAppealAppellant", StringType(), True),
            StructField("screeningOpinionIndicatesEiaRequired", BooleanType(), True),
            StructField(
                "significantChangesAffectingApplicationAppellant",
                ArrayType(StructType([StructField("value", StringType(), True), StructField("comment", StringType(), True)]), True),
                True,
            ),
            StructField(
                "significantChangesAffectingApplicationLpa",
                ArrayType(StructType([StructField("value", StringType(), True), StructField("comment", StringType(), True)]), True),
                True,
            ),
            StructField("migrated", StringType(), True),
            StructField("ODTSourceSystem", StringType(), True),
            StructField("SourceSystemID", StringType(), True),
            StructField("IngestionDate", StringType(), True),
            StructField("ValidTo", StringType(), True),
            StructField("RowID", StringType(), True),
            StructField("IsActive", StringType(), True),
            StructField("message_id", StringType(), True),
            StructField("listOfDocumentsBeforeDecision", StringType(), True),
        ]
    )


def _raw_service_bus_row(**overrides):
    base = {
        "AppealS78ID": 12345,
        "caseId": 2468,
        "caseReference": "123456789",
        "submissionId": "dkec2bhbdkjkejbbkdekbejdedjke",
        "caseStatus": "validation",
        "caseType": "W",
        "caseProcedure": "written",
        "lpaCode": "someCode",
        "caseOfficerId": "hicihbfibibuefbeiujff3",
        "inspectorId": None,
        "allocationLevel": None,
        "allocationBand": None,
        "caseSpecialisms": None,
        "caseSubmittedDate": "2025-01-01T00:00:00.000Z",
        "caseCreatedDate": "2025-01-01T00:00:00.000Z",
        "caseUpdatedDate": "2025-01-01T00:00:00.000Z",
        "caseValidDate": None,
        "caseValidationDate": None,
        "caseValidationOutcome": None,
        "caseValidationInvalidDetails": None,
        "caseValidationIncompleteDetails": None,
        "caseExtensionDate": None,
        "caseStartedDate": None,
        "casePublishedDate": None,
        "linkedCaseStatus": None,
        "leadCaseReference": None,
        "lpaQuestionnaireDueDate": None,
        "lpaQuestionnaireSubmittedDate": "2025-01-01T00:00:00.000Z",
        "lpaQuestionnaireCreatedDate": "2025-01-01T00:00:00.000Z",
        "lpaQuestionnairePublishedDate": None,
        "lpaQuestionnaireValidationOutcome": None,
        "lpaQuestionnaireValidationOutcomeDate": None,
        "lpaQuestionnaireValidationDetails": None,
        "lpaStatement": "2025-01-01T00:00:00.000Z",
        "caseWithdrawnDate": None,
        "caseTransferredDate": None,
        "transferredCaseClosedDate": None,
        "caseDecisionOutcomeDate": None,
        "caseDecisionPublishedDate": None,
        "caseDecisionOutcome": None,
        "caseCompletedDate": None,
        "enforcementNotice": None,
        "applicationReference": "123",
        "applicationDate": "2025-01-01T00:00:00.000Z",
        "applicationDecision": "refused",
        "applicationDecisionDate": "2025-01-01T00:00:00.000Z",
        "applicationDecisionDueDate": None,
        "caseSubmissionDueDate": "2025-01-01T00:00:00.000Z",
        "siteAddressLine1": "e2e Test Address",
        "siteAddressLine2": "Somewhere St",
        "siteAddressTown": "Somewhereville",
        "siteAddressCounty": "Somewhere",
        "siteAddressPostcode": "BS21 6LE",
        "siteAccessDetails": ["Come and see", "Here it is"],
        "siteSafetyDetails": ["It's dangerous", "Fine"],
        "siteAreaSquareMetres": 22.0,
        "floorSpaceSquareMetres": 22.0,
        "isCorrectAppealType": True,
        "isGreenBelt": False,
        "inConservationArea": True,
        "ownsAllLand": True,
        "ownsSomeLand": True,
        "knowsOtherOwners": "Some",
        "knowsAllOwners": "Some",
        "advertisedAppeal": True,
        "notificationMethod": ["notice", "letter"],
        "ownersInformed": True,
        "originalDevelopmentDescription": "A test description",
        "changedDevelopmentDescription": False,
        "newConditionDetails": "cupidatat",
        "extraConditionsDetails": None,
        "nearbyCaseReferences": ["1000000"],
        "neighbouringSiteAddresses": [
            {
                "neighbouringSiteAddressLine1": "deserunt in irure do",
                "neighbouringSiteAddressLine2": "string",
                "neighbouringSiteAddressTown": "laboris ut enim et laborum",
                "neighbouringSiteAddressCounty": "reprehenderit eu mollit Excepteur sit",
                "neighbouringSiteAddressPostcode": "aliqua in qui ipsum",
                "neighbouringSiteAccessDetails": None,
                "neighbouringSiteSafetyDetails": None,
            }
        ],
        "reasonForNeighbourVisits": None,
        "affectedListedBuildingNumbers": ["1021466", "1021468"],
        "changedListedBuildingNumbers": [],
        "preserveGrantLoan": None,
        "consultHistoricEngland": None,
        "appellantCostsAppliedFor": False,
        "lpaCostsAppliedFor": False,
        "agriculturalHolding": True,
        "tenantAgriculturalHolding": True,
        "otherTenantsAgriculturalHolding": None,
        "informedTenantsAgriculturalHolding": None,
        "appellantProcedurePreference": None,
        "appellantProcedurePreferenceDetails": "eiusmod ex exercitation",
        "appellantProcedurePreferenceDuration": 1.0,
        "appellantProcedurePreferenceWitnessCount": 5.0,
        "statusPlanningObligation": "proident aute",
        "affectsScheduledMonument": False,
        "hasProtectedSpecies": False,
        "isAonbNationalLandscape": None,
        "designatedSitesNames": ["cSAC", "SAC", "customVal1"],
        "isGypsyOrTravellerSite": False,
        "isPublicRightOfWay": False,
        "eiaEnvironmentalImpactSchedule": None,
        "eiaDevelopmentDescription": None,
        "eiaSensitiveAreaDetails": "",
        "eiaColumnTwoThreshold": None,
        "eiaScreeningOpinion": None,
        "eiaRequiresEnvironmentalStatement": None,
        "eiaCompletedEnvironmentalStatement": None,
        "hasStatutoryConsultees": False,
        "consultedBodiesDetails": None,
        "hasInfrastructureLevy": False,
        "isInfrastructureLevyFormallyAdopted": None,
        "infrastructureLevyAdoptedDate": None,
        "infrastructureLevyExpectedDate": None,
        "lpaProcedurePreference": "hearing",
        "lpaProcedurePreferenceDetails": "pref details lpa",
        "lpaProcedurePreferenceDuration": 3.0,
        "caseworkReason": None,
        "importantInformation": None,
        "jurisdiction": None,
        "redeterminedIndicator": None,
        "dateCostsReportDespatched": None,
        "dateNotRecoveredOrDerecovered": None,
        "dateRecovered": None,
        "originalCaseDecisionDate": None,
        "targetDate": None,
        "appellantCommentsSubmittedDate": None,
        "appellantStatementDueDate": None,
        "appellantStatementSubmittedDate": None,
        "appellantProofsSubmittedDate": None,
        "finalCommentsDueDate": None,
        "interestedPartyRepsDueDate": None,
        "lpaCommentsSubmittedDate": None,
        "lpaProofsSubmittedDate": None,
        "lpaStatementSubmittedDate": None,
        "proofsOfEvidenceDueDate": None,
        "siteNoticesSentDate": None,
        "statementDueDate": None,
        "caseManagementConferenceDate": None,
        "numberOfResidencesNetChange": None,
        "siteGridReferenceEasting": None,
        "siteGridReferenceNorthing": None,
        "siteViewableFromRoad": None,
        "siteWithinSSSI": None,
        "typeOfPlanningApplication": "full-appeal",
        "developmentType": "minor-dwellings",
        "statementOfCommonGroundDueDate": None,
        "planningObligationDueDate": None,
        "hasLandownersPermission": None,
        "wasApplicationRefusedDueToHighwayOrTraffic": None,
        "didAppellantSubmitCompletePhotosAndPlans": None,
        "isSiteInAreaOfSpecialControlAdverts": None,
        "advertDetails": None,
        "padsSapId": None,
        "enforcementNoticeReference": None,
        "descriptionOfAllegedBreach": None,
        "dateAppellantContactedPins": None,
        "ownerOccupancyStatus": None,
        "occupancyConditionsMet": None,
        "enforcementAppealGroundsDetails": None,
        "applicationElbAppealGroundsDetails": None,
        "applicationMadeAndFeePaid": None,
        "noticeRelatesToBuildingEngineeringMiningOther": None,
        "changeOfUseRefuseOrWaste": None,
        "changeOfUseMineralExtraction": None,
        "changeOfUseMineralStorage": None,
        "relatesToErectionOfBuildingOrBuildings": None,
        "relatesToBuildingWithAgriculturalPurpose": None,
        "relatesToBuildingSingleDwellingHouse": None,
        "previousPlanningPermissionGranted": None,
        "issueDateOfEnforcementNotice": None,
        "effectiveDateOfEnforcementNotice": None,
        "didAppellantAppealLpaDecision": None,
        "dateLpaDecisionDue": None,
        "dateLpaDecisionReceived": None,
        "areaOfAllegedBreachInSquareMetres": None,
        "doesAllegedBreachCreateFloorSpace": None,
        "floorSpaceCreatedByBreachInSquareMetres": None,
        "applicationPartOrWholeDevelopment": None,
        "hasPcnBeenServed": None,
        "isSiteWithin67MOfTrunkRd": None,
        "affectedTrunkRoadName": None,
        "isSiteOnCrownLand": None,
        "stopNoticeExists": None,
        "isSiteWithin400MOfMineralInterest": None,
        "isSiteWithin250MOfLandfill": None,
        "hasDevelopmentInvolvedWasteImportation": None,
        "isSiteSubjectToArticle4Direction": None,
        "article4AffectedDevelopmentRights": None,
        "pcnRestrictedDevelopmentRights": None,
        "applicationMadeUnderActSection": None,
        "siteUseAtTimeOfApplication": None,
        "appealUnderActSection": None,
        "lpaConsiderAppealInvalid": None,
        "lpaAppealInvalidReasons": None,
        "discontinuanceNoticeServedReason": None,
        "discontinuanceNoticeServedOtherReason": None,
        "wasRetrospectivePlanningApplicationMade": None,
        "reasonForAppealAppellant": None,
        "screeningOpinionIndicatesEiaRequired": None,
        "significantChangesAffectingApplicationAppellant": None,
        "significantChangesAffectingApplicationLpa": None,
        "migrated": "1",
        "ODTSourceSystem": "ODT",
        "SourceSystemID": "5",
        "IngestionDate": "2025-01-01T00:00:00.000000+0000",
        "ValidTo": None,
        "RowID": "",
        "IsActive": "Y",
        "message_id": "deougfouegdedougoudeg",
        "listOfDocumentsBeforeDecision": None,
    }
    return base | overrides


def _raw_horizon_row(**overrides):
    base = {
        "caseReference": "12345",
        "caseId": "2468",
        "caseType": "C",
        "caseProcedure": "LI",
        "caseStatus": "Notice withdrawn",
        "lpaCode": "Y3425",
        "caseofficerid": "7686423",
        "caseofficerlogin": "Unassigned",
        "caseofficername": "Inspector Gadget",
        "coemailaddress": "unassigned@nowhere.com",
        "casefullReferenceNumber": "someReferenceNumber",
        "caseSpecialisms": None,
        "caseCreatedDate": "2025-01-01 00:00:00.0000000",
        "appealdocscomplete": None,
        "caseStartedDate": "2025-01-01 00:00:00.0000000",
        "caseUpdatedDate": "2025-01-01 00:00:00.0000000",
        "caseWithdrawnDate": "2025-01-01 00:00:00.0000000",
        "caseDecisionOutcomeDate": None,
        "caseCompletedDate": None,
        "dateNotRecoveredOrDerecovered": None,
        "dateRecovered": None,
        "originalCaseDecisionDate": None,
        "lpaQuestionnaireDueDate": None,
        "lpaQuestionnaireSubmittedDate": None,
        "siteAddressTown": "STONE",
        "siteAddressPostcode": "XX12 3YY",
        "siteAddressLine2": "Hilderstone Road, Spot Acre",
        "siteAddressLine1": "Spot Acre Site",
        "siteAddressCounty": "Staffordshire",
        "interestedpartyrepsduedate": "2025-01-01 00:00:00.0000000",
        "proofsdue": None,
        "siteviewablefromroad": None,
        "floorSpaceSquareMetres": None,
        "costsappliedforindicator": "No",
        "procedureappellant": "LI",
        "isAonbNationalLandscape": None,
        "lpaProcedurePreference": None,
        "inspectorneedtoentersite": None,
        "siteGridReferenceEasting": "123456",
        "siteGridReferenceNorthing": "123456",
        "sitewithinsssi": None,
        "importantinformation": None,
        "issueDateOfEnforcementNotice": datetime(2005, 1, 1),
        "effectiveDateOfEnforcementNotice": datetime(2025, 1, 1),
        "enforcementAppealGroundsDetails": [
            {"appealGroundLetter": " ", "groundForAppealStartDate": None},
            {"appealGroundLetter": "g", "groundForAppealStartDate": None},
        ],
        "allocationLevel": None,
        "allocationBand": None,
        "applicationReference": None,
        "typeOfPlanningApplication": None,
        "applicationDate": None,
        "applicationDecisionDate": None,
        "applicationMadeUnderActSection": None,
        "advertAttributeKey": None,
        "advertType": None,
        "advertSetRowNumber": None,
        "publicSafetyLpaIndicator": None,
        "amenityLPAIndicator": None,
        "publicSafetyGroundOutcome": None,
        "amenityGroundOutcome": None,
        "advertInPosition": None,
        "siteOnHighwayLand": None,
        "leadCaseReference": None,
        "linkedCaseStatus": "Not Linked",
        "caseDecisionOutcome": None,
        "jurisdiction": "Transferred",
        "redeterminedIndicator": None,
        "developmentType": "Change of use",
        "procedureType": "Inquiry",
        "caseValidationOutcome": None,
        "caseValidationDate": None,
        "dateCostsReportDespatched": None,
        "originalDevelopmentDescription": "Some description",
        "appellantCommentsSubmittedDate": None,
        "appellantStatementSubmittedDate": None,
        "lpaCommentsSubmittedDate": None,
        "lpaProofsSubmittedDate": None,
        "lpaStatementSubmittedDate": None,
        "siteNoticesSentDate": None,
        "statementDueDate": "2025-01-01 00:00:00.0000000",
        "numberOfResidencesNetChange": "0",
        "preserveGrantLoan": None,
        "consultHistoricEngland": None,
    }
    return base | overrides


def _raw_horizon_schema():
    return StructType(
        [
            StructField("caseReference", StringType(), True),
            StructField("caseId", StringType(), True),
            StructField("caseType", StringType(), True),
            StructField("caseProcedure", StringType(), True),
            StructField("caseStatus", StringType(), True),
            StructField("lpaCode", StringType(), True),
            StructField("caseofficerid", StringType(), True),
            StructField("caseofficerlogin", StringType(), True),
            StructField("caseofficername", StringType(), True),
            StructField("coemailaddress", StringType(), True),
            StructField("casefullReferenceNumber", StringType(), True),
            StructField("caseSpecialisms", ArrayType(StringType(), True), True),
            StructField("caseCreatedDate", StringType(), True),
            StructField("appealdocscomplete", StringType(), True),
            StructField("caseStartedDate", StringType(), True),
            StructField("caseUpdatedDate", StringType(), True),
            StructField("caseWithdrawnDate", StringType(), True),
            StructField("caseDecisionOutcomeDate", StringType(), True),
            StructField("caseCompletedDate", StringType(), True),
            StructField("dateNotRecoveredOrDerecovered", StringType(), True),
            StructField("dateRecovered", StringType(), True),
            StructField("originalCaseDecisionDate", StringType(), True),
            StructField("lpaQuestionnaireDueDate", StringType(), True),
            StructField("lpaQuestionnaireSubmittedDate", StringType(), True),
            StructField("siteAddressTown", StringType(), True),
            StructField("siteAddressPostcode", StringType(), True),
            StructField("siteAddressLine2", StringType(), True),
            StructField("siteAddressLine1", StringType(), True),
            StructField("siteAddressCounty", StringType(), True),
            StructField("interestedpartyrepsduedate", StringType(), True),
            StructField("proofsdue", StringType(), True),
            StructField("siteviewablefromroad", StringType(), True),
            StructField("floorSpaceSquareMetres", StringType(), True),
            StructField("costsappliedforindicator", StringType(), True),
            StructField("procedureappellant", StringType(), True),
            StructField("isAonbNationalLandscape", StringType(), True),
            StructField("lpaProcedurePreference", StringType(), True),
            StructField("inspectorneedtoentersite", StringType(), True),
            StructField("siteGridReferenceEasting", StringType(), True),
            StructField("siteGridReferenceNorthing", StringType(), True),
            StructField("sitewithinsssi", StringType(), True),
            StructField("importantinformation", StringType(), True),
            StructField("issueDateOfEnforcementNotice", TimestampType(), True),
            StructField("effectiveDateOfEnforcementNotice", TimestampType(), True),
            StructField(
                "enforcementAppealGroundsDetails",
                ArrayType(
                    StructType(
                        [StructField("appealGroundLetter", StringType(), True), StructField("groundForAppealStartDate", TimestampType(), True)]
                    ),
                    True,
                ),
                True,
            ),
            StructField("allocationLevel", StringType(), True),
            StructField("allocationBand", StringType(), True),
            StructField("applicationReference", StringType(), True),
            StructField("typeOfPlanningApplication", StringType(), True),
            StructField("applicationDate", StringType(), True),
            StructField("applicationDecisionDate", StringType(), True),
            StructField("applicationMadeUnderActSection", StringType(), True),
            StructField("advertAttributeKey", StringType(), True),
            StructField("advertType", StringType(), True),
            StructField("advertSetRowNumber", IntegerType(), True),
            StructField("publicSafetyLpaIndicator", StringType(), True),
            StructField("amenityLPAIndicator", StringType(), True),
            StructField("publicSafetyGroundOutcome", StringType(), True),
            StructField("amenityGroundOutcome", StringType(), True),
            StructField("advertInPosition", StringType(), True),
            StructField("siteOnHighwayLand", StringType(), True),
            StructField("leadCaseReference", StringType(), True),
            StructField("linkedCaseStatus", StringType(), True),
            StructField("caseDecisionOutcome", StringType(), True),
            StructField("jurisdiction", StringType(), True),
            StructField("redeterminedIndicator", StringType(), True),
            StructField("developmentType", StringType(), True),
            StructField("procedureType", StringType(), True),
            StructField("caseValidationOutcome", StringType(), True),
            StructField("caseValidationDate", StringType(), True),
            StructField("dateCostsReportDespatched", StringType(), True),
            StructField("originalDevelopmentDescription", StringType(), True),
            StructField("appellantCommentsSubmittedDate", StringType(), True),
            StructField("appellantStatementSubmittedDate", StringType(), True),
            StructField("lpaCommentsSubmittedDate", StringType(), True),
            StructField("lpaProofsSubmittedDate", StringType(), True),
            StructField("lpaStatementSubmittedDate", StringType(), True),
            StructField("siteNoticesSentDate", StringType(), True),
            StructField("statementDueDate", StringType(), True),
            StructField("numberOfResidencesNetChange", StringType(), True),
            StructField("preserveGrantLoan", BooleanType(), True),
            StructField("consultHistoricEngland", BooleanType(), True),
        ]
    )


def _raw_has_row(**overrides):
    base = {
        "caseReference": "12345",
        "caseId": 12345,
        "submissionId": "e4d42124-364c-4bda-af1f-3c40e4b09ff3",
        "caseStatus": "validation",
        "caseType": "D",
        "caseProcedure": "written",
        "lpaCode": "Q9999",
        "caseOfficerId": "13de469c-8de6-4908-97cd-330ea73df618",
        "inspectorId": None,
        "allocationLevel": None,
        "allocationBand": None,
        "caseSpecialisms": None,
        "caseSubmittedDate": "2024-03-25T23:59:59.999Z",
        "caseCreatedDate": "2026-05-14T03:10:42.803Z",
        "caseUpdatedDate": "2026-05-14T03:10:43.664Z",
        "caseValidDate": None,
        "caseValidationDate": None,
        "caseValidationOutcome": None,
        "caseValidationInvalidDetails": None,
        "caseValidationIncompleteDetails": None,
        "caseExtensionDate": None,
        "caseStartedDate": None,
        "casePublishedDate": None,
        "linkedCaseStatus": None,
        "leadCaseReference": None,
        "lpaQuestionnaireDueDate": None,
        "lpaQuestionnaireSubmittedDate": None,
        "lpaQuestionnaireCreatedDate": None,
        "lpaQuestionnairePublishedDate": None,
        "lpaQuestionnaireValidationOutcome": None,
        "lpaQuestionnaireValidationOutcomeDate": None,
        "lpaQuestionnaireValidationDetails": None,
        "lpaStatement": None,
        "caseWithdrawnDate": None,
        "caseTransferredDate": None,
        "transferredCaseClosedDate": None,
        "caseDecisionOutcomeDate": None,
        "caseDecisionPublishedDate": None,
        "caseDecisionOutcome": None,
        "caseCompletedDate": None,
        "enforcementNotice": None,
        "applicationReference": "123",
        "applicationDate": "2024-01-01T00:00:00.000Z",
        "applicationDecision": "refused",
        "applicationDecisionDate": "2024-01-01T00:00:00.000Z",
        "caseSubmissionDueDate": "2024-03-25T23:59:59.999Z",
        "siteAddressLine1": "e2e Test Address",
        "siteAddressLine2": "Somewhere St",
        "siteAddressTown": "Somewhereville",
        "siteAddressCounty": "Somewhere",
        "siteAddressPostcode": "BS21 6LE",
        "siteAccessDetails": ["Come and see", ""],
        "siteSafetyDetails": ["It's dangerous", ""],
        "siteAreaSquareMetres": 22.0,
        "floorSpaceSquareMetres": 22.0,
        "isCorrectAppealType": None,
        "isGreenBelt": False,
        "inConservationArea": None,
        "affectsScheduledMonument": None,
        "hasProtectedSpecies": None,
        "isAonbNationalLandscape": None,
        "isSiteOnHighwayLand": None,
        "designatedSitesNames": None,
        "hasInfrastructureLevy": None,
        "isInfrastructureLevyFormallyAdopted": None,
        "infrastructureLevyAdoptedDate": None,
        "infrastructureLevyExpectedDate": None,
        "lpaProcedurePreference": None,
        "lpaProcedurePreferenceDetails": None,
        "lpaProcedurePreferenceDuration": None,
        "caseworkReason": None,
        "importantInformation": None,
        "jurisdiction": None,
        "redeterminedIndicator": None,
        "dateCostsReportDespatched": None,
        "dateNotRecoveredOrDerecovered": None,
        "dateRecovered": None,
        "originalCaseDecisionDate": None,
        "targetDate": None,
        "ownsAllLand": True,
        "ownsSomeLand": True,
        "knowsOtherOwners": "Some",
        "knowsAllOwners": "Some",
        "advertisedAppeal": True,
        "notificationMethod": None,
        "ownersInformed": True,
        "originalDevelopmentDescription": "A test description",
        "changedDevelopmentDescription": False,
        "newConditionDetails": None,
        "nearbyCaseReferences": [],
        "neighbouringSiteAddresses": None,
        "reasonForNeighbourVisits": None,
        "affectedListedBuildingNumbers": None,
        "appellantCostsAppliedFor": False,
        "lpaCostsAppliedFor": None,
        "typeOfPlanningApplication": "full-appeal",
        "siteGridReferenceEasting": None,
        "siteGridReferenceNorthing": None,
        "hasLandownersPermission": None,
        "wasApplicationRefusedDueToHighwayOrTraffic": None,
        "didAppellantSubmitCompletePhotosAndPlans": None,
        "isSiteInAreaOfSpecialControlAdverts": None,
        "advertDetails": None,
        "padsSapId": None,
        "message_id": "bcd6ee6658e249eb8915df2983f61f2a",
        "applicationDecisionDueDate": None,
        "SourceSystemID": "5",
        "RowID": "",
        "migrated": "1",
        "ODTSourceSystem": "ODT",
        "ValidTo": None,
        "IsActive": "Y",
        "AppealsHasID": 2,
        "IngestionDate": datetime(2026, 5, 14, 3, 10, 44, 986000),
        "appellantProcedurePreference": None,
        "appellantProcedurePreferenceDetails": None,
        "appellantProcedurePreferenceDuration": None,
        "appellantProcedurePreferenceWitnessCount": None,
        "consultedBodiesDetails": None,
        "designAccessStatementProvided": None,
        "developmentType": None,
        "hasEmergingPlan": None,
        "hasStatutoryConsultees": None,
        "numberOfResidencesNetChange": None,
        "planningObligation": None,
        "siteViewableFromRoad": None,
        "siteWithinSSSI": None,
        "statusPlanningObligation": None,
    }
    return base | overrides


def _raw_has_schema():
    return StructType(
        [
            StructField("caseReference", StringType(), True),
            StructField("caseId", LongType(), True),
            StructField("submissionId", StringType(), True),
            StructField("caseStatus", StringType(), True),
            StructField("caseType", StringType(), True),
            StructField("caseProcedure", StringType(), True),
            StructField("lpaCode", StringType(), True),
            StructField("caseOfficerId", StringType(), True),
            StructField("inspectorId", StringType(), True),
            StructField("allocationLevel", StringType(), True),
            StructField("allocationBand", DoubleType(), True),
            StructField("caseSpecialisms", ArrayType(StringType(), True), True),
            StructField("caseSubmittedDate", StringType(), True),
            StructField("caseCreatedDate", StringType(), True),
            StructField("caseUpdatedDate", StringType(), True),
            StructField("caseValidDate", StringType(), True),
            StructField("caseValidationDate", StringType(), True),
            StructField("caseValidationOutcome", StringType(), True),
            StructField("caseValidationInvalidDetails", ArrayType(StringType(), True), True),
            StructField("caseValidationIncompleteDetails", ArrayType(StringType(), True), True),
            StructField("caseExtensionDate", StringType(), True),
            StructField("caseStartedDate", StringType(), True),
            StructField("casePublishedDate", StringType(), True),
            StructField("linkedCaseStatus", StringType(), True),
            StructField("leadCaseReference", StringType(), True),
            StructField("lpaQuestionnaireDueDate", StringType(), True),
            StructField("lpaQuestionnaireSubmittedDate", StringType(), True),
            StructField("lpaQuestionnaireCreatedDate", StringType(), True),
            StructField("lpaQuestionnairePublishedDate", StringType(), True),
            StructField("lpaQuestionnaireValidationOutcome", StringType(), True),
            StructField("lpaQuestionnaireValidationOutcomeDate", StringType(), True),
            StructField("lpaQuestionnaireValidationDetails", ArrayType(StringType(), True), True),
            StructField("lpaStatement", StringType(), True),
            StructField("caseWithdrawnDate", StringType(), True),
            StructField("caseTransferredDate", StringType(), True),
            StructField("transferredCaseClosedDate", StringType(), True),
            StructField("caseDecisionOutcomeDate", StringType(), True),
            StructField("caseDecisionPublishedDate", StringType(), True),
            StructField("caseDecisionOutcome", StringType(), True),
            StructField("caseCompletedDate", StringType(), True),
            StructField("enforcementNotice", BooleanType(), True),
            StructField("applicationReference", StringType(), True),
            StructField("applicationDate", StringType(), True),
            StructField("applicationDecision", StringType(), True),
            StructField("applicationDecisionDate", StringType(), True),
            StructField("caseSubmissionDueDate", StringType(), True),
            StructField("siteAddressLine1", StringType(), True),
            StructField("siteAddressLine2", StringType(), True),
            StructField("siteAddressTown", StringType(), True),
            StructField("siteAddressCounty", StringType(), True),
            StructField("siteAddressPostcode", StringType(), True),
            StructField("siteAccessDetails", ArrayType(StringType(), True), True),
            StructField("siteSafetyDetails", ArrayType(StringType(), True), True),
            StructField("siteAreaSquareMetres", DoubleType(), True),
            StructField("floorSpaceSquareMetres", DoubleType(), True),
            StructField("isCorrectAppealType", BooleanType(), True),
            StructField("isGreenBelt", BooleanType(), True),
            StructField("inConservationArea", BooleanType(), True),
            StructField("affectsScheduledMonument", BooleanType(), True),
            StructField("hasProtectedSpecies", BooleanType(), True),
            StructField("isAonbNationalLandscape", BooleanType(), True),
            StructField("isSiteOnHighwayLand", BooleanType(), True),
            StructField("designatedSitesNames", ArrayType(StringType(), True), True),
            StructField("hasInfrastructureLevy", BooleanType(), True),
            StructField("isInfrastructureLevyFormallyAdopted", BooleanType(), True),
            StructField("infrastructureLevyAdoptedDate", StringType(), True),
            StructField("infrastructureLevyExpectedDate", StringType(), True),
            StructField("lpaProcedurePreference", StringType(), True),
            StructField("lpaProcedurePreferenceDetails", StringType(), True),
            StructField("lpaProcedurePreferenceDuration", DoubleType(), True),
            StructField("caseworkReason", StringType(), True),
            StructField("importantInformation", StringType(), True),
            StructField("jurisdiction", StringType(), True),
            StructField("redeterminedIndicator", BooleanType(), True),
            StructField("dateCostsReportDespatched", StringType(), True),
            StructField("dateNotRecoveredOrDerecovered", StringType(), True),
            StructField("dateRecovered", StringType(), True),
            StructField("originalCaseDecisionDate", StringType(), True),
            StructField("targetDate", StringType(), True),
            StructField("ownsAllLand", BooleanType(), True),
            StructField("ownsSomeLand", BooleanType(), True),
            StructField("knowsOtherOwners", StringType(), True),
            StructField("knowsAllOwners", StringType(), True),
            StructField("advertisedAppeal", BooleanType(), True),
            StructField("notificationMethod", ArrayType(StringType(), True), True),
            StructField("ownersInformed", BooleanType(), True),
            StructField("originalDevelopmentDescription", StringType(), True),
            StructField("changedDevelopmentDescription", BooleanType(), True),
            StructField("newConditionDetails", StringType(), True),
            StructField("nearbyCaseReferences", ArrayType(StringType(), True), True),
            StructField(
                "neighbouringSiteAddresses",
                ArrayType(
                    StructType(
                        [
                            StructField("neighbouringSiteAddressLine1", StringType(), True),
                            StructField("neighbouringSiteAddressLine2", StringType(), True),
                            StructField("neighbouringSiteAddressTown", StringType(), True),
                            StructField("neighbouringSiteAddressCounty", StringType(), True),
                            StructField("neighbouringSiteAddressPostcode", StringType(), True),
                            StructField("neighbouringSiteAccessDetails", StringType(), True),
                            StructField("neighbouringSiteSafetyDetails", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("reasonForNeighbourVisits", StringType(), True),
            StructField("affectedListedBuildingNumbers", ArrayType(StringType(), True), True),
            StructField("appellantCostsAppliedFor", BooleanType(), True),
            StructField("lpaCostsAppliedFor", BooleanType(), True),
            StructField("typeOfPlanningApplication", StringType(), True),
            StructField("siteGridReferenceEasting", StringType(), True),
            StructField("siteGridReferenceNorthing", StringType(), True),
            StructField("hasLandownersPermission", BooleanType(), True),
            StructField("wasApplicationRefusedDueToHighwayOrTraffic", BooleanType(), True),
            StructField("didAppellantSubmitCompletePhotosAndPlans", BooleanType(), True),
            StructField("isSiteInAreaOfSpecialControlAdverts", BooleanType(), True),
            StructField(
                "advertDetails",
                ArrayType(
                    StructType(
                        [
                            StructField("advertType", StringType(), True),
                            StructField("isAdvertInPosition", BooleanType(), True),
                            StructField("isSiteOnHighwayLand", BooleanType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("padsSapId", StringType(), True),
            StructField("message_id", StringType(), True),
            StructField("applicationDecisionDueDate", StringType(), True),
            StructField("SourceSystemID", StringType(), True),
            StructField("RowID", StringType(), True),
            StructField("migrated", StringType(), True),
            StructField("ODTSourceSystem", StringType(), True),
            StructField("ValidTo", StringType(), True),
            StructField("IsActive", StringType(), True),
            StructField("AppealsHasID", LongType(), True),
            StructField("IngestionDate", TimestampType(), True),
            StructField("appellantProcedurePreference", StringType(), True),
            StructField("appellantProcedurePreferenceDetails", StringType(), True),
            StructField("appellantProcedurePreferenceDuration", StringType(), True),
            StructField("appellantProcedurePreferenceWitnessCount", StringType(), True),
            StructField("consultedBodiesDetails", StringType(), True),
            StructField("designAccessStatementProvided", StringType(), True),
            StructField("developmentType", StringType(), True),
            StructField("hasEmergingPlan", BooleanType(), True),
            StructField("hasStatutoryConsultees", BooleanType(), True),
            StructField("numberOfResidencesNetChange", StringType(), True),
            StructField("planningObligation", StringType(), True),
            StructField("siteViewableFromRoad", StringType(), True),
            StructField("siteWithinSSSI", StringType(), True),
            StructField("statusPlanningObligation", StringType(), True),
        ]
    )


def _group_resolver_row(**overrides):
    base = {"caseReference": "98765", "currentGroup": "B", "asOfTimestamp": datetime(2025, 1, 1)}
    return base | overrides


def _group_resolver_schema():
    return StructType(
        [
            StructField("caseReference", StringType(), True),
            StructField("currentGroup", StringType(), True),
            StructField("asOfTimestamp", TimestampType(), True),
        ]
    )


def _harmonised_s78_row(**overrides):
    base = {
        "caseReference": "12345",
        "AppealS78ID": 1,
        "caseId": 2468,
        "submissionId": None,
        "caseStatus": "Notice withdrawn",
        "caseType": "C",
        "caseProcedure": "LI",
        "lpaCode": "Y3425",
        "caseOfficerId": None,
        "inspectorId": None,
        "allocationLevel": None,
        "allocationBand": None,
        "caseSpecialisms": None,
        "caseSubmittedDate": None,
        "caseCreatedDate": "2025-01-01 00:00:00.0000000",
        "caseUpdatedDate": "2025-01-01 00:00:00.0000000",
        "caseValidDate": None,
        "caseValidationDate": None,
        "caseValidationOutcome": None,
        "caseValidationInvalidDetails": None,
        "caseValidationIncompleteDetails": None,
        "caseExtensionDate": None,
        "caseStartedDate": "2025-01-01 00:00:00.0000000",
        "casePublishedDate": None,
        "linkedCaseStatus": "Not Linked",
        "leadCaseReference": None,
        "lpaQuestionnaireDueDate": None,
        "lpaQuestionnaireSubmittedDate": None,
        "lpaQuestionnaireCreatedDate": None,
        "lpaQuestionnairePublishedDate": None,
        "lpaQuestionnaireValidationOutcome": None,
        "lpaQuestionnaireValidationOutcomeDate": None,
        "lpaQuestionnaireValidationDetails": None,
        "lpaStatement": None,
        "caseWithdrawnDate": "2025-01-01 00:00:00.0000000",
        "caseTransferredDate": None,
        "transferredCaseClosedDate": None,
        "caseDecisionOutcomeDate": None,
        "caseDecisionPublishedDate": None,
        "caseDecisionOutcome": None,
        "caseCompletedDate": None,
        "enforcementNotice": None,
        "applicationReference": None,
        "applicationDate": None,
        "applicationDecision": None,
        "applicationDecisionDate": None,
        "applicationDecisionDueDate": None,
        "caseSubmissionDueDate": None,
        "siteAddressLine1": "Spot Acre Site",
        "siteAddressLine2": "Hilderstone Road, Spot Acre",
        "siteAddressTown": "STONE",
        "siteAddressCounty": "Staffordshire",
        "siteAddressPostcode": "XX12 3YY",
        "siteAccessDetails": None,
        "siteSafetyDetails": None,
        "siteAreaSquareMetres": None,
        "floorSpaceSquareMetres": None,
        "isCorrectAppealType": None,
        "isGreenBelt": None,
        "inConservationArea": None,
        "ownsAllLand": None,
        "ownsSomeLand": None,
        "knowsOtherOwners": None,
        "knowsAllOwners": None,
        "advertisedAppeal": None,
        "notificationMethod": None,
        "ownersInformed": None,
        "originalDevelopmentDescription": "Some description",
        "changedDevelopmentDescription": None,
        "newConditionDetails": None,
        "extraConditionsDetails": None,
        "nearbyCaseReferences": None,
        "neighbouringSiteAddresses": None,
        "reasonForNeighbourVisits": None,
        "affectedListedBuildingNumbers": None,
        "changedListedBuildingNumbers": None,
        "preserveGrantLoan": None,
        "consultHistoricEngland": None,
        "appellantCostsAppliedFor": None,
        "lpaCostsAppliedFor": None,
        "agriculturalHolding": None,
        "tenantAgriculturalHolding": None,
        "otherTenantsAgriculturalHolding": None,
        "informedTenantsAgriculturalHolding": None,
        "appellantProcedurePreference": None,
        "appellantProcedurePreferenceDetails": None,
        "appellantProcedurePreferenceDuration": None,
        "appellantProcedurePreferenceWitnessCount": None,
        "statusPlanningObligation": None,
        "affectsScheduledMonument": None,
        "hasProtectedSpecies": None,
        "isAonbNationalLandscape": None,
        "designatedSitesNames": None,
        "isGypsyOrTravellerSite": None,
        "isPublicRightOfWay": None,
        "eiaEnvironmentalImpactSchedule": None,
        "eiaDevelopmentDescription": None,
        "eiaSensitiveAreaDetails": None,
        "eiaColumnTwoThreshold": None,
        "eiaScreeningOpinion": None,
        "eiaRequiresEnvironmentalStatement": None,
        "eiaCompletedEnvironmentalStatement": None,
        "hasStatutoryConsultees": None,
        "consultedBodiesDetails": None,
        "hasInfrastructureLevy": None,
        "isInfrastructureLevyFormallyAdopted": None,
        "infrastructureLevyAdoptedDate": None,
        "infrastructureLevyExpectedDate": None,
        "lpaProcedurePreference": None,
        "lpaProcedurePreferenceDetails": None,
        "lpaProcedurePreferenceDuration": None,
        "caseworkReason": None,
        "importantInformation": None,
        "jurisdiction": "Transferred",
        "redeterminedIndicator": None,
        "dateCostsReportDespatched": None,
        "dateNotRecoveredOrDerecovered": None,
        "dateRecovered": None,
        "originalCaseDecisionDate": None,
        "targetDate": None,
        "appellantCommentsSubmittedDate": None,
        "appellantStatementDueDate": None,
        "appellantStatementSubmittedDate": None,
        "appellantProofsSubmittedDate": None,
        "finalCommentsDueDate": None,
        "interestedPartyRepsDueDate": None,
        "lpaCommentsSubmittedDate": None,
        "lpaProofsSubmittedDate": None,
        "lpaStatementSubmittedDate": None,
        "proofsOfEvidenceDueDate": None,
        "siteNoticesSentDate": None,
        "statementDueDate": "2025-01-01 00:00:00.0000000",
        "caseManagementConferenceDate": None,
        "numberOfResidencesNetChange": 0.0,
        "siteGridReferenceEasting": "123456",
        "siteGridReferenceNorthing": "123456",
        "siteViewableFromRoad": None,
        "siteWithinSSSI": None,
        "typeOfPlanningApplication": None,
        "developmentType": "Change of use",
        "statementOfCommonGroundDueDate": None,
        "planningObligationDueDate": None,
        "hasLandownersPermission": None,
        "wasApplicationRefusedDueToHighwayOrTraffic": None,
        "didAppellantSubmitCompletePhotosAndPlans": None,
        "isSiteInAreaOfSpecialControlAdverts": None,
        "advertDetails": None,
        "padsSapId": None,
        "enforcementNoticeReference": None,
        "descriptionOfAllegedBreach": None,
        "dateAppellantContactedPins": None,
        "ownerOccupancyStatus": None,
        "occupancyConditionsMet": None,
        "enforcementAppealGroundsDetails": None,
        "applicationElbAppealGroundsDetails": [
            {"appealGroundLetter": " ", "groundForAppealStartDate": None, "groundFacts": None},
            {"appealGroundLetter": "g", "groundForAppealStartDate": None, "groundFacts": None},
        ],
        "applicationMadeAndFeePaid": None,
        "noticeRelatesToBuildingEngineeringMiningOther": None,
        "changeOfUseRefuseOrWaste": None,
        "changeOfUseMineralExtraction": None,
        "changeOfUseMineralStorage": None,
        "relatesToErectionOfBuildingOrBuildings": None,
        "relatesToBuildingWithAgriculturalPurpose": None,
        "relatesToBuildingSingleDwellingHouse": None,
        "previousPlanningPermissionGranted": None,
        "issueDateOfEnforcementNotice": "2005-01-01 00:00:00",
        "effectiveDateOfEnforcementNotice": "2025-01-01 00:00:00",
        "didAppellantAppealLpaDecision": None,
        "dateLpaDecisionDue": None,
        "dateLpaDecisionReceived": None,
        "areaOfAllegedBreachInSquareMetres": None,
        "doesAllegedBreachCreateFloorSpace": None,
        "floorSpaceCreatedByBreachInSquareMetres": None,
        "applicationPartOrWholeDevelopment": None,
        "hasPcnBeenServed": None,
        "isSiteWithin67MOfTrunkRd": None,
        "affectedTrunkRoadName": None,
        "isSiteOnCrownLand": None,
        "stopNoticeExists": None,
        "isSiteWithin400MOfMineralInterest": None,
        "isSiteWithin250MOfLandfill": None,
        "hasDevelopmentInvolvedWasteImportation": None,
        "isSiteSubjectToArticle4Direction": None,
        "article4AffectedDevelopmentRights": None,
        "pcnRestrictedDevelopmentRights": None,
        "applicationMadeUnderActSection": None,
        "siteUseAtTimeOfApplication": None,
        "appealUnderActSection": None,
        "lpaConsiderAppealInvalid": None,
        "lpaAppealInvalidReasons": None,
        "discontinuanceNoticeServedReason": None,
        "discontinuanceNoticeServedOtherReason": None,
        "wasRetrospectivePlanningApplicationMade": None,
        "reasonForAppealAppellant": None,
        "screeningOpinionIndicatesEiaRequired": None,
        "significantChangesAffectingApplicationAppellant": None,
        "significantChangesAffectingApplicationLpa": None,
        "migrated": None,
        "ODTSourceSystem": "HORIZON",
        "SourceSystemID": None,
        "IngestionDate": datetime(2026, 5, 18, 11, 38, 5, 76735),
        "ValidTo": None,
        "RowID": "",
        "IsActive": "Y",
        "message_id": None,
        "listOfDocumentsBeforeDecision": None,
    }
    return base | overrides


def _harmonised_s78_schema():
    return StructType(
        [
            StructField("caseReference", StringType(), True),
            StructField("AppealS78ID", LongType(), False),
            StructField("caseId", LongType(), True),
            StructField("submissionId", StringType(), True),
            StructField("caseStatus", StringType(), True),
            StructField("caseType", StringType(), True),
            StructField("caseProcedure", StringType(), True),
            StructField("lpaCode", StringType(), True),
            StructField("caseOfficerId", StringType(), True),
            StructField("inspectorId", StringType(), True),
            StructField("allocationLevel", StringType(), True),
            StructField("allocationBand", DoubleType(), True),
            StructField("caseSpecialisms", ArrayType(StringType(), True), True),
            StructField("caseSubmittedDate", StringType(), True),
            StructField("caseCreatedDate", StringType(), True),
            StructField("caseUpdatedDate", StringType(), True),
            StructField("caseValidDate", StringType(), True),
            StructField("caseValidationDate", StringType(), True),
            StructField("caseValidationOutcome", StringType(), True),
            StructField("caseValidationInvalidDetails", ArrayType(StringType(), True), True),
            StructField("caseValidationIncompleteDetails", ArrayType(StringType(), True), True),
            StructField("caseExtensionDate", StringType(), True),
            StructField("caseStartedDate", StringType(), True),
            StructField("casePublishedDate", StringType(), True),
            StructField("linkedCaseStatus", StringType(), True),
            StructField("leadCaseReference", StringType(), True),
            StructField("lpaQuestionnaireDueDate", StringType(), True),
            StructField("lpaQuestionnaireSubmittedDate", StringType(), True),
            StructField("lpaQuestionnaireCreatedDate", StringType(), True),
            StructField("lpaQuestionnairePublishedDate", StringType(), True),
            StructField("lpaQuestionnaireValidationOutcome", StringType(), True),
            StructField("lpaQuestionnaireValidationOutcomeDate", StringType(), True),
            StructField("lpaQuestionnaireValidationDetails", ArrayType(StringType(), True), True),
            StructField("lpaStatement", StringType(), True),
            StructField("caseWithdrawnDate", StringType(), True),
            StructField("caseTransferredDate", StringType(), True),
            StructField("transferredCaseClosedDate", StringType(), True),
            StructField("caseDecisionOutcomeDate", StringType(), True),
            StructField("caseDecisionPublishedDate", StringType(), True),
            StructField("caseDecisionOutcome", StringType(), True),
            StructField("caseCompletedDate", StringType(), True),
            StructField("enforcementNotice", BooleanType(), True),
            StructField("applicationReference", StringType(), True),
            StructField("applicationDate", StringType(), True),
            StructField("applicationDecision", StringType(), True),
            StructField("applicationDecisionDate", StringType(), True),
            StructField("applicationDecisionDueDate", StringType(), True),
            StructField("caseSubmissionDueDate", StringType(), True),
            StructField("siteAddressLine1", StringType(), True),
            StructField("siteAddressLine2", StringType(), True),
            StructField("siteAddressTown", StringType(), True),
            StructField("siteAddressCounty", StringType(), True),
            StructField("siteAddressPostcode", StringType(), True),
            StructField("siteAccessDetails", ArrayType(StringType(), True), True),
            StructField("siteSafetyDetails", ArrayType(StringType(), True), True),
            StructField("siteAreaSquareMetres", DoubleType(), True),
            StructField("floorSpaceSquareMetres", DoubleType(), True),
            StructField("isCorrectAppealType", BooleanType(), True),
            StructField("isGreenBelt", BooleanType(), True),
            StructField("inConservationArea", BooleanType(), True),
            StructField("ownsAllLand", BooleanType(), True),
            StructField("ownsSomeLand", BooleanType(), True),
            StructField("knowsOtherOwners", StringType(), True),
            StructField("knowsAllOwners", StringType(), True),
            StructField("advertisedAppeal", BooleanType(), True),
            StructField("notificationMethod", ArrayType(StringType(), True), True),
            StructField("ownersInformed", BooleanType(), True),
            StructField("originalDevelopmentDescription", StringType(), True),
            StructField("changedDevelopmentDescription", BooleanType(), True),
            StructField("newConditionDetails", StringType(), True),
            StructField("extraConditionsDetails", StringType(), True),
            StructField("nearbyCaseReferences", ArrayType(StringType(), True), True),
            StructField(
                "neighbouringSiteAddresses",
                ArrayType(
                    StructType(
                        [
                            StructField("neighbouringSiteAddressLine1", StringType(), True),
                            StructField("neighbouringSiteAddressLine2", StringType(), True),
                            StructField("neighbouringSiteAddressTown", StringType(), True),
                            StructField("neighbouringSiteAddressCounty", StringType(), True),
                            StructField("neighbouringSiteAddressPostcode", StringType(), True),
                            StructField("neighbouringSiteAccessDetails", StringType(), True),
                            StructField("neighbouringSiteSafetyDetails", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("reasonForNeighbourVisits", StringType(), True),
            StructField("affectedListedBuildingNumbers", ArrayType(StringType(), True), True),
            StructField("changedListedBuildingNumbers", ArrayType(StringType(), True), True),
            StructField("preserveGrantLoan", BooleanType(), True),
            StructField("consultHistoricEngland", BooleanType(), True),
            StructField("appellantCostsAppliedFor", BooleanType(), True),
            StructField("lpaCostsAppliedFor", BooleanType(), True),
            StructField("agriculturalHolding", BooleanType(), True),
            StructField("tenantAgriculturalHolding", BooleanType(), True),
            StructField("otherTenantsAgriculturalHolding", BooleanType(), True),
            StructField("informedTenantsAgriculturalHolding", BooleanType(), True),
            StructField("appellantProcedurePreference", StringType(), True),
            StructField("appellantProcedurePreferenceDetails", StringType(), True),
            StructField("appellantProcedurePreferenceDuration", DoubleType(), True),
            StructField("appellantProcedurePreferenceWitnessCount", DoubleType(), True),
            StructField("statusPlanningObligation", StringType(), True),
            StructField("affectsScheduledMonument", BooleanType(), True),
            StructField("hasProtectedSpecies", BooleanType(), True),
            StructField("isAonbNationalLandscape", BooleanType(), True),
            StructField("designatedSitesNames", ArrayType(StringType(), True), True),
            StructField("isGypsyOrTravellerSite", BooleanType(), True),
            StructField("isPublicRightOfWay", BooleanType(), True),
            StructField("eiaEnvironmentalImpactSchedule", StringType(), True),
            StructField("eiaDevelopmentDescription", StringType(), True),
            StructField("eiaSensitiveAreaDetails", StringType(), True),
            StructField("eiaColumnTwoThreshold", BooleanType(), True),
            StructField("eiaScreeningOpinion", BooleanType(), True),
            StructField("eiaRequiresEnvironmentalStatement", BooleanType(), True),
            StructField("eiaCompletedEnvironmentalStatement", BooleanType(), True),
            StructField("hasStatutoryConsultees", BooleanType(), True),
            StructField("consultedBodiesDetails", StringType(), True),
            StructField("hasInfrastructureLevy", BooleanType(), True),
            StructField("isInfrastructureLevyFormallyAdopted", BooleanType(), True),
            StructField("infrastructureLevyAdoptedDate", StringType(), True),
            StructField("infrastructureLevyExpectedDate", StringType(), True),
            StructField("lpaProcedurePreference", StringType(), True),
            StructField("lpaProcedurePreferenceDetails", StringType(), True),
            StructField("lpaProcedurePreferenceDuration", DoubleType(), True),
            StructField("caseworkReason", StringType(), True),
            StructField("importantInformation", StringType(), True),
            StructField("jurisdiction", StringType(), True),
            StructField("redeterminedIndicator", StringType(), True),
            StructField("dateCostsReportDespatched", StringType(), True),
            StructField("dateNotRecoveredOrDerecovered", StringType(), True),
            StructField("dateRecovered", StringType(), True),
            StructField("originalCaseDecisionDate", StringType(), True),
            StructField("targetDate", StringType(), True),
            StructField("appellantCommentsSubmittedDate", StringType(), True),
            StructField("appellantStatementDueDate", StringType(), True),
            StructField("appellantStatementSubmittedDate", StringType(), True),
            StructField("appellantProofsSubmittedDate", StringType(), True),
            StructField("finalCommentsDueDate", StringType(), True),
            StructField("interestedPartyRepsDueDate", StringType(), True),
            StructField("lpaCommentsSubmittedDate", StringType(), True),
            StructField("lpaProofsSubmittedDate", StringType(), True),
            StructField("lpaStatementSubmittedDate", StringType(), True),
            StructField("proofsOfEvidenceDueDate", StringType(), True),
            StructField("siteNoticesSentDate", StringType(), True),
            StructField("statementDueDate", StringType(), True),
            StructField("caseManagementConferenceDate", StringType(), True),
            StructField("numberOfResidencesNetChange", DoubleType(), True),
            StructField("siteGridReferenceEasting", StringType(), True),
            StructField("siteGridReferenceNorthing", StringType(), True),
            StructField("siteViewableFromRoad", BooleanType(), True),
            StructField("siteWithinSSSI", BooleanType(), True),
            StructField("typeOfPlanningApplication", StringType(), True),
            StructField("developmentType", StringType(), True),
            StructField("statementOfCommonGroundDueDate", StringType(), True),
            StructField("planningObligationDueDate", StringType(), True),
            StructField("hasLandownersPermission", BooleanType(), True),
            StructField("wasApplicationRefusedDueToHighwayOrTraffic", BooleanType(), True),
            StructField("didAppellantSubmitCompletePhotosAndPlans", BooleanType(), True),
            StructField("isSiteInAreaOfSpecialControlAdverts", BooleanType(), True),
            StructField(
                "advertDetails",
                ArrayType(
                    StructType(
                        [
                            StructField("advertType", StringType(), True),
                            StructField("isAdvertInPosition", BooleanType(), True),
                            StructField("isSiteOnHighwayLand", BooleanType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("padsSapId", StringType(), True),
            StructField("enforcementNoticeReference", StringType(), True),
            StructField("descriptionOfAllegedBreach", StringType(), True),
            StructField("dateAppellantContactedPins", StringType(), True),
            StructField("ownerOccupancyStatus", StringType(), True),
            StructField("occupancyConditionsMet", BooleanType(), True),
            StructField(
                "enforcementAppealGroundsDetails",
                ArrayType(
                    StructType(
                        [
                            StructField("appealGroundLetter", StringType(), True),
                            StructField("groundForAppealStartDate", StringType(), True),
                            StructField("groundFacts", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField(
                "applicationElbAppealGroundsDetails",
                ArrayType(
                    StructType(
                        [
                            StructField("appealGroundLetter", StringType(), True),
                            StructField("groundForAppealStartDate", StringType(), True),
                            StructField("groundFacts", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("applicationMadeAndFeePaid", BooleanType(), True),
            StructField("noticeRelatesToBuildingEngineeringMiningOther", BooleanType(), True),
            StructField("changeOfUseRefuseOrWaste", BooleanType(), True),
            StructField("changeOfUseMineralExtraction", BooleanType(), True),
            StructField("changeOfUseMineralStorage", BooleanType(), True),
            StructField("relatesToErectionOfBuildingOrBuildings", BooleanType(), True),
            StructField("relatesToBuildingWithAgriculturalPurpose", BooleanType(), True),
            StructField("relatesToBuildingSingleDwellingHouse", BooleanType(), True),
            StructField("previousPlanningPermissionGranted", BooleanType(), True),
            StructField("issueDateOfEnforcementNotice", StringType(), True),
            StructField("effectiveDateOfEnforcementNotice", StringType(), True),
            StructField("didAppellantAppealLpaDecision", BooleanType(), True),
            StructField("dateLpaDecisionDue", StringType(), True),
            StructField("dateLpaDecisionReceived", StringType(), True),
            StructField("areaOfAllegedBreachInSquareMetres", DoubleType(), True),
            StructField("doesAllegedBreachCreateFloorSpace", BooleanType(), True),
            StructField("floorSpaceCreatedByBreachInSquareMetres", DoubleType(), True),
            StructField("applicationPartOrWholeDevelopment", StringType(), True),
            StructField("hasPcnBeenServed", BooleanType(), True),
            StructField("isSiteWithin67MOfTrunkRd", BooleanType(), True),
            StructField("affectedTrunkRoadName", StringType(), True),
            StructField("isSiteOnCrownLand", BooleanType(), True),
            StructField("stopNoticeExists", BooleanType(), True),
            StructField("isSiteWithin400MOfMineralInterest", BooleanType(), True),
            StructField("isSiteWithin250MOfLandfill", BooleanType(), True),
            StructField("hasDevelopmentInvolvedWasteImportation", BooleanType(), True),
            StructField("isSiteSubjectToArticle4Direction", BooleanType(), True),
            StructField("article4AffectedDevelopmentRights", StringType(), True),
            StructField("pcnRestrictedDevelopmentRights", BooleanType(), True),
            StructField("applicationMadeUnderActSection", StringType(), True),
            StructField("siteUseAtTimeOfApplication", StringType(), True),
            StructField("appealUnderActSection", StringType(), True),
            StructField("lpaConsiderAppealInvalid", BooleanType(), True),
            StructField("lpaAppealInvalidReasons", StringType(), True),
            StructField("discontinuanceNoticeServedReason", StringType(), True),
            StructField("discontinuanceNoticeServedOtherReason", StringType(), True),
            StructField("wasRetrospectivePlanningApplicationMade", BooleanType(), True),
            StructField("reasonForAppealAppellant", StringType(), True),
            StructField("screeningOpinionIndicatesEiaRequired", BooleanType(), True),
            StructField(
                "significantChangesAffectingApplicationAppellant",
                ArrayType(StructType([StructField("value", StringType(), True), StructField("comment", StringType(), True)]), True),
                True,
            ),
            StructField(
                "significantChangesAffectingApplicationLpa",
                ArrayType(StructType([StructField("value", StringType(), True), StructField("comment", StringType(), True)]), True),
                True,
            ),
            StructField("migrated", StringType(), True),
            StructField("ODTSourceSystem", StringType(), True),
            StructField("SourceSystemID", StringType(), True),
            StructField("IngestionDate", TimestampType(), True),
            StructField("ValidTo", StringType(), True),
            StructField("RowID", StringType(), True),
            StructField("IsActive", StringType(), False),
            StructField("message_id", StringType(), True),
            StructField("listOfDocumentsBeforeDecision", StringType(), True),
        ]
    )


class TestAppealS78HarmonisationProcess(ETLTestCase):
    def assert_etl_successful(self, test_case: str):
        spark = PytestSparkSessionUtil().get_spark_session()
        service_bus_data = spark.createDataFrame(
            (_raw_service_bus_row(), _raw_service_bus_row(caseReference="23456")),
            schema=_raw_service_bus_schema(),
        )
        service_bus_table = f"{test_case}_sb_appeal_s78"
        self.write_existing_table(spark, service_bus_data, service_bus_table, "odw_harmonised_db", "odw-harmonised", service_bus_table, "overwrite")
        horizon_data = spark.createDataFrame(
            (_raw_horizon_row(), _raw_horizon_row(caseReference="23456")),
            schema=_raw_horizon_schema(),
        )
        horizon_table = f"{test_case}_horizon_appeal_s78"
        self.write_existing_table(spark, horizon_data, horizon_table, "odw_standardised_db", "odw-standardised", horizon_table, "overwrite")
        has_data = spark.createDataFrame(
            (_raw_has_row(), _raw_has_row(caseReference="23456")),
            schema=_raw_has_schema(),
        )
        has_table = f"{test_case}_appeal_has"
        self.write_existing_table(spark, has_data, has_table, "odw_harmonised_db", "odw-harmonised", has_table, "overwrite")
        group_resolver_data = spark.createDataFrame((_group_resolver_row(),), schema=_group_resolver_schema())
        group_resolver_table = f"{test_case}_GroupResolver"
        self.write_existing_table(
            spark, group_resolver_data, group_resolver_table, "odw_harmonised_db", "odw-harmonised", group_resolver_table, "overwrite"
        )
        expected_curated_data_after_writing = spark.createDataFrame(
            (
                _harmonised_s78_row(),
                _harmonised_s78_row(
                    caseReference="123456789",
                    submissionId="dkec2bhbdkjkejbbkdekbejdedjke",
                    caseStatus="validation",
                    caseType="W",
                    caseProcedure="written",
                    lpaCode="someCode",
                    caseOfficerId="hicihbfibibuefbeiujff3",
                    caseSubmittedDate="2025-01-01T00:00:00.000Z",
                    caseCreatedDate="2025-01-01T00:00:00.000Z",
                    caseUpdatedDate="2025-01-01T00:00:00.000Z",
                    caseStartedDate=None,
                    linkedCaseStatus=None,
                    lpaQuestionnaireSubmittedDate="2025-01-01T00:00:00.000Z",
                    lpaQuestionnaireCreatedDate="2025-01-01T00:00:00.000Z",
                    lpaStatement="2025-01-01T00:00:00.000Z",
                    caseWithdrawnDate=None,
                    applicationReference="123",
                    applicationDate="2025-01-01T00:00:00.000Z",
                    applicationDecision="refused",
                    applicationDecisionDate="2025-01-01T00:00:00.000Z",
                    caseSubmissionDueDate="2025-01-01T00:00:00.000Z",
                    siteAddressLine1="e2e Test Address",
                    siteAddressLine2="Somewhere St",
                    siteAddressTown="Somewhereville",
                    siteAddressCounty="Somewhere",
                    siteAddressPostcode="BS21 6LE",
                    siteAccessDetails=["Come and see", "Here it is"],
                    siteSafetyDetails=["It's dangerous", "Fine"],
                    siteAreaSquareMetres=22.0,
                    floorSpaceSquareMetres=22.0,
                    isCorrectAppealType=True,
                    isGreenBelt=False,
                    inConservationArea=True,
                    ownsAllLand=True,
                    ownsSomeLand=True,
                    knowsOtherOwners="Some",
                    knowsAllOwners="Some",
                    advertisedAppeal=True,
                    notificationMethod=["notice", "letter"],
                    ownersInformed=True,
                    originalDevelopmentDescription="A test description",
                    changedDevelopmentDescription=False,
                    newConditionDetails="cupidatat",
                    nearbyCaseReferences=["1000000"],
                    neighbouringSiteAddresses=[
                        {
                            "neighbouringSiteAddressLine1": "deserunt in irure do",
                            "neighbouringSiteAddressLine2": "string",
                            "neighbouringSiteAddressTown": "laboris ut enim et laborum",
                            "neighbouringSiteAddressCounty": "reprehenderit eu mollit Excepteur sit",
                            "neighbouringSiteAddressPostcode": "aliqua in qui ipsum",
                            "neighbouringSiteAccessDetails": None,
                            "neighbouringSiteSafetyDetails": None,
                        }
                    ],
                    affectedListedBuildingNumbers=["1021466", "1021468"],
                    changedListedBuildingNumbers=[],
                    appellantCostsAppliedFor=False,
                    lpaCostsAppliedFor=False,
                    agriculturalHolding=True,
                    tenantAgriculturalHolding=True,
                    appellantProcedurePreferenceDetails="eiusmod ex exercitation",
                    appellantProcedurePreferenceDuration=1.0,
                    appellantProcedurePreferenceWitnessCount=5.0,
                    statusPlanningObligation="proident aute",
                    affectsScheduledMonument=False,
                    hasProtectedSpecies=False,
                    designatedSitesNames=["cSAC", "SAC", "customVal1"],
                    isGypsyOrTravellerSite=False,
                    isPublicRightOfWay=False,
                    eiaSensitiveAreaDetails="",
                    hasStatutoryConsultees=False,
                    hasInfrastructureLevy=False,
                    lpaProcedurePreference="hearing",
                    lpaProcedurePreferenceDetails="pref details lpa",
                    lpaProcedurePreferenceDuration=3.0,
                    jurisdiction=None,
                    statementDueDate=None,
                    numberOfResidencesNetChange=None,
                    siteGridReferenceEasting=None,
                    siteGridReferenceNorthing=None,
                    typeOfPlanningApplication="full-appeal",
                    developmentType="minor-dwellings",
                    applicationElbAppealGroundsDetails=None,
                    issueDateOfEnforcementNotice=None,
                    effectiveDateOfEnforcementNotice=None,
                    ODTSourceSystem="ODT",
                    SourceSystemID="5",
                    IngestionDate=datetime(2025, 1, 1, 0, 0),
                    message_id="deougfouegdedougoudeg",
                ),
                _harmonised_s78_row(
                    caseReference="23456",
                    submissionId="dkec2bhbdkjkejbbkdekbejdedjke",
                    caseStatus="validation",
                    caseType="W",
                    caseProcedure="written",
                    lpaCode="someCode",
                    caseOfficerId="hicihbfibibuefbeiujff3",
                    caseSubmittedDate="2025-01-01T00:00:00.000Z",
                    caseCreatedDate="2025-01-01T00:00:00.000Z",
                    caseUpdatedDate="2025-01-01T00:00:00.000Z",
                    caseStartedDate=None,
                    linkedCaseStatus=None,
                    lpaQuestionnaireSubmittedDate="2025-01-01T00:00:00.000Z",
                    lpaQuestionnaireCreatedDate="2025-01-01T00:00:00.000Z",
                    lpaStatement="2025-01-01T00:00:00.000Z",
                    caseWithdrawnDate=None,
                    applicationReference="123",
                    applicationDate="2025-01-01T00:00:00.000Z",
                    applicationDecision="refused",
                    applicationDecisionDate="2025-01-01T00:00:00.000Z",
                    caseSubmissionDueDate="2025-01-01T00:00:00.000Z",
                    siteAddressLine1="e2e Test Address",
                    siteAddressLine2="Somewhere St",
                    siteAddressTown="Somewhereville",
                    siteAddressCounty="Somewhere",
                    siteAddressPostcode="BS21 6LE",
                    siteAccessDetails=["Come and see", "Here it is"],
                    siteSafetyDetails=["It's dangerous", "Fine"],
                    siteAreaSquareMetres=22.0,
                    floorSpaceSquareMetres=22.0,
                    isCorrectAppealType=True,
                    isGreenBelt=False,
                    inConservationArea=True,
                    ownsAllLand=True,
                    ownsSomeLand=True,
                    knowsOtherOwners="Some",
                    knowsAllOwners="Some",
                    advertisedAppeal=True,
                    notificationMethod=["notice", "letter"],
                    ownersInformed=True,
                    originalDevelopmentDescription="A test description",
                    changedDevelopmentDescription=False,
                    newConditionDetails="cupidatat",
                    nearbyCaseReferences=["1000000"],
                    neighbouringSiteAddresses=[
                        {
                            "neighbouringSiteAddressLine1": "deserunt in irure do",
                            "neighbouringSiteAddressLine2": "string",
                            "neighbouringSiteAddressTown": "laboris ut enim et laborum",
                            "neighbouringSiteAddressCounty": "reprehenderit eu mollit Excepteur sit",
                            "neighbouringSiteAddressPostcode": "aliqua in qui ipsum",
                            "neighbouringSiteAccessDetails": None,
                            "neighbouringSiteSafetyDetails": None,
                        }
                    ],
                    affectedListedBuildingNumbers=["1021466", "1021468"],
                    changedListedBuildingNumbers=[],
                    appellantCostsAppliedFor=False,
                    lpaCostsAppliedFor=False,
                    agriculturalHolding=True,
                    tenantAgriculturalHolding=True,
                    appellantProcedurePreferenceDetails="eiusmod ex exercitation",
                    appellantProcedurePreferenceDuration=1.0,
                    appellantProcedurePreferenceWitnessCount=5.0,
                    statusPlanningObligation="proident aute",
                    affectsScheduledMonument=False,
                    hasProtectedSpecies=False,
                    designatedSitesNames=["cSAC", "SAC", "customVal1"],
                    isGypsyOrTravellerSite=False,
                    isPublicRightOfWay=False,
                    eiaSensitiveAreaDetails="",
                    hasStatutoryConsultees=False,
                    hasInfrastructureLevy=False,
                    lpaProcedurePreference="hearing",
                    lpaProcedurePreferenceDetails="pref details lpa",
                    lpaProcedurePreferenceDuration=3.0,
                    jurisdiction=None,
                    statementDueDate=None,
                    numberOfResidencesNetChange=None,
                    siteGridReferenceEasting=None,
                    siteGridReferenceNorthing=None,
                    typeOfPlanningApplication="full-appeal",
                    developmentType="minor-dwellings",
                    applicationElbAppealGroundsDetails=None,
                    issueDateOfEnforcementNotice=None,
                    effectiveDateOfEnforcementNotice=None,
                    ODTSourceSystem="ODT",
                    SourceSystemID="5",
                    IngestionDate=datetime(2025, 1, 1, 0, 0),
                    ValidTo="2026-05-14 03:10:44.986",
                    IsActive="N",
                    message_id="deougfouegdedougoudeg",
                ),
                _harmonised_s78_row(caseReference="23456", AppealS78ID=2),
            ),
            schema=_harmonised_s78_schema(),
        )
        output_table = f"{test_case}_appeal_s78"
        expected_group_resolver_to_update = spark.createDataFrame(
            (
                _group_resolver_row(caseReference="12345", currentGroup="B", asOfTimestamp=datetime(2026, 5, 18, 11, 38, 5, 76735)),
                _group_resolver_row(caseReference="123456789", currentGroup="B", asOfTimestamp=datetime(2025, 1, 1, 0, 0)),
                _group_resolver_row(caseReference="23456", currentGroup="B", asOfTimestamp=datetime(2026, 5, 18, 11, 38, 5, 76735)),
            ),
            schema=_group_resolver_schema(),
        )
        expected_group_resolver_data = group_resolver_data.union(expected_group_resolver_to_update)
        """
        Rows to be merged into the target HAS table (dumped from the notebook)
        {"caseReference": "12345", "s78HrmActiveTs": datetime(2026, 5, 18, 11, 38, 5, 76735)},
        {"caseReference": "123456789", "s78HrmActiveTs": datetime(2025, 1, 1, 0, 0)},
        {"caseReference": "23456", "s78HrmActiveTs": datetime(2026, 5, 18, 11, 38, 5, 76735)},
        """
        expected_has_data = spark.createDataFrame(
            (
                _raw_has_row(caseReference="12345", IsActive="N", ValidTo=datetime(2026, 5, 18, 11, 38, 5, 76735)),
                _raw_has_row(caseReference="23456", IsActive="N", ValidTo=datetime(2026, 5, 18, 11, 38, 5, 76735)),
            ),
            schema=_raw_has_schema(),
        )
        with (
            mock.patch.object(AppealS78HarmonisationProcess, "SERVICE_BUS_TABLE", service_bus_table),
            mock.patch.object(AppealS78HarmonisationProcess, "HORIZON_TABLE", horizon_table),
            mock.patch.object(AppealS78HarmonisationProcess, "HAS_TABLE", has_table),
            mock.patch.object(AppealS78HarmonisationProcess, "GROUP_RESOLVER", group_resolver_table),
            mock.patch.object(AppealS78HarmonisationProcess, "OUTPUT_TABLE", output_table),
        ):
            inst = AppealS78HarmonisationProcess(spark)
            result = inst.run()
            assert_etl_result_successful(result)
            actual_table_data = spark.table(f"odw_curated_db.{output_table}")
            assert_dataframes_equal(expected_curated_data_after_writing, actual_table_data)
            # Would be good to move this delta merge logic to the appropriate entities - shouldn't be crossing logic between ETL processes
            # but the original notebook did, so this functionality has been preserved for now
            actual_group_resolver_data = spark.table(f"odw_harmonised_db.{group_resolver_table}")
            assert_dataframes_equal(expected_group_resolver_data, actual_group_resolver_data)
            actual_has_data = spark.table(f"odw_harmonised_db.{has_table}")
            assert_dataframes_equal(expected_has_data, actual_has_data)

    def test__appeal_s78_harmonisation_process__run_with_no_existing_data(self):
        """
        - Given I have new service bus s78 data, and s78 data extracted from horizon
        - When I call AppealS78HarmonisationProcess.run
        - Then the data should be harmonised into the s78 table, and the relevant groupResolver/HAS tables activated/deactivated
        """
        self.assert_etl_successful("t_as78hp_wned")

    def test__appeal_s78_harmonisation_process__run_with_existing_data(self):
        """
        - Given I have new service bus s78 data, and s78 data extracted from horizon, and an existing GroupResolver and harmnised HAS table
        - When I call AppealS78HarmonisationProcess.run
        - Then the data should be harmonised into the s78 table, and the relevant groupResolver/HAS tables activated/deactivated
        """
        test_case = "t_as78hp_wed"
        spark = PytestSparkSessionUtil().get_spark_session()
        existing_s78_data = spark.createDataFrame(
            (
                _harmonised_s78_row(caseReference="42"),  # Should be overwritten
            ),
            schema=_harmonised_s78_schema(),
        )
        output_table = f"{test_case}_appeal_s78"
        self.write_existing_table(spark, existing_s78_data, output_table, "odw_harmonised_db", "odw-harmonised", output_table, "overwrite")
        self.assert_etl_successful(test_case)
