import odw.test.util.mock.import_mock_notebook_utils  # noqa: F401
import pytest
from odw.core.etl.transformation.harmonised.nsip_project_harmonisation_process import NsipProjectHarmonisationProcess
from odw.core.io.synapse_legacy_delta_io import SynapseLegacyDeltaIO
from odw.core.util.util import Util
from odw.core.util.logging_util import LoggingUtil
from odw.test.util.session_util import PytestSparkSessionUtil
from odw.test.integration_test.etl.etl_test_case import ETLTestCase
from odw.test.util.util import generate_local_path, format_to_adls_path
from odw.test.util.assertion import assert_dataframes_equal, assert_etl_result_successful
import mock
from pyspark.sql.types import ArrayType, BooleanType, DoubleType, IntegerType, LongType, StringType, StructField, StructType, TimestampType, DateType
from pyspark.sql import DataFrame
from datetime import datetime


def _service_bus_schema():
    return StructType(
        [
            StructField("NSIPProjectInfoInternalID", LongType(), True),
            StructField("caseId", LongType(), True),
            StructField("caseReference", StringType(), True),
            StructField("projectName", StringType(), True),
            StructField("projectNameWelsh", StringType(), True),
            StructField("projectDescription", StringType(), True),
            StructField("projectDescriptionWelsh", StringType(), True),
            StructField("decision", StringType(), True),
            StructField("publishStatus", StringType(), True),
            StructField("sector", StringType(), True),
            StructField("projectType", StringType(), True),
            StructField("sourceSystem", StringType(), True),
            StructField("stage", StringType(), True),
            StructField("projectLocation", StringType(), True),
            StructField("projectLocationWelsh", StringType(), True),
            StructField("projectEmailAddress", StringType(), True),
            StructField("regions", ArrayType(StringType(), True), True),
            StructField("transboundary", BooleanType(), True),
            StructField("easting", IntegerType(), True),
            StructField("northing", IntegerType(), True),
            StructField("welshLanguage", BooleanType(), True),
            StructField("mapZoomLevel", StringType(), True),
            StructField("secretaryOfState", StringType(), True),
            StructField("datePINSFirstNotifiedOfProject", StringType(), True),
            StructField("dateProjectAppearsOnWebsite", StringType(), True),
            StructField("anticipatedSubmissionDateNonSpecific", StringType(), True),
            StructField("anticipatedDateOfSubmission", StringType(), True),
            StructField("screeningOpinionSought", StringType(), True),
            StructField("screeningOpinionIssued", StringType(), True),
            StructField("scopingOpinionSought", StringType(), True),
            StructField("scopingOpinionIssued", StringType(), True),
            StructField("section46Notification", StringType(), True),
            StructField("dateOfDCOSubmission", StringType(), True),
            StructField("deadlineForAcceptanceDecision", StringType(), True),
            StructField("dateOfDCOAcceptance", StringType(), True),
            StructField("dateOfNonAcceptance", StringType(), True),
            StructField("dateOfRepresentationPeriodOpen", StringType(), True),
            StructField("dateOfRelevantRepresentationClose", StringType(), True),
            StructField("extensionToDateRelevantRepresentationsClose", StringType(), True),
            StructField("dateRRepAppearOnWebsite", StringType(), True),
            StructField("dateIAPIDue", StringType(), True),
            StructField("rule6LetterPublishDate", StringType(), True),
            StructField("preliminaryMeetingStartDate", StringType(), True),
            StructField("notificationDateForPMAndEventsDirectlyFollowingPM", StringType(), True),
            StructField("notificationDateForEventsDeveloper", StringType(), True),
            StructField("dateSection58NoticeReceived", StringType(), True),
            StructField("confirmedStartOfExamination", StringType(), True),
            StructField("rule8LetterPublishDate", StringType(), True),
            StructField("deadlineForCloseOfExamination", StringType(), True),
            StructField("dateTimeExaminationEnds", StringType(), True),
            StructField("stage4ExtensionToExamCloseDate", StringType(), True),
            StructField("deadlineForSubmissionOfRecommendation", StringType(), True),
            StructField("dateOfRecommendations", StringType(), True),
            StructField("stage5ExtensionToRecommendationDeadline", StringType(), True),
            StructField("deadlineForDecision", StringType(), True),
            StructField("confirmedDateOfDecision", StringType(), True),
            StructField("stage5ExtensionToDecisionDeadline", StringType(), True),
            StructField("jRPeriodEndDate", StringType(), True),
            StructField("dateProjectWithdrawn", StringType(), True),
            StructField("operationsLeadId", StringType(), True),
            StructField("operationsManagerId", StringType(), True),
            StructField("caseManagerId", StringType(), True),
            StructField("nsipOfficerIds", ArrayType(StringType(), True), True),
            StructField("nsipAdministrationOfficerIds", ArrayType(StringType(), True), True),
            StructField("leadInspectorId", StringType(), True),
            StructField("inspectorIds", ArrayType(StringType(), True), True),
            StructField("environmentalServicesOfficerId", StringType(), True),
            StructField("legalOfficerId", StringType(), True),
            StructField("applicantId", StringType(), True),
            StructField("migrationStatus", BooleanType(), True),
            StructField("dateOfReOpenRelevantRepresentationStart", StringType(), True),
            StructField("dateOfReOpenRelevantRepresentationClose", StringType(), True),
            StructField("IsActive", StringType(), True),
            StructField("inceptionMeetingDate", StringType(), True),
            StructField("draftDocumentSubmissionDate", StringType(), True),
            StructField("programmeDocumentSubmissionDate", StringType(), True),
            StructField("estimatedScopingSubmissionDate", StringType(), True),
            StructField("consultationMilestoneAdequacyDate", StringType(), True),
            StructField("principalAreaDisagreementSummaryStmtSubmittedDate", StringType(), True),
            StructField("policyComplianceDocumentSubmittedDate", StringType(), True),
            StructField("designApproachDocumentSubmittedDate", StringType(), True),
            StructField("caAndTpEvidenceSubmittedDate", StringType(), True),
            StructField("caseTeamIssuedCommentsDate", StringType(), True),
            StructField("fastTrackAdmissionDocumentSubmittedDate", StringType(), True),
            StructField("matureOutlineControlDocumentSubmittedDate", StringType(), True),
            StructField("memLastUpdated", StringType(), True),
            StructField("multipartyApplicationCheckDocumentSubmittedDate", StringType(), True),
            StructField("programmeDocumentReviewedByEstDate", StringType(), True),
            StructField("publicSectorEqualityDutySubmittedDate", StringType(), True),
            StructField("statutoryConsultationPeriodEndDate", StringType(), True),
            StructField("submissionOfDraftDocumentsDate", StringType(), True),
            StructField("updatedProgrammeDocumentReceivedDate", StringType(), True),
            StructField("courtDecisionDate", StringType(), True),
            StructField("decisionChallengeSubmissionDate", StringType(), True),
            StructField("courtDecisionOutcomeText", StringType(), True),
            StructField("recommendation", StringType(), True),
            StructField("additionalComments", StringType(), True),
            StructField("caAndTpEvidence", StringType(), True),
            StructField("fastTrackAdmissionDocument", StringType(), True),
            StructField(
                "meetings",
                ArrayType(
                    StructType(
                        [
                            StructField("meetingId", LongType(), True),
                            StructField("meetingAgenda", StringType(), True),
                            StructField("planningInspectorateRole", StringType(), True),
                            StructField("meetingDate", StringType(), True),
                            StructField("meetingType", StringType(), True),
                            StructField("estimatedPrelimMeetingDate", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("multipartyApplicationCheckDocument", StringType(), True),
            StructField("newMaturity", StringType(), True),
            StructField("numberBand2Inspectors", DoubleType(), True),
            StructField("numberBand3Inspectors", DoubleType(), True),
            StructField("programmeDocumentURI", StringType(), True),
            StructField("publicSectorEqualityDuty", StringType(), True),
            StructField("subProjectType", StringType(), True),
            StructField("tier", StringType(), True),
            StructField("s61SummaryURI", StringType(), True),
            StructField("planProcessEvidence", BooleanType(), True),
            StructField("issuesTracker", StringType(), True),
            StructField("essentialFastTrackComponents", BooleanType(), True),
            StructField("principalAreaDisagreementSummaryStmt", StringType(), True),
            StructField("policyComplianceDocument", StringType(), True),
            StructField("designApproachDocument", StringType(), True),
            StructField("matureOutlineControlDocument", StringType(), True),
            StructField(
                "invoices",
                ArrayType(
                    StructType(
                        [
                            StructField("invoiceStage", StringType(), True),
                            StructField("invoiceNumber", StringType(), True),
                            StructField("amountDue", DoubleType(), True),
                            StructField("paymentDueDate", StringType(), True),
                            StructField("invoicedDate", StringType(), True),
                            StructField("paymentDate", StringType(), True),
                            StructField("refundCreditNoteNumber", StringType(), True),
                            StructField("refundAmount", DoubleType(), True),
                            StructField("refundIssueDate", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("operationsLeadIds", ArrayType(StringType(), True), True),
            StructField("operationsManagerIds", ArrayType(StringType(), True), True),
            StructField("caseManagerIds", ArrayType(StringType(), True), True),
            StructField("leadInspectorIds", ArrayType(StringType(), True), True),
            StructField("environmentalServicesOfficerIds", ArrayType(StringType(), True), True),
            StructField("legalOfficerIds", ArrayType(StringType(), True), True),
            StructField("ODTSourceSystem", StringType(), True),
            StructField("SourceSystemID", StringType(), True),
            StructField("IngestionDate", TimestampType(), True),
            StructField("ValidTo", StringType(), True),
            StructField("isMaterialChange", BooleanType(), True),
        ]
    )


def _horizon_schema():
    return StructType(
        [
            StructField("ingested_datetime", TimestampType(), True),
            StructField("expected_from", TimestampType(), True),
            StructField("expected_to", TimestampType(), True),
            StructField("casecreateddate", StringType(), True),
            StructField("projectname", StringType(), True),
            StructField("projectstatus", StringType(), True),
            StructField("examtimetablepublishstatus", StringType(), True),
            StructField("sector", StringType(), True),
            StructField("projecttype", StringType(), True),
            StructField("stage", StringType(), True),
            StructField("casereference", StringType(), True),
            StructField("horizoncasenumber", StringType(), True),
            StructField("projectlocation", StringType(), True),
            StructField("projectemailaddress", StringType(), True),
            StructField("twitteraccountname", StringType(), True),
            StructField("region", StringType(), True),
            StructField("easting", StringType(), True),
            StructField("northing", StringType(), True),
            StructField("transboundary", StringType(), True),
            StructField("welshlanguage", StringType(), True),
            StructField("exasize", StringType(), True),
            StructField("mapzoomlevel", StringType(), True),
            StructField("projectdescription", StringType(), True),
            StructField("sos", StringType(), True),
            StructField("tene", StringType(), True),
            StructField("anticipatedsubmissiondatenonspecific", StringType(), True),
            StructField("dateprojectappearsonwebsite", StringType(), True),
            StructField("dateofdcoacceptance", StringType(), True),
            StructField("anticipateddateofsubmission", StringType(), True),
            StructField("dateofdcosubmission", StringType(), True),
            StructField("dateofrepresentationperiodopen", StringType(), True),
            StructField("dateofrelevantrepresentationclose", StringType(), True),
            StructField("daterrepappearonwebsite", StringType(), True),
            StructField("confirmedstartofexamination", StringType(), True),
            StructField("datetimeexaminationends", StringType(), True),
            StructField("stage4extensiontoexamclosedate", StringType(), True),
            StructField("stage5extensiontorecommendationdeadline", StringType(), True),
            StructField("dateofrecommendations", StringType(), True),
            StructField("confirmeddateofdecision", StringType(), True),
            StructField("stage5extensiontodecisiondeadline", StringType(), True),
            StructField("dateprojectwithdrawn", StringType(), True),
            StructField("section46notification", StringType(), True),
            StructField("datepinsfirstnotifiedofproject", StringType(), True),
            StructField("screeningopinionsought", StringType(), True),
            StructField("screeningopinionissued", StringType(), True),
            StructField("scopingopinionsought", StringType(), True),
            StructField("scopingopinionissued", StringType(), True),
            StructField("deadlineforacceptancedecision", StringType(), True),
            StructField("datesection58noticereceived", StringType(), True),
            StructField("preliminarymeetingstartdate", StringType(), True),
            StructField("deadlineforcloseofexamination", StringType(), True),
            StructField("deadlineforsubmissionofrecommendation", StringType(), True),
            StructField("deadlinefordecision", StringType(), True),
            StructField("jrperiodenddate", StringType(), True),
            StructField("extensiontodaterelevantrepresentationsclose", StringType(), True),
            StructField("summary", StringType(), True),
            StructField("promotername", StringType(), True),
            StructField("applicantfirstname", StringType(), True),
            StructField("applicantlastname", StringType(), True),
            StructField("addressline1", StringType(), True),
            StructField("addressline2", StringType(), True),
            StructField("addresstown", StringType(), True),
            StructField("addresscounty", StringType(), True),
            StructField("postcode", StringType(), True),
            StructField("applicantemailaddress", StringType(), True),
            StructField("applicantwebaddress", StringType(), True),
            StructField("applicantphonenumber", StringType(), True),
            StructField("applicantdescriptionofproject", StringType(), True),
            StructField("casenodeid", StringType(), True),
            StructField("projectNameWelsh", StringType(), True),
            StructField("projectDescriptionWelsh", StringType(), True),
            StructField("projectLocationWelsh", StringType(), True),
            StructField("input_file", StringType(), True),
            StructField("ingested_by_process_name", StringType(), True),
            StructField("modified_datetime", TimestampType(), True),
            StructField("modified_by_process_name", StringType(), True),
            StructField("entity_name", StringType(), True),
            StructField("file_id", StringType(), True),
            StructField("salutation", StringType(), True),
        ]
    )


def _final_table_schema():
    return StructType(
        [
            StructField("NSIPProjectInfoInternalID", IntegerType(), True),
            StructField("caseId", IntegerType(), True),
            StructField("casereference", StringType(), True),
            StructField("projectname", StringType(), True),
            StructField("projectNameWelsh", StringType(), True),
            StructField("projectDescription", StringType(), True),
            StructField("summary", StringType(), True),
            StructField("projectDescriptionWelsh", StringType(), True),
            StructField("caseCreatedDate", StringType(), True),
            StructField("decision", StringType(), True),
            StructField("publishStatus", StringType(), True),
            StructField("sector", StringType(), True),
            StructField("projectType", StringType(), True),
            StructField("sourceSystem", StringType(), True),
            StructField("stage", StringType(), True),
            StructField("projectLocation", StringType(), True),
            StructField("projectLocationWelsh", StringType(), True),
            StructField("projectEmailAddress", StringType(), True),
            StructField("Regions", ArrayType(StringType(), True), True),
            StructField("transboundary", BooleanType(), True),
            StructField("easting", IntegerType(), True),
            StructField("northing", IntegerType(), True),
            StructField("welshLanguage", BooleanType(), True),
            StructField("mapZoomLevel", StringType(), True),
            StructField("secretaryOfState", StringType(), True),
            StructField("datePINSFirstNotifiedOfProject", StringType(), True),
            StructField("dateProjectAppearsOnWebsite", StringType(), True),
            StructField("anticipatedSubmissionDateNonSpecific", StringType(), True),
            StructField("anticipatedDateOfSubmission", StringType(), True),
            StructField("screeningOpinionSought", StringType(), True),
            StructField("screeningOpinionIssued", StringType(), True),
            StructField("scopingOpinionSought", StringType(), True),
            StructField("scopingOpinionIssued", StringType(), True),
            StructField("section46Notification", StringType(), True),
            StructField("dateOfDCOSubmission", StringType(), True),
            StructField("deadlineForAcceptanceDecision", StringType(), True),
            StructField("dateOfDCOAcceptance", StringType(), True),
            StructField("dateOfNonAcceptance", StringType(), True),
            StructField("dateOfRepresentationPeriodOpen", StringType(), True),
            StructField("dateOfRelevantRepresentationClose", StringType(), True),
            StructField("extensionToDateRelevantRepresentationsClose", StringType(), True),
            StructField("dateRRepAppearOnWebsite", StringType(), True),
            StructField("dateIAPIDue", StringType(), True),
            StructField("rule6LetterPublishDate", StringType(), True),
            StructField("preliminaryMeetingStartDate", StringType(), True),
            StructField("notificationDateForPMAndEventsDirectlyFollowingPM", StringType(), True),
            StructField("notificationDateForEventsDeveloper", StringType(), True),
            StructField("dateSection58NoticeReceived", StringType(), True),
            StructField("confirmedStartOfExamination", StringType(), True),
            StructField("rule8LetterPublishDate", DateType(), True),
            StructField("deadlineForCloseOfExamination", StringType(), True),
            StructField("dateTimeExaminationEnds", StringType(), True),
            StructField("stage4ExtensionToExamCloseDate", StringType(), True),
            StructField("deadlineForSubmissionOfRecommendation", StringType(), True),
            StructField("dateOfRecommendations", StringType(), True),
            StructField("stage5ExtensionToRecommendationDeadline", StringType(), True),
            StructField("deadlineForDecision", StringType(), True),
            StructField("confirmedDateOfDecision", StringType(), True),
            StructField("stage5ExtensionToDecisionDeadline", StringType(), True),
            StructField("jRPeriodEndDate", StringType(), True),
            StructField("dateProjectWithdrawn", StringType(), True),
            StructField("operationsLeadId", StringType(), True),
            StructField("operationsManagerId", StringType(), True),
            StructField("caseManagerId", StringType(), True),
            StructField("nsipOfficerIds", ArrayType(StringType(), True), True),
            StructField("nsipAdministrationOfficerIds", ArrayType(StringType(), True), True),
            StructField("leadInspectorId", StringType(), True),
            StructField("inspectorIds", ArrayType(StringType(), True), True),
            StructField("environmentalServicesOfficerId", StringType(), True),
            StructField("legalOfficerId", StringType(), True),
            StructField("applicantId", StringType(), True),
            StructField("migrationStatus", BooleanType(), True),
            StructField("dateOfReOpenRelevantRepresentationStart", StringType(), True),
            StructField("dateOfReOpenRelevantRepresentationClose", StringType(), True),
            StructField("examTimetablePublishStatus", StringType(), True),
            StructField("twitteraccountname", StringType(), True),
            StructField("exasize", StringType(), True),
            StructField("tene", StringType(), True),
            StructField("promotername", StringType(), True),
            StructField("applicantfirstname", StringType(), True),
            StructField("applicantlastname", StringType(), True),
            StructField("addressLine1", StringType(), True),
            StructField("addressLine2", StringType(), True),
            StructField("addressTown", StringType(), True),
            StructField("addressCounty", StringType(), True),
            StructField("Postcode", StringType(), True),
            StructField("applicantemailaddress", StringType(), True),
            StructField("applicantwebaddress", StringType(), True),
            StructField("applicantphonenumber", StringType(), True),
            StructField("applicantdescriptionofproject", StringType(), True),
            StructField("HorizonCaseNumber", StringType(), True),
            StructField("inceptionMeetingDate", StringType(), True),
            StructField("draftDocumentSubmissionDate", StringType(), True),
            StructField("programmeDocumentSubmissionDate", StringType(), True),
            StructField("estimatedScopingSubmissionDate", StringType(), True),
            StructField("consultationMilestoneAdequacyDate", StringType(), True),
            StructField("principalAreaDisagreementSummaryStmtSubmittedDate", StringType(), True),
            StructField("policyComplianceDocumentSubmittedDate", StringType(), True),
            StructField("designApproachDocumentSubmittedDate", StringType(), True),
            StructField("caAndTpEvidenceSubmittedDate", StringType(), True),
            StructField("caseTeamIssuedCommentsDate", StringType(), True),
            StructField("fastTrackAdmissionDocumentSubmittedDate", StringType(), True),
            StructField("matureOutlineControlDocumentSubmittedDate", StringType(), True),
            StructField("memLastUpdated", StringType(), True),
            StructField("multipartyApplicationCheckDocumentSubmittedDate", StringType(), True),
            StructField("programmeDocumentReviewedByEstDate", StringType(), True),
            StructField("publicSectorEqualityDutySubmittedDate", StringType(), True),
            StructField("statutoryConsultationPeriodEndDate", StringType(), True),
            StructField("submissionOfDraftDocumentsDate", StringType(), True),
            StructField("updatedProgrammeDocumentReceivedDate", StringType(), True),
            StructField("courtDecisionDate", StringType(), True),
            StructField("decisionChallengeSubmissionDate", StringType(), True),
            StructField("courtDecisionOutcomeText", StringType(), True),
            StructField("recommendation", StringType(), True),
            StructField("additionalComments", StringType(), True),
            StructField("caAndTpEvidence", StringType(), True),
            StructField("fastTrackAdmissionDocument", StringType(), True),
            StructField(
                "meetings",
                ArrayType(
                    StructType(
                        [
                            StructField("meetingId", StringType(), True),
                            StructField("meetingAgenda", StringType(), True),
                            StructField("planningInspectorateRole", StringType(), True),
                            StructField("meetingDate", StringType(), True),
                            StructField("meetingType", StringType(), True),
                            StructField("estimatedPrelimMeetingDate", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("multipartyApplicationCheckDocument", StringType(), True),
            StructField("newMaturity", StringType(), True),
            StructField("numberBand2Inspectors", DoubleType(), True),
            StructField("numberBand3Inspectors", DoubleType(), True),
            StructField("programmeDocumentURI", StringType(), True),
            StructField("publicSectorEqualityDuty", StringType(), True),
            StructField("subProjectType", StringType(), True),
            StructField("tier", StringType(), True),
            StructField("s61SummaryURI", StringType(), True),
            StructField("planProcessEvidence", BooleanType(), True),
            StructField("issuesTracker", StringType(), True),
            StructField("essentialFastTrackComponents", BooleanType(), True),
            StructField("principalAreaDisagreementSummaryStmt", StringType(), True),
            StructField("policyComplianceDocument", StringType(), True),
            StructField("designApproachDocument", StringType(), True),
            StructField("matureOutlineControlDocument", StringType(), True),
            StructField(
                "invoices",
                ArrayType(
                    StructType(
                        [
                            StructField("invoiceStage", StringType(), True),
                            StructField("invoiceNumber", StringType(), True),
                            StructField("amountDue", DoubleType(), True),
                            StructField("paymentDueDate", StringType(), True),
                            StructField("invoicedDate", StringType(), True),
                            StructField("paymentDate", StringType(), True),
                            StructField("refundCreditNoteNumber", StringType(), True),
                            StructField("refundAmount", DoubleType(), True),
                            StructField("refundIssueDate", StringType(), True),
                        ]
                    ),
                    True,
                ),
                True,
            ),
            StructField("operationsLeadIds", ArrayType(StringType(), True), True),
            StructField("operationsManagerIds", ArrayType(StringType(), True), True),
            StructField("caseManagerIds", ArrayType(StringType(), True), True),
            StructField("leadInspectorIds", ArrayType(StringType(), True), True),
            StructField("environmentalServicesOfficerIds", ArrayType(StringType(), True), True),
            StructField("legalOfficerIds", ArrayType(StringType(), True), True),
            StructField("migrated", StringType(), True),
            StructField("ODTSourceSystem", StringType(), True),
            StructField("SourceSystemID", StringType(), True),
            StructField("IngestionDate", TimestampType(), True),
            StructField("ValidTo", StringType(), True),
            StructField("RowID", StringType(), True),
            StructField("isMaterialChange", BooleanType(), True),
            StructField("IsActive", StringType(), True),
        ]
    )


def _service_bus_row(**overrides):
    row = {
        "NSIPProjectInfoInternalID": None,
        "caseId": 3003,
        "caseReference": "EN030003",
        "projectName": "Project",
        "projectNameWelsh": None,
        "projectDescription": "Project description",
        "projectDescriptionWelsh": None,
        "decision": "approved",
        "publishStatus": "published",
        "sector": "transport",
        "projectType": "rail",
        "sourceSystem": "ODT",  #
        "stage": "pre-application",
        "projectLocation": "Cardiff",
        "projectLocationWelsh": "Caerdydd",
        "projectEmailAddress": "picard@example.com",
        "regions": ["wales"],
        "transboundary": False,
        "easting": 1,
        "northing": 2,
        "welshLanguage": False,
        "mapZoomLevel": "medium",
        "secretaryOfState": "SoS",
        "datePINSFirstNotifiedOfProject": None,
        "dateProjectAppearsOnWebsite": None,
        "anticipatedSubmissionDateNonSpecific": None,
        "anticipatedDateOfSubmission": None,
        "screeningOpinionSought": None,
        "screeningOpinionIssued": None,
        "scopingOpinionSought": None,
        "scopingOpinionIssued": None,
        "section46Notification": None,
        "dateOfDCOSubmission": None,
        "deadlineForAcceptanceDecision": None,
        "dateOfDCOAcceptance": None,
        "dateOfNonAcceptance": None,
        "dateOfRepresentationPeriodOpen": None,
        "dateOfRelevantRepresentationClose": None,
        "extensionToDateRelevantRepresentationsClose": None,
        "dateRRepAppearOnWebsite": None,
        "dateIAPIDue": None,
        "rule6LetterPublishDate": None,
        "preliminaryMeetingStartDate": None,
        "notificationDateForPMAndEventsDirectlyFollowingPM": None,
        "notificationDateForEventsDeveloper": None,
        "dateSection58NoticeReceived": None,
        "confirmedStartOfExamination": None,
        "rule8LetterPublishDate": None,
        "deadlineForCloseOfExamination": None,
        "dateTimeExaminationEnds": None,
        "stage4ExtensionToExamCloseDate": None,
        "deadlineForSubmissionOfRecommendation": None,
        "dateOfRecommendations": None,
        "stage5ExtensionToRecommendationDeadline": None,
        "deadlineForDecision": None,
        "confirmedDateOfDecision": None,
        "stage5ExtensionToDecisionDeadline": None,
        "jRPeriodEndDate": None,
        "dateProjectWithdrawn": None,
        "migrationStatus": True,
        "dateOfReOpenRelevantRepresentationStart": None,
        "dateOfReOpenRelevantRepresentationClose": None,
        "IsActive": "Y",
        "inceptionMeetingDate": None,
        "draftDocumentSubmissionDate": None,
        "programmeDocumentSubmissionDate": None,
        "estimatedScopingSubmissionDate": None,
        "consultationMilestoneAdequacyDate": None,
        "principalAreaDisagreementSummaryStmtSubmittedDate": None,
        "policyComplianceDocumentSubmittedDate": None,
        "designApproachDocumentSubmittedDate": None,
        "caAndTpEvidenceSubmittedDate": None,
        "caseTeamIssuedCommentsDate": None,
        "fastTrackAdmissionDocumentSubmittedDate": None,
        "matureOutlineControlDocumentSubmittedDate": None,
        "memLastUpdated": None,
        "multipartyApplicationCheckDocumentSubmittedDate": None,
        "programmeDocumentReviewedByEstDate": None,
        "publicSectorEqualityDutySubmittedDate": None,
        "statutoryConsultationPeriodEndDate": None,
        "submissionOfDraftDocumentsDate": None,
        "updatedProgrammeDocumentReceivedDate": None,
        "courtDecisionDate": None,
        "decisionChallengeSubmissionDate": None,
        "courtDecisionOutcomeText": None,
        "recommendation": None,
        "additionalComments": None,
        "caAndTpEvidence": None,
        "fastTrackAdmissionDocument": None,
        "meetings": None,
        "multipartyApplicationCheckDocument": None,
        "newMaturity": None,
        "numberBand2Inspectors": None,
        "numberBand3Inspectors": None,
        "programmeDocumentURI": None,
        "publicSectorEqualityDuty": None,
        "subProjectType": None,
        "tier": None,
        "s61SummaryURI": None,
        "planProcessEvidence": None,
        "issuesTracker": None,
        "essentialFastTrackComponents": None,
        "principalAreaDisagreementSummaryStmt": None,
        "policyComplianceDocument": None,
        "designApproachDocument": None,
        "matureOutlineControlDocument": None,
        "invoices": None,
        "operationsLeadIds": ["lead-1"],
        "operationsManagerIds": ["mgr-1"],
        "caseManagerIds": ["case-mgr-1"],
        "leadInspectorIds": ["lead-inspector-1"],
        "environmentalServicesOfficerIds": ["env-1"],
        "legalOfficerIds": ["legal-1"],
        "ODTSourceSystem": "Horizon",
        "SourceSystemID": "SRC-1",
        "IngestionDate": datetime(2025, 1, 10, 9, 0, 0),
        "ValidTo": None,
        "isMaterialChange": False,
    }
    row.update(overrides)
    return row


def _horizon_row(**overrides):
    row = {
        "ingested_datetime": datetime(2025, 3, 1, 10, 0, 0),
        "expected_from": None,
        "expected_to": None,
        "casecreateddate": "2024-12-01",
        "projectname": "Project",
        "projectstatus": "not published",
        "examtimetablepublishstatus": "published",
        "sector": "transport",
        "projecttype": "rail",
        "stage": "pre-application",
        "casereference": "EN030003",
        "horizoncasenumber": "3003",
        "projectlocation": "Cardiff",
        "projectemailaddress": "picard@example.com",
        "twitteraccountname": "@hzproject",
        "region": "wales",
        "easting": 1,
        "northing": 2,
        "transboundary": False,
        "welshlanguage": True,
        "exasize": "large",
        "mapzoomlevel": "HIGH",
        "projectdescription": "Project description",
        "sos": "SoS",
        "tene": "TEN-E",
        "anticipatedsubmissiondatenonspecific": None,
        "dateprojectappearsonwebsite": None,
        "dateofdcoacceptance": None,
        "anticipateddateofsubmission": None,
        "dateofdcosubmission": None,
        "dateofrepresentationperiodopen": None,
        "dateofrelevantrepresentationclose": None,
        "daterrepappearonwebsite": None,
        "confirmedstartofexamination": None,
        "datetimeexaminationends": None,
        "stage4extensiontoexamclosedate": None,
        "stage5extensiontorecommendationdeadline": None,
        "dateofrecommendations": None,
        "confirmeddateofdecision": None,
        "stage5extensiontodecisiondeadline": None,
        "dateprojectwithdrawn": None,
        "section46notification": None,
        "datepinsfirstnotifiedofproject": None,
        "screeningopinionsought": None,
        "screeningopinionissued": None,
        "scopingopinionsought": None,
        "scopingopinionissued": None,
        "deadlineforacceptancedecision": None,
        "datesection58noticereceived": None,
        "preliminarymeetingstartdate": None,
        "deadlineforcloseofexamination": None,
        "deadlineforsubmissionofrecommendation": None,
        "deadlinefordecision": None,
        "jrperiodenddate": None,
        "extensiontodaterelevantrepresentationsclose": None,
        "summary": "Horizon summary",
        "promotername": "Promoter Ltd",
        "applicantfirstname": "Jane",
        "applicantlastname": "Doe",
        "addressline1": "1 High Street",
        "addressline2": None,
        "addresstown": "Cardiff",
        "addresscounty": "South Glamorgan",
        "postcode": "CF10 1AA",
        "applicantemailaddress": "applicant@example.com",
        "applicantwebaddress": "https://example.com",
        "applicantphonenumber": "01234567890",
        "applicantdescriptionofproject": "Project description from applicant",
        "casenodeid": 3003,
        "projectNameWelsh": None,
        "projectDescriptionWelsh": None,
        "projectLocationWelsh": "Caerdydd",
        "input_file": None,
        "ingested_by_process_name": None,
        "modified_datetime": None,
        "modified_by_process_name": None,
        "entity_name": None,
        "file_id": None,
        "salutation": None,
    }
    row.update(overrides)
    return row


def _final_table_row(**overrides):
    # Generated by feeding the mock data in the source notebook
    row = {
        "NSIPProjectInfoInternalID": 2,
        "caseId": 3003,
        "casereference": "EN030003",
        "projectname": "Project",
        "projectDescription": "Project description",
        "decision": "approved",
        "publishStatus": "published",
        "sector": "transport",
        "projectType": "rail",
        "sourceSystem": "ODT",
        "stage": "pre-application",
        "projectLocation": "Cardiff",
        "projectLocationWelsh": "Caerdydd",
        "projectEmailAddress": "picard@example.com",
        "Regions": ["wales"],
        "transboundary": False,
        "easting": 1,
        "northing": 2,
        "welshLanguage": False,
        "mapZoomLevel": "medium",
        "secretaryOfState": "SoS",
        "migrationStatus": True,
        "operationsLeadIds": ["lead-1"],
        "operationsManagerIds": ["mgr-1"],
        "caseManagerIds": ["case-mgr-1"],
        "leadInspectorIds": ["lead-inspector-1"],
        "environmentalServicesOfficerIds": ["env-1"],
        "legalOfficerIds": ["legal-1"],
        "migrated": "1",
        "ODTSourceSystem": "Horizon",
        "SourceSystemID": "SRC-1",
        "IngestionDate": datetime(2025, 4, 1, 10, 0, 0),
        "RowID": "",  # "a4380923dd651c195b1631af7c829187",
        "isMaterialChange": False,
        "IsActive": "Y",
    }
    row.update(overrides)
    return row


class TestNsipProjectHarmonisationProcess(ETLTestCase):
    @pytest.fixture(scope="module", autouse=True)
    def setup(self, request):
        with mock.patch("notebookutils.mssparkutils.runtime.context", {"pipelinejobid": "some_guid", "isForPipeline": True}):
            with mock.patch.object(SynapseLegacyDeltaIO, "_format_to_adls_path", format_to_adls_path):
                with mock.patch.object(Util, "get_storage_account", return_value="pinsstodwdevuks9h80mb.dfs.core.windows.net"):
                    with mock.patch.object(Util, "get_path_to_file", generate_local_path):
                        with mock.patch.object(LoggingUtil, "__new__"):
                            with mock.patch.object(LoggingUtil, "log_info", return_value=None):
                                with mock.patch.object(LoggingUtil, "log_error", return_value=None):
                                    yield

    def compare_final_tables(self, expected: DataFrame, actual: DataFrame):
        uncomparable_cols = {"RowID", "IngestionDate", "ValidTo"}
        comparable_cols = set(_final_table_schema().names) - uncomparable_cols
        expected_cleaned = expected.select(*comparable_cols)
        actual_cleaned = actual.select(*comparable_cols)
        assert_dataframes_equal(expected_cleaned, actual_cleaned, True)

    def test__nsip_project_harmonisation_process__run__with_existing_data(self):
        spark = PytestSparkSessionUtil().get_spark_session()
        service_bus_data = spark.createDataFrame(
            (
                _service_bus_row(
                    caseid=1001,
                    HorizonCaseNumber="1001",
                    casereference="EN010001",
                    projectname="Unchanged record",
                    IngestionDate=datetime(2025, 2, 1, 10, 0, 0),
                    RowID=1,
                ),
                _service_bus_row(  # Updated row
                    caseid=3003,
                    HorizonCaseNumber="3003",
                    casereference="EN030003",
                    projectname="Updated record",
                    IngestionDate=datetime(2025, 4, 1, 10, 0, 0),
                    RowID=2,
                ),
                _service_bus_row(  # New row
                    caseid=3004,
                    HorizonCaseNumber="3004",
                    casereference="EN030004",
                    projectname="New record",
                    IngestionDate=datetime(2025, 4, 1, 10, 0, 0),
                    RowID=2,
                ),
            ),
            schema=_service_bus_schema(),
        )
        self.write_existing_table(spark, service_bus_data, "sb_ti_nphp_r_wed", "odw_harmonised_db", "odw-harmonised", "sb_ti_nphp_r_wed", "overwrite")
        horizon_data = spark.createDataFrame(
            (
                _horizon_row(
                    caseNodeId=1001,
                    HorizonCaseNumber="1001",
                    casereference="EN010001",
                    projectname="Unchanged record",
                    ingestion_date=datetime(2025, 2, 1, 10, 0, 0),
                ),
                _horizon_row(
                    caseNodeId=3003,
                    HorizonCaseNumber="3003",
                    casereference="EN030003",
                    projectname="Updated record",
                    ingestion_date=datetime(2025, 3, 1, 10, 0, 0),
                ),
            ),
            schema=_horizon_schema(),
        )
        self.write_existing_table(spark, horizon_data, "ti_nphp_r_wed", "odw_standardised_db", "odw-standardised", "ti_nphp_r_wed", "overwrite")
        expected_output_table = spark.createDataFrame(
            (
                _final_table_row(),
                _final_table_row(NSIPProjectInfoInternalID=1, ValidTo=datetime(2025, 4, 1, 10, 0, 0), IsActive="N"),
                _final_table_row(NSIPProjectInfoInternalID=3, ValidTo=datetime(2025, 4, 1, 10, 0, 0), IsActive="N"),
            ),
            schema=_final_table_schema(),
        )
        with mock.patch.object(NsipProjectHarmonisationProcess, "HARMONISED_TABLE", "sb_ti_nphp_r_wed"):
            with mock.patch.object(NsipProjectHarmonisationProcess, "HORIZON_TABLE", "ti_nphp_r_wed"):
                with mock.patch.object(NsipProjectHarmonisationProcess, "OUTPUT_TABLE", "ti_nphp_r_wed"):
                    inst = NsipProjectHarmonisationProcess(spark)
                    etl_result = inst.run()
                    assert_etl_result_successful(etl_result)
                    actual_output_table = spark.table("odw_harmonised_db.ti_nphp_r_wed")
                    print("profile stats")
                    self.compare_final_tables(expected_output_table, actual_output_table)
