import odw.test.util.mock.import_mock_notebook_utils  # noqa: F401
from odw.core.etl.transformation.harmonised.nsip_representation_harmonisation_process import NsipRepresentationHarmonisationProcess
from odw.test.util.session_util import PytestSparkSessionUtil
import pyspark.sql.types as T
import mock


def test__nsip_representation_harmonisation_process__run__combines_sources_and_derives_reference_and_migrated():
    spark = PytestSparkSessionUtil().get_spark_session()

    service_bus_data = spark.createDataFrame(
        [
            (
                1,
                10,
                "REF-1",
                "EX-1",
                "EN010001",
                100,
                "Valid",
                "orig1",
                False,
                None,
                None,
                None,
                "Person",
                "repd1",
                "repr1",
                "reg1",
                "Type1",
                "2025-01-01",
                ["A1"],
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                "1",
                "ODT",
                "SRC1",
                "2025-01-01 00:00:00",
                None,
                "",
                "Y",
            ),
        ],
        T.StructType(
            [
                T.StructField("NSIPRepresentaionID", T.IntegerType(), True),
                T.StructField("representationId", T.IntegerType(), True),
                T.StructField("referenceId", T.StringType(), True),
                T.StructField("examinationLibraryRef", T.StringType(), True),
                T.StructField("caseRef", T.StringType(), True),
                T.StructField("caseId", T.IntegerType(), True),
                T.StructField("status", T.StringType(), True),
                T.StructField("originalRepresentation", T.StringType(), True),
                T.StructField("redacted", T.BooleanType(), True),
                T.StructField("redactedRepresentation", T.StringType(), True),
                T.StructField("redactedBy", T.StringType(), True),
                T.StructField("redactedNotes", T.StringType(), True),
                T.StructField("representationFrom", T.StringType(), True),
                T.StructField("representedId", T.StringType(), True),
                T.StructField("representativeId", T.StringType(), True),
                T.StructField("registerFor", T.StringType(), True),
                T.StructField("representationType", T.StringType(), True),
                T.StructField("dateReceived", T.StringType(), True),
                T.StructField("attachmentIds", T.ArrayType(T.StringType()), True),
                T.StructField("caseuniqueid", T.StringType(), True),
                T.StructField("organisationname", T.StringType(), True),
                T.StructField("jobtitle", T.StringType(), True),
                T.StructField("fullname", T.StringType(), True),
                T.StructField("phonenumber", T.StringType(), True),
                T.StructField("emailaddress", T.StringType(), True),
                T.StructField("buildingnumber", T.StringType(), True),
                T.StructField("street", T.StringType(), True),
                T.StructField("town", T.StringType(), True),
                T.StructField("county", T.StringType(), True),
                T.StructField("country", T.StringType(), True),
                T.StructField("postcode", T.StringType(), True),
                T.StructField("attendprelimmeeting", T.StringType(), True),
                T.StructField("AgentFullName", T.StringType(), True),
                T.StructField("AgentOrganisationName", T.StringType(), True),
                T.StructField("agent_phonenumber", T.StringType(), True),
                T.StructField("agent_emailaddress", T.StringType(), True),
                T.StructField("AgentBuildingNumber", T.StringType(), True),
                T.StructField("AgentStreet", T.StringType(), True),
                T.StructField("AgentTown", T.StringType(), True),
                T.StructField("AgentCounty", T.StringType(), True),
                T.StructField("AgentCountry", T.StringType(), True),
                T.StructField("AgentPostcode", T.StringType(), True),
                T.StructField("representatcompacqhearing", T.StringType(), True),
                T.StructField("representatissuehearing", T.StringType(), True),
                T.StructField("representatopenfloorhearing", T.StringType(), True),
                T.StructField("submitlaterreps", T.StringType(), True),
                T.StructField("webreference", T.StringType(), True),
                T.StructField("owneroroccupier", T.StringType(), True),
                T.StructField("powertosell", T.StringType(), True),
                T.StructField("entitledtoclaim", T.StringType(), True),
                T.StructField("other", T.StringType(), True),
                T.StructField("descriptionifother", T.StringType(), True),
                T.StructField("preferredcontactmethod", T.StringType(), True),
                T.StructField("Migrated", T.StringType(), True),
                T.StructField("ODTSourceSystem", T.StringType(), True),
                T.StructField("SourceSystemID", T.StringType(), True),
                T.StructField("IngestionDate", T.StringType(), True),
                T.StructField("ValidTo", T.StringType(), True),
                T.StructField("RowID", T.StringType(), True),
                T.StructField("IsActive", T.StringType(), True),
            ]
        ),
    )

    horizon_data = spark.createDataFrame(
        [
            (
                20,
                "EN010002",
                200,
                "New",
                "orig2",
                "red2",
                "user2",
                "notes2",
                "Organisation",
                "contact2",
                "agent2",
                "Type2",
                "2025-02-01",
                ["A2"],
                "caseu2",
                "org2",
                "job2",
                "full2",
                "phone2",
                "mail2@test.com",
                "12",
                "street2",
                "town2",
                "county2",
                "country2",
                "pc2",
                "yes",
                "agent full",
                "agent org",
                "aphone",
                "amail@test.com",
                "abuild",
                "astreet",
                "atown",
                "acounty",
                "acountry",
                "apost",
                "yes",
                "no",
                "yes",
                "later",
                "web2",
                "owner2",
                "power2",
                "claim2",
                "other2",
                "desc-other2",
                "email",
                "2025-02-01 00:00:00",
                None,
                "Y",
            ),
        ],
        T.StructType(
            [
                T.StructField("relevantrepid", T.IntegerType(), True),
                T.StructField("casereference", T.StringType(), True),
                T.StructField("casenodeid", T.IntegerType(), True),
                T.StructField("RelevantRepStatus", T.StringType(), True),
                T.StructField("representationoriginal", T.StringType(), True),
                T.StructField("representationredacted", T.StringType(), True),
                T.StructField("redactedBy", T.StringType(), True),
                T.StructField("notes", T.StringType(), True),
                T.StructField("RelRepOnBehalfOf", T.StringType(), True),
                T.StructField("contactId", T.StringType(), True),
                T.StructField("agentcontactid", T.StringType(), True),
                T.StructField("RelRepOrganisation", T.StringType(), True),
                T.StructField("dateReceived", T.StringType(), True),
                T.StructField("attachmentId", T.ArrayType(T.StringType()), True),
                T.StructField("caseuniqueid", T.StringType(), True),
                T.StructField("organisationname", T.StringType(), True),
                T.StructField("jobtitle", T.StringType(), True),
                T.StructField("fullname", T.StringType(), True),
                T.StructField("phonenumber", T.StringType(), True),
                T.StructField("emailaddress", T.StringType(), True),
                T.StructField("buildingnumber", T.StringType(), True),
                T.StructField("street", T.StringType(), True),
                T.StructField("town", T.StringType(), True),
                T.StructField("county", T.StringType(), True),
                T.StructField("country", T.StringType(), True),
                T.StructField("postcode", T.StringType(), True),
                T.StructField("attendprelimmeeting", T.StringType(), True),
                T.StructField("agent_fullname", T.StringType(), True),
                T.StructField("agent_organisationname", T.StringType(), True),
                T.StructField("agent_phonenumber", T.StringType(), True),
                T.StructField("agent_emailaddress", T.StringType(), True),
                T.StructField("agent_buildingnumber", T.StringType(), True),
                T.StructField("agent_street", T.StringType(), True),
                T.StructField("agent_town", T.StringType(), True),
                T.StructField("Agent_County", T.StringType(), True),
                T.StructField("Agent_Country", T.StringType(), True),
                T.StructField("agent_postcode", T.StringType(), True),
                T.StructField("representatcompacqhearing", T.StringType(), True),
                T.StructField("representatissuehearing", T.StringType(), True),
                T.StructField("representatopenfloorhearing", T.StringType(), True),
                T.StructField("submitlaterreps", T.StringType(), True),
                T.StructField("webreference", T.StringType(), True),
                T.StructField("owneroroccupier", T.StringType(), True),
                T.StructField("powertosell", T.StringType(), True),
                T.StructField("entitledtoclaim", T.StringType(), True),
                T.StructField("other", T.StringType(), True),
                T.StructField("descriptionifother", T.StringType(), True),
                T.StructField("preferredcontactmethod", T.StringType(), True),
                T.StructField("IngestionDate", T.StringType(), True),
                T.StructField("ValidTo", T.StringType(), True),
                T.StructField("IsActive", T.StringType(), True),
            ]
        ),
    )

    source_system_data = spark.createDataFrame(
        [("SRC_CASEWORK",)],
        ["SourceSystemID"],
    )

    sb_representation_ids = spark.createDataFrame(
        [(10,)],
        ["representationId"],
    )

    source_data = {
        "service_bus_data": service_bus_data,
        "horizon_data": horizon_data,
        "source_system_data": source_system_data,
        "sb_representation_ids": sb_representation_ids,
    }

    with (
        mock.patch(
            "odw.core.etl.transformation.harmonised.nsip_representation_harmonisation_process.Util.get_storage_account",
            return_value="test_storage",
        ),
        mock.patch("odw.core.etl.etl_process.LoggingUtil") as MockEtlLogging,
        mock.patch("odw.core.etl.transformation.harmonised.nsip_representation_harmonisation_process.LoggingUtil") as MockProcessLogging,
    ):
        MockEtlLogging.return_value = mock.Mock()
        MockProcessLogging.return_value = mock.Mock()

        inst = NsipRepresentationHarmonisationProcess(spark)

        with mock.patch.object(inst, "load_data", return_value=source_data), mock.patch.object(inst, "write_data") as mock_write:
            result = inst.run()

    data_to_write = mock_write.call_args[0][0]
    actual_df = data_to_write[inst.OUTPUT_TABLE]["data"]
    rows = {row["representationId"]: row.asDict(recursive=True) for row in actual_df.collect()}

    assert actual_df.count() == 2
    assert rows[10]["Migrated"] == "1"
    assert rows[20]["Migrated"] == "0"
    assert rows[20]["referenceId"] == "EN010002-20"
    assert rows[20]["redacted"] is True

    assert data_to_write[inst.OUTPUT_TABLE]["write_mode"] == "overwrite"
    assert data_to_write[inst.OUTPUT_TABLE]["partition_by"] == ["IsActive"]
    assert result.metadata.insert_count == 2
