parameters:
  agentPool: ''
  env: ''

##
# Run tests for the odw python package.
# Note: These can only run in the build environment due to the build ADO agent having more memory
##
stages:
- stage: RunODWPackageTests
  displayName: 'Run tests for the ODW package in the ${{ parameters.env }} environment'
  condition: |
    and(not(or(failed(), canceled())), eq('${{ parameters.env }}', 'build'))
  jobs:
  - template: ${{variables['System.DefaultWorkingDirectory']}}/pipelines/jobs/run-odw-package-unittests.yaml
    parameters:
      agentPool: ${{ parameters.agentPool }}
      env: ${{ parameters.env }}
  - template: ${{variables['System.DefaultWorkingDirectory']}}/pipelines/jobs/run-odw-package-integrationtests.yaml
    parameters:
      agentPool: ${{ parameters.agentPool }}
      env: ${{ parameters.env }}

